### ISSUE TITLE
The styled-jsx integration relies on hoisting

### ISSUE THREAD

**Issue by arcanis** [vercel/next.js#10149]
# Bug report

## Describe the bug

Next generates files that contain the following import statement:

```ts
import foo from 'styled-jsx/style';
```

Since the output files belong to the project that depends on Next rather than Next itself, the `styled-jsx` dependency needs to be listed in the user project. Based on #9325, I think this isn't what you're looking for.

## Suggested fix

1. Fix `styled-jsx` by:
    - adding a custom import path setting (it's currently [hardcoded](https://github.com/zeit/styled-jsx/blob/a736e3cc8ab5c7ce3db4f01beb0a3f9ee343cc3b/src/_utils.js#L681)).
2. Fix `next` by:
    - adding a new file (let's say `styled-jsx.js`) that contains `module.exports = require('styled-jsx/style')` (it would basically re-export its own dependency)
    - updating the Babel configuration to use `next/styled-jsx` inside the custom import path setting that we will have implemented in 1.

This solution isn't obtrusive, doesn't have breaking changes, and makes Next resilient to problems highlighted in #9325 (and, more importantly to me, makes the default `create-next-app` setup work with Yarn 2 😉).

Note that I likely won't have the resources to make the fix myself right now.

**Comment by Timer** [comment]
Thanks for the ping! Marked to be investigated soon. 🙏

**Comment by therazor** [comment]
judging by the linked issues this should be fixed in `v9.5.3` and above, but I'm having the same problem on that version. Is there anything missing still?

**Comment by masihjahangiri** [comment]
@arcanis @therazor The issue is still unresolved. I get this error:
```
- Required package: styled-jsx (via "styled-jsx/style")
- Required by: /app/components/shared-component/FormsInputsWithLabel.tsx
- event - build page: /next/dist/pages/_error
- wait  - compiling...
- error - ./components/shared-component/FormsInputsWithLabel.tsx
- Module not found: Your application tried to access styled-jsx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

**Comment by masihjahangiri** [comment]
I solved my issue temporary with add `nodeLinker: node-modules` field to `.yarnrc.yml` and run `yarn install` again. I'm waiting for a full solution.

**Comment by merceyz** [comment]
As the error says, you're trying to require `styled-jsx` without declaring it, so if you decalre it, it would work again with PnP

**Comment by masihjahangiri** [comment]
@merceyz I'm tried to import styled-jsx but I can't find any way to import it to my component. Do you have any idea that how to import it to a next.js component? I think in build time babel handle importing.

**Comment by jordinl83** [comment]
Any thoughts on fixing this? 

I've created an example application that reproduces this issue:

See: https://github.com/jordinl83/yarn-styled-jsx-bug

To reproduce, just run:

```
yarn
yarn dev
```

And navigate to [localhost:3000](http://localhost:3000). You should see the error:

```
Module not found: Your application tried to access styled-jsx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

Also, in branch [with-styled-jsx-installed](https://github.com/jordinl83/yarn-styled-jsx-bug/compare/with-styled-jsx-installed) I tried adding `styled-jsx` as a dependency, which seems to have the unintended consequence of not generating the CSS at build time. 

To reproduce:

```
git checkout with-styled-jsx-installed
yarn build
yarn start
```
Navigate to [localhost:3000](http://localhost:3000), open developer console and disable javascript. You'll notice that styles are not applied when reloading the page.

cc @timneutkens

**Comment by jordinl83** [comment]
@timneutkens @Timer Added failing test for `styled-jsx` and PNP: https://github.com/vercel/next.js/pull/21320

Let me know if you would like me to attempt to fix it and what would be the best approach. I see @arcanis gave a recommendation in the description of this issue, so I could try that?
