### ISSUE TITLE
Jump link anchors dont work

### ISSUE THREAD

**Issue by RenatoSerra22** [vercel/next.js#11109]
# Bug report

## Describe the bug

When clicking an anchor tag in a different page with a jump to id tag, it raises an error and doesnt go.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

` <a
                  className='nav-link'
                  href='https://github.com/zeit/next.js/#documentation'
                >
                  Docs
                </a>
`
## Expected behavior

should redirect to github and scroll to documentation tag

## Screenshots

<img width="452" alt="Screenshot 2020-03-16 at 15 13 05" src="https://user-images.githubusercontent.com/12633730/76773477-6e37da00-679a-11ea-852d-5c5e4f640b82.png">

## System information

- Browser (if applies): Chrome
- Nextjs version: 9.1.6

## Additional context

I've tried this in another project without nextjs and it works fine i also tried in a random 
place like

https://jsfiddle.net/uqxck4jv/

**Comment by djnorrisdev** [comment]
I get that it finds the documentation section with your link (maybe), but will changing the href to this will resolve the error? `https://github.com/zeit/next.js/#user-content-documentation`

**Comment by RenatoSerra22** [comment]
same error with that or anything that has `#some_element_id`

**Comment by thislogancall** [comment]
I believe I'm also experiencing this issue. Although I am not getting the error, the jump link to a different page doesn't work. It goes to that page but not the 'jump' section.

**Comment by rs-8** [comment]
@thislogancall 
have same thing

**Comment by djnorrisdev** [comment]
> same error with that or anything that has `#some_element_id` to jump to, if i remove it, it works fine to just go to `https://github.com/zeit/next.js` for example

I thought I had it resolved, but in production I'm having the same issue.

**Comment by kmturley** [comment]
I have a similar issue when using anchor tags inside markdown:
`## [Heading](#anchor-tag)`

Clicking them doesn't jump to the correct section. However it works on this page here:
https://nextjs.org/docs/api-reference/cli#build

**Comment by Seybo** [comment]
Same issue. Page doesn't scroll to jump link if come from another page. Jump links only work within the same page

**Comment by landsman** [comment]
Same problem

**Comment by Seybo** [comment]
Any updates here? In the light of NextJs 10 release? 
Maybe somebody can post a clear workaround here for the time being?
I've tried several approaches found on SO but couldn't make it work.

**Comment by talaikis** [comment]
My ultra-nonsensical solution for this problem, as I needed it asap:

```js
useEffect(() => {
    const path = window.location.hash
    if (path && path.includes('#')) {
      const id = path.replace('#', '')
      const el = window.document.getElementById(id)
      const r = el.getBoundingClientRect()
      window.scrollTo({
        top: r.top,
        behavior: 'smooth'
      })
    }
  })
```

**Comment by Seybo** [comment]
Here is how i adapted the above because it doesn't work on mobile for me:
```javascript
  React.useEffect(() => {
    const path = window.location.hash
    if (path && path.includes("#")) {
      setTimeout(() => {
        const id = path.replace("#", "")
        const el = window.document.getElementById(id)
        const r = el.getBoundingClientRect()
        window.top.scroll({
          top: pageYOffset + r.top,
          behavior: "smooth",
        })
      }, 600)
    }
```

**Comment by Radmehr-aghdam** [comment]
Fixed on Next.js v10

**Comment by yuvilio** [comment]
We were still seeing this no scrolling to anchor issue in next 10 (on initial page load, works fine if you're already navigating). For some reason the `getBoundingClientRect` wasn't correctly calculating the scroll position..  We used `scrollIntoView`.

```js
  useEffect(() => {
    const path = window.location.hash;
    if (path && path.includes('#')) {
      const id = path.replace('#', '');
      if (id) {
        document
          .querySelector('#' + id)
          .scrollIntoView({ behavior: 'smooth' });
      }
    }
  });
```

**Comment by WiseClock** [comment]
Next.js ^10 fixed it for ASCII anchors, I'm still having problems with CJK characters.

**Comment by Radmehr-aghdam** [comment]
> Next.js ^10 fixed it for ASCII anchors, I'm still having problems with CJK characters.

I have no idea about CJK chars but I think you can use Unicode instead of direct CJK

this link may be useful:
https://www.key-shortcut.com/en/writing-systems/%E6%96%87%E5%AD%97-chinese-cjk/cjk-characters-1

**Comment by goodroot** [comment]
This issue is still present on Next.js `11.0.1`.

**Comment by MincePie** [comment]
has anyone figured out a solution to this. I can't get anchor tags working with next.js at all (same page content).

**Comment by JohnTelford** [comment]
I have this issue in Next.js 11.1.1. also

**Comment by papertokyo** [comment]
Same here. The links navigate to the page and the hash is preserved, but it doesn't jump to the linked section. If you refresh, the hash remains but the rest of the path disappears so you end up on the home page with the hash appended.

**Comment by jasdeepsingh** [comment]
Have this exact same issue. 

Why is this not a priority for the Nextjs team? This is breaking a pretty common web pattern for any sites built on top of Nextjs.

**Comment by xiaolin** [comment]
Came across this and using ref to scroll into view.

e.g. when navigating to `/examplepage/#mySection` or `/examplepage/#myOtherSection`

```jsx
const ExamplePage = () => {
  const mySection = useRef(null);
  const myOtherSection = useRef(null);

  useEffect(() => {
    const path = window.location.hash;
    if (path && path.includes('#')) {
      const sectionName = path.replace('#', '');
      switch (sectionName) {
        case 'mySection':
          mySection.current.scrollIntoView({ behavior: 'smooth' });
          break;
        case 'myOtherSection':
          myOtherSection.current.scrollIntoView({ behavior: 'smooth' });
          break;
        default:
          break;
      }
    }
  }, [window.location.hash]);

  return (
    <div>
      <section ref={mySection}>
         My section
      </section>
      <section ref={myOtherSection}>
         My other section
      </section>
    </div>
  )
}
```

**Comment by Radmehr-aghdam** [comment]
Just use `Link` component instead of `a` tag =)

**Comment by dmudro** [comment]
I am surprised to see this issue which breaks essential [scroll to fragment spec](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier).

The above fixes are all based client side JS / DOM telling the user agent to scroll into the fragment via either re-setting the `window.location.hash` or calling `document.scrollIntoView`, wrapped in `useEffect`. If you want to work this globally on all pages, you'd need to add this to `_app.js` or above `_document.js`.

The issue is, in the context of Next.js, the DOM is strangely not fully ready at the hook execution, i. e. `document.querySelector('#fragment')` might return `null`. I suspect this is why folks started wrapping the logic inside a `setTimeout`; using a timer to get around such issue is almost always a code smell in first place.

This will require Next.js core fix I am afraid.

**Comment by dmudro** [comment]
Been trying to fix this by subscribing to a _on dom ready_ event in `_document.tsx`, which unsurpsigingly is not work inside a React app:

```
// following does not work
<script
  dangerouslySetInnerHTML={{
    __html: `document.addEventListener('DOMContentLoaded', () => { const hash = window.location.hash; console.log('DOMContentLoaded hash', hash); const el = hash && document.querySelector(hash); console.log('DOMContentLoaded el', el); el && el.scrollIntoView({ behavior: 'smooth' }); });`
  }}
/>
```

_On window load_ would work, although the UX might be undesirable as the user could already interacted with the page bofore all assets are loaded:

```
<script
  dangerouslySetInnerHTML={{
  __html: `window.addEventListener('load', () => { const hash = window.location.hash; console.log('window.load hash', hash); const el = hash && document.querySelector(hash); console.log('window.load el', el); el && el.scrollIntoView({ behavior: 'smooth' }); });`
}}
/>
```

...hopefully that will give someone a good idea how to come up with a robust fix.

In theory it could work by subscribing to one of [Router events](https://nextjs.org/docs/api-reference/next/router#routerevents) and do the fragment scrolling business there but I am unable to get the router events working in my app right now.

**Comment by TheGodOfAwesome** [comment]
Found a simple HTML work around 
Wrap the components you want to jump to in basic divs with the id so that nextjs can SSR them and the add then link to the di as usual no js required



```
export default function Home() {

  return (
    <div>
      <Head>
        <title>Example</title>
        <meta name="description" content="Nfts" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="waitlist">
        <ImageInfoCard/>
      </div>
      <div id="explore">
        <Explorer/>
      </div>
    </div>
  )
}

<Link href="#waitlist">Subscribe</Link>
```

**Comment by TheoOliveira** [comment]
Just install https://www.npmjs.com/package/react-scrollchor and worked! Have a nice day of coding guys!

**Comment by ibraheemsulay** [comment]
> Been trying to fix this by subscribing to a _on dom ready_ event in `_document.tsx`, which unsurpsigingly is not work inside a React app:
> 
> ```
> // following does not work
> <script
>   dangerouslySetInnerHTML={{
>     __html: `document.addEventListener('DOMContentLoaded', () => { const hash = window.location.hash; console.log('DOMContentLoaded hash', hash); const el = hash && document.querySelector(hash); console.log('DOMContentLoaded el', el); el && el.scrollIntoView({ behavior: 'smooth' }); });`
>   }}
> />
> ```
> 
> _On window load_ would work, although the UX might be undesirable as the user could already interacted with the page bofore all assets are loaded:
> 
> ```
> <script
>   dangerouslySetInnerHTML={{
>   __html: `window.addEventListener('load', () => { const hash = window.location.hash; console.log('window.load hash', hash); const el = hash && document.querySelector(hash); console.log('window.load el', el); el && el.scrollIntoView({ behavior: 'smooth' }); });`
> }}
> />
> ```
> 
> ...hopefully that will give someone a good idea how to come up with a robust fix.
> 
> In theory it could work by subscribing to one of [Router events](https://nextjs.org/docs/api-reference/next/router#routerevents) and do the fragment scrolling business there but I am unable to get the router events working in my app right now.

Where is the script tag meant to be placed? is it in the page component head tag?

**Comment by robksawyer** [comment]
I ended up integrating https://www.npmjs.com/package/react-scroll and that worked pretty well. It'd be nice to use a simple Link tag though.

```
 React.useLayoutEffect(() => {
    const scrollHash = () => {
      scroller.scrollTo(section, {
        duration: 1000,
        delay: 0,
        smooth: true,
      });
    };
    if (section) {
      setTimeout(scrollHash, 700);
    }
  }, []);
```

**Comment by GregBorrelly** [comment]
Seeing the same issue on `Next v12.0.9` - anchors work when you click a link within the same page, but if you refresh or navigated to another page by clicking `<Link href={"/secondPage#subsection"} >` you end up at the top of page.

**Comment by dmudro** [comment]
> Seeing the same issue on `Next v12.0.9` - anchors work when you click a link within the same page, but if you refresh or navigate to another page by clicking `<Link href={"/secondPage#subsection"} >` you end up at the top of page. 

make sure that the #subsection element is not behind some async logic or anything that would cause that element not be in the DOM yet i. e. at render time in the full refresh scenario

**Comment by remcode-remco** [comment]
> Maybe it's useful for somebody: Still far from a sensible fix, but this code saved me from calculating object positions etc.
> 
> It's using the native browser function by just reseting the hash.
> 
> ```ts
>   useEffect(() => {
>     const hash = window.location.hash
>     window.location.hash = ''
>     window.location.hash = hash
>   })
> ```

This is a quick uncomplicated fix, thanks!

**Comment by jmayergit** [comment]
If you have conditionally rendered elements you can use a setTimeout with 0 seconds to wait until the next JS event loop

```TS
  const jumpToUrlFragment = () => {
    const hash = window.location.hash;
    if (hash.length > 0) {
      const element = document.querySelector(hash);
      element && element.scrollIntoView();
    }
  };

  useEffect(() => {
    if (!loading) {
      const timerId = setTimeout(() => {
        jumpToUrlFragment();
      }, 0);

      return () => clearTimeout(timerId);
    }
  }, [loading]);
```

**Comment by jmayergit** [comment]
> This was super helpful... thanks a lot

Yeah I found @dmudro 's answer helpful as well. As he says setTimeout is not optimal but I think we all know this. Importantly he encourages us to find the potential problem causing our errors
