### ISSUE TITLE
Apply API middlewares to getServerSideProps

### ISSUE THREAD

**Issue by aperaham** [vercel/next.js#11126]
# Feature request
API request handlers use middleware (such as cookie parsing). I was surprised to find that `getServerSideProps` does not apply similar middleware as well, and I believe this would be a rather straightforward and desirable feature to include by default. 

For instance, if I were to create a new API endpoint, the cookie parser attached to the `req` object is available to use.

```jsx
// pages/api/endpoint.js
export default (req, res) => {
  if (req.cookies.myCookie) {
    // do something with cookie
  }
  res.statusCode = 200
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ name: 'John Doe' }))
} 
```
However, it seems the cookie parser (API middleware) is not applied to `getServerSideProps` and so the following example does not work as desired:
```jsx
// pages/Page.js
export async function getServerSideProps({ req, res }) {
  if (req.cookies.myCookie) { /* cookie parser object not available */ }

  res.statusCode = 200
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ name: 'John Doe' }))
```

## Describe the solution you'd like
Apply API middleware to `getServerSideProps` by default.

### Thanks!
**Thank you** for all of your amazing work on next.js!

**Comment by arnaudpeich** [comment]
FWIW I wrote this little utility for my project:

```ts
import { GetServerSideProps } from 'next'
import { apiResolver } from 'next/dist/next-server/server/api-utils'

export const enrichContext = async (
  context: Parameters<GetServerSideProps>[0],
  middleware?: (req, res, next) => Promise<void>
) => {
  const dummyApiContext = {
    previewModeEncryptionKey: undefined,
    previewModeId: undefined,
    previewModeSigningKey: undefined
  }
  const handler = async (req, res, next) => {
    if (middleware) await middleware(req, res, next)
  }
  await apiResolver(context.req, context.res, {}, handler, dummyApiContext)
}
``` 

The `apiResolver` will add the query, body and cookies properties to `req`. You can add your own middleware, _e.g._ `passport` to get `req.user`.

Usage in a page:

```ts
export const getServerSideProps: GetServerSideProps<MyPageProps> = async context => {
  // If you want to use a middleware based on next-connect, make sure to initialize it with a no-op onNoMatch, e.g.:
  // const myMiddleware = require('next-connect')({ onNoMatch: () => {} })
  await enrichContext(context, myMiddleware)
  const { req } = context
  return { props: { whatever: req.body.whatever } }
}
```

**Comment by timneutkens** [comment]
@arnaudpeich note that you're importing Next.js internals making it likely to break your application between any version upgrade.

Feel free to open a PR to add the middlewares being added to pages into Next.js itself.

This looks very wrong btw:

```
res.emit('pipe') // This tells the apiResolver that it's ok if the handler doesn't send a response
```

**Comment by arnaudpeich** [comment]
Yes I agree this is not ideal, and I fixed the exact version of Next in my package.json (the function's signature changed in a recent patch) to 9.3.4.

The `emit('pipe')` is because of this: https://github.com/zeit/next.js/blob/ed1aba0dbb124bd9effaeb7114a07582a7676738/packages/next/next-server/server/api-utils.ts#L67

I'm telling the apiResolver that it's normal if the handler doesn't send a response.

I'll try to take a crack at writing a cleaner version in a PR.

**Comment by katywings** [comment]
I created the following workaround:

```js
import { getCookieParser, setLazyProp, getQueryParser } from 'next/dist/next-server/server/api-utils';

export const hydrateContext = function({ req, params }) {
  // From https://github.com/zeit/next.js/blob/ed1aba0dbb124bd9effaeb7114a07582a7676738/packages/next/next-server/server/api-utils.ts#L42

  // Parsing of cookies
  setLazyProp({ req }, 'cookies', getCookieParser(req))
  // Parsing query string
  setLazyProp({ req, params }, 'query', getQueryParser(req))
}
```

Then you can use it in getServerSideProps like so:
```js
import { csrfHandlerWithContext } from "../lib/csrf";
import { hydrateContext } from "../lib/next";

export const getServerSideProps = async (context) => {
  hydrateContext(context);
  // csurf middleware needs req.cookies
  await csrfHandlerWithContext(context);

  return {
    props: {
      csrf: context.req.csrfToken()
    }
  }
}
```

It seems like the logical step is to solve this using global middlewares - if they some day come :). IMHO This issue, #10325 and probably more issues that I don't know only exist because we don't have global middlewares right now. I didn't have time to look into the internals, but I assume that global middlewares are hard to implement with HMR which could be the reason why we don't have them in the first place?

**Comment by BoiForus** [comment]
I am using next@10.0.3, and I was surprised to find that I can use `context.req.cookies` in my `getServerSideProps`

```javascript
export const getServerSideProps: GetServerSideProps<GameProps> = async (context) => {
  const req = context.req as NextApiRequest
  console.log('cookies:', req.cookies)
  // it works!
  // but there would be a typescript error [Property 'cookies' does not exist on type 'IncomingMessage']
  // if I use 'req.cookies' without the type assertion
  
  return {
    props: {}
  }
}
```

I am now puzzled, whether the middleware is only provided for API routes as said in [https://nextjs.org/docs/api-routes/api-middlewares](https://nextjs.org/docs/api-routes/api-middlewares)

**Comment by karlhorky** [comment]
Wow, looks like https://github.com/vercel/next.js/pull/19724 (reviewed + merged by @timneutkens ) actually added cookies to `getServerSideProps` 🎉 🙌

@aperaham is this enough? Can this issue be closed now?

**Comment by aperaham** [comment]
Brilliant. Looks like this is have been resolved. Thanks, everyone! One less issue in the queue!

**Comment by em** [comment]
It looks like req.query is still missing. Can you reopen this issue?
