### ISSUE TITLE
Preloaded js chunks not being used by browser.

### ISSUE THREAD

**Issue by tankpower1** [vercel/next.js#11215]
# Bug report

## Describe the bug

The preloaded js chunks don't seem to be used by the browser and are redundant even with crossorigin attribute added.

<pre>
Warnings:
A preload <link> was found for "https://***/_next/static/chunks/***.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload <link> was found for "https://***/_next/static/chunks/***.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload <link> was found for "https://***/_next/static/chunks/***.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
</pre>

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Build for production.
2. Run site through lighthouse.
3. See error

## Expected behavior

The preload link should work without any complains from lighthouse otherwise is it even called correctly?

## System information

- Version of Next.js: [9.3.1]

**Comment by timneutkens** [comment]
A complete reproduction is needed.

**Comment by tankpower1** [comment]
I'm just building and uploading my project in order to test in on Pagespeed insights, the error occurs in the `passed audits -> Preload key requests` section. At this time i cannot give a complete reproduction. It's a simple build with v9.3.1 default behaviour.

**Comment by nguyendangkhanh** [comment]
i have same error, https://github.com/drenther/next-pwa and check same step by tankpower1

**Comment by StarpTech** [comment]
Isn't it solved by this https://github.com/zeit/next.js/blob/4ce095df89139bc1dc777465de717a6cb545a923/packages/next/README.md#cdn-support-with-asset-prefix ?

```html
<Head crossOrigin="anonymous">...</Head>
<body>
   <Main/>
   <NextScript crossOrigin="anonymous"/>
</body>
```

**Comment by tankpower1** [comment]
I've tried that exact solution and it didn't seem to change anything.

**Comment by StarpTech** [comment]
Then only a complete reproduction can help.

**Comment by stan-sack** [comment]
Can confirm i'm seeing this as well. 

The links are for pages that im linking to using `<Link href="/my-page-name" />` as described in the docs. If I remove the links then I don't see the warning in the page audit anymore. I have `crossOrigin: "anonymous"` in my next.config.js and im on `next@9.3.5`. Site is deployed using serverless-nextjs-component

**Comment by pinkiebala** [comment]
[NextJS official doc](https://nextjs.org/docs/getting-started) got the same issue.
https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fnextjs.org%2Fdocs%2Fgetting-started

![image](https://user-images.githubusercontent.com/17506890/86462844-e84a9980-bd5e-11ea-8e6a-00d86b5219d0.png)

**Comment by Timer** [comment]
This was resolved in Next.js 9.5+, please upgrade!

**Comment by BernardA** [comment]
I just upgraded to 9.5.3 and still facing same issue: 

All the `crossorigin` attributes are being ignored.

Here how it shows on dev tools: 

![Screenshot 2020-09-03 at 15 50 39](https://user-images.githubusercontent.com/9449665/92124395-046dc400-edfe-11ea-84d6-c8dc00867f73.png)


The code on _document.js

      export default class MyDocument extends Document {
    render() {
        return (
            <Html lang="en">
                <Head>
                    <link rel="dns-prefetch" href="https://ba2pi.com" />
                    <link rel="preconnect" href="https://ba2pi.com" crossOrigin />
                    {/* PWA primary color */}
                    <meta name="theme-color" content={theme.palette.primary.main} />
                    <link
                        rel="preload"
                        as="font"
                        type="font/woff"
                        href="/fonts/roboto-v20-latin-700.woff"
                        crossOrigin
                    />
                    <link
                        rel="preload"
                        as="font"
                        type="font/woff2"
                        href="/fonts/roboto-v20-latin-700.woff2"
                        crossOrigin
                    />
                </Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </Html>
        );
     }
    }

**Comment by AndrsDev** [comment]
I'm still having this issue with Next.js 9.5+ using `next export`

**Comment by BernardA** [comment]
Same here with 9.5.3.

Here is the repo: https://github.com/BernardA/quiamo-client

**Comment by nastari** [comment]
@Timer 
I'm on version 9.5.3 and the problem is here in front of me.

**Comment by Timer** [comment]
This issue is being tracked here:
https://github.com/vercel/next.js/issues/16932
