### ISSUE TITLE
IE11, development, HMR: Object doesn't support property or method 'attachShadow'. 

### ISSUE THREAD

**Issue by aorsten** [vercel/next.js#13231]
# Bug report

## Describe the bug

Basically the nextjs page bugs in IE11 development with the following message.
```
Object doesn't support property or method 'attachShadow'
``` 
It seems related to development hot module reloading. Somehow the `/_next/webpack-hmr` route is caught by express. I have by the way seen similar bugs when using custom routes in pure nextjs pages previously. Unsure if this is related.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Install the `custom-server-express` example.
2. Add this snippet in `server.js`:
```
  server.get('/:one/:two', (req, res) => {
    console.log("Parameters", req.params)
    return res.redirect('/a')
  })
```
3. Open `localhost:3000` in Internet Explorer 11.
4. The page flashes the actual content before going white.
5. Open the console (F12) and the `attachShadow` message flashes indefinitely.
6. In the command window, read the message `Parameters { one: '_next', two: 'webpack-hmr' }`

## Expected behavior

I expected to see my content. I would have also expected that `attachShadow` was either added as a built-in polyfill in nextjs, or that the function was avoided. I believe it can be traced to this location: `@next\react-dev-overlay\lib\internal\components\ShadowPortal.js`. In other locations in the next package you have an if-test to avoid this - it seems to me.

## Screenshots

![image](https://user-images.githubusercontent.com/19666956/82674366-781b0500-9c43-11ea-9921-5b8d29553d24.png)

## System information

- OS: Windows 10
- Browser: IE 11
- Version of Next.js: latest (as per today, using the custom-server-express example)
- Version of Node.js: 10.16.0

## Additional context

I came across this while updating a production package. I wanted to debug the polyfills and find out whether I still need to add polyfills for IE11 after next 9.3. This was a major roadblock.

The real problem here is probably using attachShadow in IE11.

I will try to recreate it without an express server...

**Comment by aorsten** [comment]
Small update - I couldn't immediately recreate the error without an express server, but I didn't pour my soul into it. Would it be an easy fix to add an if-test for attachShadow in the specific place I pointed to?

**Comment by kate-hall** [comment]
I'm having the same error, also using an express server.

**Comment by revolunet** [comment]
same error error here with next@9.4 on IE11 in dev mode. this make IE11 debugging impossible in dev mode

**Comment by tomdohnal** [comment]
I think this could be solved by using webcomponents polyfill (https://github.com/webcomponents/polyfills) in the `packages/react-dev-overlay/lib/internal/components/ShadowPortal.tsx` file.

I could try to make a PR if you'd be interested

**Comment by amigolargo** [comment]
We fixed this in our application using the `@webcomponents/shadydom` polyfill, +1 to @tomdohnal

**Comment by altruisticsoftware** [comment]
@tomdohnal That did it for me, thank you.

@amigolargo - Could you post where exactly you decided to put the polyfill in your app? The issue for us is coming from `<Head />` imported from `next/document`, and if we omit the `<Head />` from `_document.js`, everything breaks from an error unrelated to this one. Obviously we'd still like to use `_document.js`

**Comment by amigolargo** [comment]
@altruisticsoftware in `src/polyfills.js`,  `import '@webcomponents/shadydom';`

It is configured in `next.config.js` within the webpack config like so:

`const originalEntry = config.entry;
    config.entry = async () => {
      const entries = await originalEntry();

      if (
        entries['main.js'] &&
        !entries['main.js'].includes('./src/polyfills.js')
      ) {
        entries['main.js'].unshift('./src/polyfills.js');
      }

      return entries;
    };`

**Comment by Timer** [comment]
Would someone be willing to setup an IE 11 development test suite for us?

It'd be great to fix this and prevent future regressions with CI.

**Comment by revolunet** [comment]
do you have browserstack.com account or another solution to run IE11 tests ?

**Comment by Timer** [comment]
Yes! See how we test Safari 10 using browserstack:
https://github.com/vercel/next.js/blob/b1025995b2645666847d72fb85e65b59b375724f/.github/workflows/build_test_deploy.yml#L115-L133

**Comment by bolatovumar** [comment]
I believe this has been resolved in https://github.com/vercel/next.js/pull/13704? That PR does fix this issue for me.

**Comment by mliq** [comment]
I am still getting this error on next 9.5.3 - is there anything else I need to do to fix it? Production mode works. This is my .browserlistrc in root:

```
# Supported browser list.
# See https://github.com/browserslist/browserslist for more details.

last 2 chrome versions
last 2 ChromeAndroid versions
last 2 edge versions
last 2 firefox versions
last 2 ios_saf versions
last 2 safari versions
ie 11
node 12
```

**Comment by Unsfer** [comment]
I'm getting this error too on old Firefox, using next 9.5.3
```
TypeError: portalNode.current.attachShadow is not a function

	Portal/< webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/components/ShadowPortal.js:37:30

The above error occurred in the <Portal> component:
    in Portal (created by ReactDevOverlay)
```

**Comment by riazXrazor** [comment]
thanks @amigolargo and @tomdohnal ur solution worked

**Comment by haydnhkim** [comment]
dev-build-watcher.js are checking for attachShadow.
https://github.com/vercel/next.js/blob/8426f13713c6a1ac498562479d864633cf355c6d/packages/next/client/dev/dev-build-watcher.js#L18-L26

If you add `@webcomponents/shadydom` polyfill, it does not add a value to prefix, so the css name is applied globally.
The website I am maintaining has a problem because it is using `#container` as its main content wrapper.
`#container` is a universal class naming, so it could be a problem for others.
(Problem only occurs with IE in the development mode)
https://github.com/vercel/next.js/blob/8426f13713c6a1ac498562479d864633cf355c6d/packages/next/client/dev/dev-build-watcher.js#L124-L129

**Comment by jtakahashi0604** [comment]
Thank you @amigolargo and @tomdohnal.

I just fixed this problem with your solution in Next.js 9.5.5.

## package.json
```json
"@webcomponents/shadydom": "^1.7.4"
```

## next.config.js
```javascript
module.exports = {
  webpack: function (config) {
    const originalEntry = config.entry;

    config.entry = async () => {
      const entries = await originalEntry();

      if (
        entries["main.js"] &&
        !entries["main.js"].includes("./src/polyfills.js")
      ) {
        entries["main.js"].unshift("./src/polyfills.js");
      }
      return entries;
    };

    return config;
  },
};
```

## ./src/polyfills.js
```javascript
import "@webcomponents/shadydom";
```

**Comment by mliq** [comment]
^ Above code fixes for me too, can recommend this further optimization to keep that dependency out of prod:

```
if (process.env.NODE_ENV === 'development') {
    require('@webcomponents/shadydom');
}
```

**Comment by oliviertassinari** [comment]
I have found a similar issue. In my case, the dev mode with IE11 is failing on the arrow function of 
https://github.com/vercel/next.js/blob/197d46ddb9bebc4a74360e66f50b091edd811ae0/packages/next/client/next-dev.js#L35

https://github.com/mui-org/material-ui/issues/24316

**Comment by ntsim** [comment]
The overlay styling is also really janky as well (this is with a barebones repo setup with `create-next-app`):

![image](https://user-images.githubusercontent.com/9917868/104219906-a5b4f880-5436-11eb-93f9-7f296c0100b4.png)

**Comment by 1R053** [comment]
The solution of @jtakahashi0604 @jtakahashi0604 and @tomdohnal works to start the site in IE11, but unfortunately breaks nextTranslate (https://www.npmjs.com/package/next-translate) for me. Only the i18nKey values are shown, not the mapped texts. Are there any ideas, how this can be addressed as well?

**Comment by kevinolivar** [comment]
Hi there, 

the fix with the @webcomponents/shadydom did not work for me. :-(

Environment:

    "@nrwl/cli": "12.5.0",
    "@nrwl/cypress": "12.5.0",
    "@nrwl/eslint-plugin-nx": "12.5.0",
    "@nrwl/express": "12.5.0",
    "@nrwl/jest": "12.5.0",
    "@nrwl/linter": "12.5.0",
    "@nrwl/next": "12.5.0",
    "@nrwl/node": "12.5.0",
    "@nrwl/react": "12.5.0",
    "@nrwl/storybook": "12.5.0",
    "@nrwl/tao": "12.5.0",
    "@nrwl/web": "12.5.0",
    "@nrwl/workspace": "12.5.0"

Browserlistrc
```
last 2 versions
> 1%
not dead
not ie <= 11
not op_mini all
```

**Comment by alicerocheman** [comment]
Still getting this error.

**Comment by balazsorban44** [comment]
This is unlikely to get fixed, as Next.js 13 does not support IE11 by default anymore, although the target can still be configured to IE11. See https://nextjs.org/docs/basic-features/supported-browsers-features#browserslist

Modern browsers are much more suited for development and should be the path forward.
