### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#13341]
Follow-up of https://github.com/zeit/next.js/issues/9426, opening this as the overarching issue on what to solve:

- [x] Get rid of buildId and use content hashes for page files
- [x] Simplify on-demand-entries
- [x] Make custom webpack plugins compatible with webpack 5
- [x] Make `resolutions` to webpack 5 use the webpack 5 implementation initially (to allow canary testing / canary to keep being released without any breaking changes)
- [x] Make React Refresh tests pass
- [ ] Make sure there are no deprecation warnings
  - [ ] https://github.com/webpack-contrib/terser-webpack-plugin/pull/283
  - [ ] https://github.com/webpack-contrib/mini-css-extract-plugin (most warnings come from this plugin)
  - [ ] Next.js internal webpack plugins warnings
    - [x] https://github.com/vercel/next.js/pull/15797
    - [x] https://github.com/vercel/next.js/pull/15806
- [ ] Provide polyfills that were removed in webpack 5 like `process` and `Buffer`. We'll likely show a warning when a built-in Node.js module is used where it was not intended, this would ensure backwards compat and significantly less breakage in existing applications. 
  - [x] Add `process` and `buffer`: https://github.com/vercel/next.js/pull/15499

**Comment by TodorTotev** [comment]
@timneutkens If there is anything you would let a non-maintainer help with, I'd be glad to assist.

**Comment by balazsorban44** [comment]
Just sharing this, you may be aware, but it might be useful. #10885

**Comment by arzafran** [comment]
Having the following error, but probably it's related to Theme-UI and they should support Webpack 5
```
error - ./node_modules/@theme-ui/core/dist/index.esm.js
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)
```

It should be a fairly simple fix, but I think it may trigger a chain of fixes needed on other dependencies. we would have to manually change all these from:
```
import { version } from './package.json';	
export default version;	
```
to
```
import packageInfo from './package.json';
export default packageInfo.version;
```

right?

**Comment by dvakatsiienko** [comment]
> Having the following error, but probably it's related to Theme-UI and they should support Webpack 5
> 
> ```
> error - ./node_modules/@theme-ui/core/dist/index.esm.js
> Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)
> ```
> 
> It should be a fairly simple fix, but I think it may trigger a chain of fixes needed on other dependencies. we would have to manually change all these from:
> 
> ```
> import { version } from './package.json';	
> export default version;	
> ```
> 
> to
> 
> ```
> import packageInfo from './package.json';
> export default packageInfo.version;
> ```
> 
> right?

Same error happens to [AWS-amplify](https://github.com/aws-amplify/amplify-js) library.

**Comment by imagentleman** [comment]
Having issues in ie11.

Was able to reproduce with a brand new app created with [create-next-app](https://www.npmjs.com/package/create-next-app).

Error:

I get a blank page showing this on the console:

<img width="1072" alt="Screen Shot 2020-07-29 at 3 02 30 PM" src="https://user-images.githubusercontent.com/2272928/88848021-7cb4ea00-d1ad-11ea-9757-bef362bb6b2e.png">

Steps to reproduce:

1. Install yarn 1.22.4 and node v12.14.1 on MacOS 10.15.6
2. Run `yarn create next-app` as shown on https://nextjs.org/docs
3. Run `yarn dev`
4. Open localhost:3000 (or 10.0.2.2:3000) in ie11 (v11.1339.17763.0) with a win10 image running on virtual box 6.1.12 r139181

Notes: 
Doesn't seem to happen with next.js 9.4.0, next.js 9.4.4 or next.js 9.5.0 in production mode (after running `yarn build` and `yarn start`).

Didn't add `{
  "resolutions": {
    "webpack": "^5.0.0-beta.22"
  }
}` to enable webpack 5. But it also happens with it.
On a real windows device (with similar software installed: win10, ie11, yarn, etc) i'm only getting the first colon error, but everything seems to work (initial page load, fast refresh, etc) unlike with the mac and vm combo. 🤷‍♂️

**Comment by timneutkens** [comment]
> Didn't add { "resolutions": { "webpack": "^5.0.0-beta.22" } } to enable webpack 5

Then this is off topic, please create a new issue.

**Comment by valse** [comment]
Hi, I'm trying to add the webpack 5 beta too but I have this error on compilation:

```Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema```
```configuration[0].module.rules[2].issuer has an unknown property 'test'. These properties are valid```

I have no custom webpack config and I'm using `styled-jsx` with `styled-jsx-plugin-sass` too

**Comment by timneutkens** [comment]
> Hi, I'm trying to add the webpack 5 beta too but I have this error on compilation:
> 
> `Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema`
> `configuration[0].module.rules[2].issuer has an unknown property 'test'. These properties are valid`
> 
> I have no custom webpack config and I'm using `styled-jsx` with `styled-jsx-plugin-sass` too

Are you sure you don't have anything in `next.config.js`, it's practically impossible for this error to occur if you do not have custom webpack configuration, this could be through added plugins.

**Comment by valse** [comment]
> > Hi, I'm trying to add the webpack 5 beta too but I have this error on compilation:
> > `Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema`
> > `configuration[0].module.rules[2].issuer has an unknown property 'test'. These properties are valid`
> > I have no custom webpack config and I'm using `styled-jsx` with `styled-jsx-plugin-sass` too
> 
> Are you sure you don't have anything in `next.config.js`, it's practically impossible for this error to occur if you do not have custom webpack configuration, this could be through added plugins.

Hi @timneutkens, this is my next.config.js and you're right I'm using the 'next-images' plugin:
``` js
const withImages = require("next-images")

module.exports = withImages({
  esModule: true,
  trailingSlash: false,
  env: {
    ...
  },
})
```

**Comment by timneutkens** [comment]
So that likely edits the webpack config in a wrong way which is a bug in that library.

**Comment by valse** [comment]
> So that likely edits the webpack config in a wrong way which is a bug in that library.

Yes it is: switching to the `next-optimized-images` plugin all works as expected... I [open an issue](https://github.com/twopluszero/next-images/issues/42) for the `next-images` plugin. Thanks!

**Comment by Utwo** [comment]
How can I test this with npm instead of yarn?

**Comment by timneutkens** [comment]
> How can I test this with npm instead of yarn?

You can't currently because npm does not support resolutions afaik.

**Comment by zburk** [comment]
Running webpack 5, everything still works for me with the following deprecation warnings. Creating a new nextjs app, I get the same deprecation warnings.

`(node:85371) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
(node:85371) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(node:85371) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'find' is deprecated)
(node:85371) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(node:85371) [DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API`

`"dependencies": {
    "fs-extra": "^9.0.1",
    "lodash": "^4.17.19",
    "next": "9.5.0",
    "next-pwa": "^3.1.1",
    "react": "16.13.1",
    "react-burger-menu": "^2.7.0",
    "react-dom": "16.13.1",
    "react-notifications-component": "^2.4.0",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "styled-components": "^5.1.1",
    "swr": "^0.2.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.5",
    "@babel/preset-env": "^7.10.4",
    "@types/lodash": "^4.14.158",
    "@types/node": "^14.0.26",
    "@types/react": "^16.9.43",
    "@types/react-burger-menu": "^2.6.1",
    "@types/react-notifications-component": "^2.4.0",
    "@types/react-redux": "^7.1.9",
    "@types/socket.io-client": "^1.4.33",
    "@types/styled-components": "^5.1.1",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-styled-components": "^1.10.7",
    "eslint": "^7.5.0",
    "eslint-plugin-react": "^7.20.5",
    "postcss-preset-env": "^6.7.0",
    "redux-devtools": "^3.5.0",
    "tailwindcss": "^1.5.2",
    "typescript": "^3.9.7"
  },`

**Comment by timneutkens** [comment]
@zburk note the todo list on the issue:

>  Make sure there are no deprecation warnings

So your application works fine?

**Comment by zburk** [comment]
> @zburk note the todo list on the issue:
> 
> > Make sure there are no deprecation warnings
> 
> So your application works fine?

Right! The deprecation warnings were the only "errors" I got. Testing the application, I found no issues with anything that weren't already present.

**Comment by Kinbaum** [comment]
I'm using Yarn 2 and I have a Next.js application within a monorepo alongside some other Webpack 5 applications. I have set the resolutions key at the root package.json level. What I've found is that by doing that, it actually breaks my `jsconfig.json`.

I am receiving the following error message in my terminal:
`Module not found: Your application tried to access apollo, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.`

`apollo` is a folder at the root of my Next.js project. Here is my `jsconfig.json`

<details>
	<summary>jsconfig.json</summary>

```json
{
    "compilerOptions": {
        "baseUrl": "."
    }
}
```
</details>

Do you have any guidance on how to resolve this issue? This works fine if I don't add the Webpack 5 resolution

**Comment by nicholaschiang** [comment]
Just added this and got the following warning from Yarn v2:
```
➤ YN0060: │ next@npm:9.5.1 [b17e5] provides webpack@npm:5.0.0-beta.22 with version 5.0.0-beta.22 which doesn't satisfy ^4.4.0 requested by mini-css-extract-plugin@npm:0.8.0
```

**Comment by nicholaschiang** [comment]
Also, got the following errors when running `next dev`:
```
ready - started server on http://0.0.0.0:3000
info  - Loaded env from /home/nchiang/repos/tutorbook/.env
(node:30375) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:30375) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'find' is deprecated)
error - ./.yarn/$$virtual/next-virtual-bd6fa6b147/0/cache/next-npm-9.5.1-e14f31e6e9-effa9056b8.zip/node_modules/next/dist/client/index.js
Module not found: next tried to access querystring, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: querystring (via "querystring")
Required by: next@virtual:b17e57c34ee4c6b233df1a3a139589ec11bfb014df22a34b79dcedd26a7fe182a25be10f2f1c79bfbe9a486560a139af8e03aca7d0382eefce37c81348d30b88#npm:9.5.1 (via /home/nchiang/repos/tutorbook/.yarn/$$virtual/next-virtual-bd6fa6b147/0/cache/next-npm-9.5.1-e14f31e6e9-effa9056b8.zip/node_modules/next/dist/client/)
error - ./.yarn/$$virtual/next-virtual-bd6fa6b147/0/cache/next-npm-9.5.1-e14f31e6e9-effa9056b8.zip/node_modules/next/dist/client/index.js
Module not found: next tried to access querystring, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: querystring (via "querystring")
Required by: next@virtual:b17e57c34ee4c6b233df1a3a139589ec11bfb014df22a34b79dcedd26a7fe182a25be10f2f1c79bfbe9a486560a139af8e03aca7d0382eefce37c81348d30b88#npm:9.5.1 (via /home/nchiang/repos/tutorbook/.yarn/$$virtual/next-virtual-bd6fa6b147/0/cache/next-npm-9.5.1-e14f31e6e9-effa9056b8.zip/node_modules/next/dist/client/)
```

**Comment by Kinbaum** [comment]
I get those as well. Supplying `querystring` as a dependency and adding it to the `.yarnrc.yml` as a peerDependency for next fixes that. Absolute imports are broken though.

**Comment by nicholaschiang** [comment]
Ah, @Kinbaum the `querystring` imports have nothing to do with this issue though (I just included those logs... which I probably shouldn't have). That's a Yarn v2 PNP issue (that should be opened separately).

And then @timneutkens some other issues when using Webpack v5:
```(node:4886) [DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE] DeprecationWarning: MainTemplate.hooks.require is deprecated (use JavascriptModulesPlugin.getCompilationHooks().renderRequire instead)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:4886) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
(node:4886) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(node:4886) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'find' is deprecated)
(node:4886) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(node:4886) [DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
```

**Comment by Kinbaum** [comment]
I think my issue is a valid webpack 5 resolution issue with jsconfig, well within the context of webpack 5 support. I was just addressing your log.

**Comment by timneutkens** [comment]
@Kinbaum can you create a github repo so that I can add it to the integration tests we have?

**Comment by jensmeindertsma** [comment]
I've come across one issue that appears only when upgrading Webpack to v5. I think this is the right place to report it? The issue is about React Context w/ Fast Refresh: I have code in place that warns when a `useContext` hook call returns the default React Context value, because this warns me when I use the React Context outside of a Provider tree. I've extracted it to a custom hook that looks like this:
```ts
export function useTheme() {
  const themeContext = useContext(ThemeContext);

  if (themeContext === null) {
    throw new Error(
      "The `useTheme` hook must be used within a `ThemeProvider` component"
    );
  }

  return themeContext;
}
```

I've placed the Context Provider in `_app.tsx`:
```tsx
const App: FunctionComponent<AppProps> = ({
  Component,
  pageProps,
}) => {
  return (
    <ThemeContext.Provider value="dark">
      <Component {...pageProps} />
    </ThemeContext.Provider>
  );
};
```

In every Next.js page I should now be able to consume this Context without problems. And it works until I start editing the `useTheme.ts` file too much **in development mode:** the error thrown by `useTheme` causes a failure server-side. This means that `useContext` returned the default value: it was called outside of a Provider tree. Which is exactly why I built this safety guard. But with the Context Provider clearly in the correct place, this should not ever happen.

This problems only occurs when using the Webpack 5 beta, when I remove the `resolutions` property and reinstall, this problem does not occur. Also, it only occurs during development.

Please see my [reproduction repository](https://github.com/jensmeindertsma/next-webpack-5) to give it a try yourself.

**Comment by Kinbaum** [comment]
> @Kinbaum can you create a github repo so that I can add it to the integration tests we have?

Hi @timneutkens, here is the [reproduction repo](https://github.com/Kinbaum/broken-jsconfig)

**Comment by jensmeindertsma** [comment]
I just rewrote my report & updated my reproduction repository to show only the absolute basic requirements to reproduce the error. I hope this helps 👍

**Comment by batusai513** [comment]
For me everything is working fine, dev and production builds, this is a medium size app with tailwind css. The only weird thing is the production build size is a bit bigger, but not that much:

Webpack 4
```
Page                                                           Size     First Load JS
┌ ● /                                                          9.95 kB        79.2 kB
├   └ css/2190b3fb6d1d0ad2d42b.css                             632 B
├   /_app                                                      0 B            64.9 kB
├ ○ /404                                                       3.03 kB        67.9 kB
├ λ /api/hello                                                 0 B            64.9 kB
├ ○ /dashboard                                                 263 B          69.5 kB
├ ○ /events                                                    263 B          69.5 kB
├ ○ /help                                                      261 B          69.5 kB
└ ○ /news                                                      261 B          69.5 kB
+ First Load JS shared by all                                  64.9 kB
  ├ chunks/71247caf95475e3ea7f9a0f8a30beb258b23d005.3cfdf7.js  4.65 kB
  ├ chunks/commons.3dfd2b.js                                   10.1 kB
  ├ chunks/framework.d55768.js                                 40 kB
  ├ chunks/main.4cf283.js                                      6.73 kB
  ├ chunks/pages/_app.0dbdb3.js                                2.24 kB
  ├ chunks/webpack.9f6eb1.js                                   1.21 kB
  └ css/cb41026fc56dc753707a.css                               2.64 kB
```

Webpack 5

```
Page                                                           Size     First Load JS
┌ ● /                                                          10.2 kB        79.8 kB
├   └ css/f514e409300bf656c791.css                             632 B
├   /_app                                                      0 B            65.2 kB
├ ○ /404                                                       2.97 kB        68.2 kB
├ λ /api/hello                                                 0 B            65.2 kB
├ ○ /dashboard                                                 267 B          69.8 kB
├ ○ /events                                                    262 B          69.8 kB
├ ○ /help                                                      262 B          69.8 kB
└ ○ /news                                                      263 B          69.8 kB
+ First Load JS shared by all                                  65.2 kB
  ├ chunks/71247caf95475e3ea7f9a0f8a30beb258b23d005.cfb6eb.js  4.56 kB
  ├ chunks/commons.9952b5.js                                   9.99 kB
  ├ chunks/framework.15679f.js                                 40.3 kB
  ├ chunks/main.0e71c7.js                                      6.68 kB
  ├ chunks/pages/_app.b5eddc.js                                2.23 kB
  ├ chunks/webpack.f05468.js                                   1.49 kB
  └ css/12607d53c5831a4d60f7.css                               2.64 kB
```

And these are the warnings when building the production bundle:

```
(node:80834) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(node:80834) [DEP_WEBPACK_MAIN_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: MainTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
(node:80834) [DEP_WEBPACK_CHUNK_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: ChunkTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
(node:80834) [DEP_WEBPACK_MAIN_TEMPLATE_HASH_FOR_CHUNK] DeprecationWarning: MainTemplate.hooks.hashForChunk is deprecated (use JavascriptModulesPlugin.getCompilationHooks().chunkHash instead)
(node:80834) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:80834) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
info  - Using external babel configuration from /Users/richardroncancio/projects/betbox-web/.babelrc
(node:80834) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(node:80834) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:80834) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_LENGTH] DeprecationWarning: chunk.files was changed from Array to Set (using Array property 'length' is deprecated)
(node:80834) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_INDEXER] DeprecationWarning: chunk.files was changed from Array to Set (indexing Array is deprecated)
(node:80834) [DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
(node:80834) [DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API
(node:80834) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(node:80834) [DEP_WEBPACK_CHUNK_GROUP_GET_MODULE_INDEX_2] DeprecationWarning: ChunkGroup.getModuleIndex2 was renamed to getModulePostOrderIndex
Creating an optimized production build 
```

**Comment by justsee** [comment]
Webpack `5.0.0-beta.22` appeared to work fine when I had a look recently. However Webpack `5.0.0-beta.23` appears to fail in resolving dynamic imports when a `jsconfig.json` file is used specifying `"baseUrl": "."`

The issue appears in [this commit](https://github.com/webpack/webpack/commit/b1eac4ab29c569b1c194831750387f5b2775fc42).

A minimal repro is here: https://github.com/justsee/webpack-dynamic-imports.

It just dynamically imports the vercel.svg logo in `pages/index.js`.

The successful commits output an error with the svg data, the failing commit displays: "Server Error Error: Cannot find module './vercel.svg'".

Call stack:

```
processChild
project/node_modules/react-dom/cjs/react-dom-server.node.development.js (3043:14)
resolve
project/node_modules/react-dom/cjs/react-dom-server.node.development.js (2960:5)
ReactDOMServerRenderer.render
project/node_modules/react-dom/cjs/react-dom-server.node.development.js (3435:22)
ReactDOMServerRenderer.read
project/node_modules/react-dom/cjs/react-dom-server.node.development.js (3373:29)
renderToString
project/node_modules/react-dom/cjs/react-dom-server.node.development.js (3988:27)
Object.renderPage
project/node_modules/next/dist/next-server/server/render.js (45:686)
Function.getInitialProps
../pages/_document.tsx (66:33)
loadGetInitialProps
project/node_modules/next/dist/next-server/lib/utils.js (5:101)
```

**Comment by MathiasKandelborg** [comment]
Upgrading to `webpack 5.0.0-beta-23` with url-loader works great.

Webpack somehow handles output, specifically the html entities e.g `&lpar;` and shows each sign instead of `)` - this is even weirder because using html code e.g. `&#40;` (`&lpar;`equivalent) is still working alongside html entity `&apos;` (commonly known html entity makes me think this change is very manual)

**Comment by MathiasKandelborg** [comment]
It seems that css injection order is being messed up when using Material-UI.

Example:

I have a MenuItem component with custom styling using the `makeStyles` hook provided by Material-UI.

Without upgrade
- When the component is 'active' it has more styles applied to it. 
With the upgrade
- The custom `createStyles`hook style is applied _before_ the styles from the original component

The upgrade results in the custom style being completely ignored, with the added bonus of the component looking weird, because the injection order isn't right.

**Comment by Kinbaum** [comment]
> > @Kinbaum can you create a github repo so that I can add it to the integration tests we have?
> 
> Hi @timneutkens, here is the [reproduction repo](https://github.com/Kinbaum/broken-jsconfig)

I can confirm that the `jsconfig.json` issue is still present using **webpack@5.0.0-beta.23** and **next@9.5.2-canary.4**

**Comment by sokra** [comment]
> > > @Kinbaum can you create a github repo so that I can add it to the integration tests we have?
> > 
> > 
> > Hi @timneutkens, here is the [reproduction repo](https://github.com/Kinbaum/broken-jsconfig)
> 
> I can confirm that the `jsconfig.json` issue is still present using **webpack@5.0.0-beta.23** and **next@9.5.2-canary.4**

The fix is here: https://github.com/webpack/webpack/pull/11259

We will release it soon

**Comment by Kinbaum** [comment]
Thanks @sokra

**Comment by sokra** [comment]
Should be fixed as of 5.0.0-beta.24

**Comment by Kinbaum** [comment]
> Should be fixed as of 5.0.0-beta.24

Hi @sokra @timneutkens, I update the webpack and the next versions and the error is still present. I've updated my [reproduction repo](https://github.com/Kinbaum/broken-jsconfig) to reflect it. This is the error I see in the terminal:

```shell
Module not found: Your application tried to access components, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: components (via "components/Header")
Required by: /broken-jsconfig/packages/next-app/pages/

  3 |  * This import throws an error when using webpack 5 resolution in monorepo
  4 |  */
> 5 | import Header from 'components/Header';
  6 | import styles from '../styles/Home.module.css'
  7 | 
  8 | export default function Home() {
```

**Comment by glenngijsberts** [comment]
Not sure if helpful, but:

<img width="1427" alt="Screenshot 2020-08-06 at 15 42 19" src="https://user-images.githubusercontent.com/14276144/89539346-ecedec00-d7fb-11ea-9cee-9f9f60b2cd5b.png">

```
webpack: ^5.0.0-beta.22,
next: ^9.5.1,
next-i18next: ^4.5.0
```

Saw the plan to add polyfills, will `path` also be added or should I include it myself?

**Comment by timneutkens** [comment]
> Not sure if helpful, but:
> 
> <img alt="Screenshot 2020-08-06 at 15 42 19" width="1427" src="https://user-images.githubusercontent.com/14276144/89539346-ecedec00-d7fb-11ea-9cee-9f9f60b2cd5b.png">
> 
> ```
> webpack: ^5.0.0-beta.22,
> next: ^9.5.1,
> next-i18next: ^4.5.0
> ```
> 
> Saw the plan to add polyfills, will `path` also be added or should I include it myself?

This is expected as per the todo item:

> Provide polyfills that were removed in webpack 5 like process and Buffer. We'll likely show a warning when a built-in Node.js module is used where it was not intended, this would ensure backwards compat and significantly less breakage in existing applications.

**Comment by Timer** [comment]
Hello everyone! We're going to close this issue because webpack 5 now works out-of-the box with Next.js, with only some warnings.

We've opened two follow up issues:

- Polyfill common Node.js packages for webpack 5: #15948
- Fix webpack 5 deprecation warnings: #15947

If you find any bugs that aren't related to those two issues above, please open a **new issue** so we can track and prioritize it accordingly. That'll let us fix things faster than comments on this thread, thank you!

**Comment by jensmeindertsma** [comment]
Does this means it works out of the box on the latest canary version \*without\* Yarn resolutions? I'm just not quite understanding _out of the box_.

**Comment by timneutkens** [comment]
> Does this means it works out of the box on the latest canary version *without* Yarn resolutions? I'm just not quite understanding _out of the box_.

You still have to add resolutions, @timer was aiming at that it works automatically when you do add the resolutions.

**Comment by jeantil** [comment]
@timneutkens do you target a pinned resolution at v5.0.0-beta.22 or do you follow the latest beta ? (just to know if the version of webpack 5 matters or not)

**Comment by timneutkens** [comment]
You'll want to use the latest beta given there's tons of bugfixes in the latest release 👍

**Comment by agustif** [comment]
hey @timneutkens !  
Should I be able to use nextjs.config.js to enable webbpack experiments alongside .babelrc file in my project?

I can't get top-leveel-await to work with custom babel, any ideas?

**Comment by timneutkens** [comment]
I would recommend not using experimental webpack features, especially top level await has a very high avenue for slowdowns and performance problems in your application when used incorrectly.

**Comment by sebinsua** [comment]
Has anybody tried to use persistent caching yet?

**Comment by timneutkens** [comment]
@sebinsua persistent caching is configured in the latest canary. It still needs some improvements but initial results are great.

**Comment by jasonwilliams** [comment]
@timneutkens I hope this isn’t a silly question. How do we try out webpack 5 with this? Do we change resolutions in package.json? Or is there some flag to pass?

**Comment by timneutkens** [comment]
https://nextjs.org/blog/next-9-5#webpack-5-support-beta

Adding resolutions and potentially using the latest `next@canary` 👍

**Comment by jasonwilliams** [comment]
Have any of you seen this error before?
```
(node:765) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:765) [DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE] DeprecationWarning: MainTemplate.hooks.require is deprecated (use JavascriptModulesPlugin.getCompilationHooks().renderRequire instead)
(node:765) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
(node:765) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'map' is deprecated)
(node:765) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
error - NormalModuleFactory.beforeResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
event - build page: /_error
```

```json
{
  "resolutions": {
    "webpack": "5.0.0-beta.30",
    "webpack-cli": "4.0.0-beta.8",
    "next": "9.5.4-canary.19"
  },
}
```

**Comment by jonawww** [comment]
Are there any suggestions on how to enable webpack 5 in combination with yarn workspaces? Since the resolutions feature only works in the top level package.json, I would not be able to use any other webpack versions. (e.g CRA still relies on webpack 4). Am I missing something?

**Comment by Toolo** [comment]
+1 to @jonawww 

We have a monorepo with several apps, some of them are in the process of being migrated to webpack 5 (but they still depend on webpack 4) and then we have the NextJS app, so we can't rely on the top level `resolutions`. Is there any other way via configuration to switch to webpack 5? 

Thanks

**Comment by Toolo** [comment]
@sokra thanks for the hint! I will definitely try it out 😃

**Comment by jonawww** [comment]
@sokra This did the trick, thanks a lot! 🙌

**Comment by Xerkus** [comment]
Note that glob patterns are not allowed with yarn 2.
From yarn install:
> The override for '**/webpack' includes a glob pattern. Glob patterns have been removed since their behaviours don't match what you'd expect. Set the override to 'webpack' instead.

**Comment by aralroca** [comment]
In my case adding the resolutions I got this warning:

```
warning Resolution field "webpack@5.6.0" is incompatible with requested version "webpack@4.44.1"
```

![image](https://user-images.githubusercontent.com/13313058/99831121-eb53f400-2b5e-11eb-9905-69348d0fd546.png)


And checking `require('webpack').version` is 4.44.1 😅  Anyone knows what this could happen? Thanks!

**Comment by outerlook** [comment]
> And checking `require('webpack').version` is 4.44.1 😅 Anyone knows what this could happen? Thanks!
same as @aralroca while using yarn workspaces and
`"**/frontend/**/webpack": "5.6.0"`
at project-root > package.json > resolutions

**Comment by gajus** [comment]
If anyone is struggling with getting rid of webpack v4 from the dependency tree while using NPM v7,  I've documented a solution:

```js
#!/usr/bin/env node

/* eslint-disable unicorn/prevent-abbreviations */
/* eslint-disable import/unambiguous */
/* eslint-disable import/no-commonjs */
/* eslint-disable node/shebang */

const fs = require('fs').promises;
const path = require('path');

const main = async (resolutions) => {
  const packageLockFilePath = path.resolve(__dirname, '../package-lock.json');

  for (const [name, version] of Object.entries(resolutions)) {
    const packageLock = JSON.parse(await fs.readFile(packageLockFilePath));

    const packagePaths = Object.keys(packageLock.packages);

    const deletePaths = [];

    for (const packagePath of packagePaths) {
      if (packagePath.endsWith('/' + name)) {
        if (packageLock.packages[packagePath].version !== version) {
          deletePaths.push(packagePath);
        }
      }
    }

    for (const packagePath of deletePaths) {
      for (const deletePath of deletePaths) {
        if (packagePath === deletePath || packagePath.startsWith(deletePath + '/')) {
          // eslint-disable-next-line fp/no-delete
          delete packageLock.packages[packagePath];
        }
      }
    }

    await fs.writeFile(
      packageLockFilePath,
      JSON.stringify(packageLock, null, '  '),
    );
  }
};

main(require('../package.json').resolutions);

```

https://stackoverflow.com/a/65014694/368691

**Comment by shobhitsharma** [comment]
@Xerkus @outerlook @gajus Ran into same issue, got storybook running in monorepo which doesnt support webpack v5 yet, since yarn v2 `**/` glob patterns wont be allowed, is there any way to resolve it alternatively.

I saw yarn workspaces has `nohoist` ([see here](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/)), I've been trying it out but no luck.

**Comment by gajus** [comment]
> @Xerkus @outerlook @gajus Ran into same issue, got storybook running in monorepo which doesnt support webpack v5 yet, since yarn v2 `**/` glob patterns wont be allowed, is there any way to resolve it alternatively.
> 
> I saw yarn workspaces has `nohoist` ([see here](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/)), I've been trying it out but no luck.

What's wrong with the solution I proposed?

**Comment by ujwal-setlur** [comment]
I just tried out Webpack 5 on a next's 10.0.3 project. Build time seemed to actually increase:

with Webpack 4:
```bash
Executed in  151.61 secs   fish           external 
   usr time  230.24 secs  125.00 micros  230.24 secs 
   sys time   13.69 secs  625.00 micros   13.69 secs 
```

with Webpack 5:
```bash
Executed in  167.02 secs   fish           external 
   usr time  492.86 secs  161.00 micros  492.86 secs 
   sys time   69.28 secs  906.00 micros   69.28 secs 
```

I should expect faster build times, no?

I also saw a JavaScript OOM exception once:

```bash
info  - Using external babel configuration from /Users/ujwal/Work/byte/software/repos/micro/dashboard/.babelrc
info  - Creating an optimized production build .
<--- Last few GCs --->

[1332:0x110008000]   149669 ms: Mark-sweep 2014.8 (2101.4) -> 2014.7 (2060.6) MB, 993.7 / 0.0 ms  (average mu = 0.233, current mu = 0.000) last resort GC in old space requested
[1332:0x110008000]   150693 ms: Mark-sweep 2014.7 (2060.6) -> 2014.7 (2055.6) MB, 1023.7 / 0.0 ms  (average mu = 0.125, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1009dcbd9]
    1: StubFrame [pc: 0x100a1900f]
Security context: 0x2050d0a408d1 <JSObject>
    2: replace [0x2050d0a4cc71](this=0x205134b80119 <Very long string[67684575]>,0x2050f12cb1e9 <JSRegExp <String[67]: (\\)?"@__(F|R|D|M|S|U|I|B)-b8a6f9ee4b77bb1b764a3bb3b52e1c-(\d+)__@">>,0x2050b395ca99 <JSFunction (sfi = 0x2050ee27c689)>)
    3: serialize(aka serialize) [0x20502fa272b9] [/Users/ujwal/Work/byte/software/repos...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x1011d1cc5 node::Abort() (.cold.1) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
 2: 0x10009f919 node::Abort() [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
 3: 0x10009fa7f node::OnFatalError(char const*, char const*) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
 4: 0x1001e38b7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
 5: 0x1001e3857 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
 6: 0x10036b9e5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
 7: 0x100373a8c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
 8: 0x10033fe0d v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::RootIndex, int, v8::internal::Object, v8::internal::AllocationType) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
 9: 0x100710002 v8::internal::FixedArrayBuilder::EnsureCapacity(v8::internal::Isolate*, int) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
10: 0x1006bb42b v8::internal::Runtime_RegExpExecMultiple(int, unsigned long*, v8::internal::Isolate*) [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
11: 0x1009dcbd9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/var/folders/yg/8_rbwqbx51b5xn2_93_y43y00000gn/T/fnm_multishell_75535_1608360666435/bin/node]
sh: line 1:  1332 Abort trap: 6           next build
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! dashboard@0.0.1 build: `npm run clean && next build`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the dashboard@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ujwal/.npm/_logs/2020-12-21T18_59_02_529Z-debug.log

```

**Comment by hvqzao** [comment]
when
```
future: {
   webpack5: true
}
```
Next seems to partially ignore
```
  distDir: 'sth'
```
and creates some files in `.next/cache/webpack/` directory.

**Comment by timneutkens** [comment]
That's fixed already on next@canary.

**Comment by SalahAdDin** [comment]
@timneutkens could you include a correct way to use plugins like `@svgr`?
I'm using the following setup but it breaks:
```javascript
config.module.rules.push({
      test: /\.svg$/,
      type: "asset",
      issuer: /\.(js|ts)x?$/,
      use: "@svgr/webpack",
    });
```

**Comment by timakhalaya** [comment]
Trying to migrate to W5 from W4, 
when using webpack5:true  i get a bunch : 
`ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].module.rules[5] should be one of these:
   ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration[0].module.rules[5].loader should be a non-empty string.
      -> A loader request.
 - configuration[0].node has an unknown property 'fs'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
 - configuration[0].watchOptions.ignored[3] should be a non-empty string.
   -> A glob pattern for files that should be ignored from watching.
 - configuration[1].module.rules[5] should be one of these:
   ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration[1].module.rules[5].loader should be a non-empty string.
      -> A loader request.
 - configuration[1].watchOptions.ignored[3] should be a non-empty string.
   -> A glob pattern for files that should be ignored from watching.`

Any suggestions ?

**Comment by outerlook** [comment]
@timakhalaya are you using next-transpile-modules?

 I faced the same on the last canary. But I suspect it is because ntl detects webpack 5 with the old future.webpack5 flag to alter it's configs

**Comment by timakhalaya** [comment]
exactly 
i use next-transpile-module

**Comment by tsusini** [comment]
@timakhalaya I have the same problem, did you find a solution?

**Comment by Toolo** [comment]
I was able to solve errors like:
> configuration[1].module.rules[5].loader should be a non-empty string.

Using the following function in `next.config.js`
```javascript
/**
 * Ensures every module.rules entry is a valid array:
 * - Valid. `use: [{loader}]`
 * - Not valid: `use: {loader}`
 * {@see https://webpack.js.org/configuration/module/#ruleuse}
 * @param rules
 */
function normalizeLoaders(rules) {
  rules.forEach((rule) => {
    if (rule.use && rule.use.loader) {
      rule.use = [rule.use];
    }

    if (rule.oneOf) {
      normalizeLoaders(rule.oneOf);
    }
  });
}


return {
  ...
  webpack(webpackConfig, ...) {
    ...
    normalizeLoaders(webpackConfig.module.rules);
    return webpackConfig;
  }
}
```

**Comment by timakhalaya** [comment]
@tsusini 
i used a function to parse scope 
```
const path = require('path')
const fs = require('fs')
/**
 *  Function used for next-transpile-modules to be competable with our scoping of packages = > @swissredcross
 * @param {string} relativePath
 * @param {string} scopeArray
 */
const parseScope = ({ relativePath, scopeArray }) => {
    // resolve a path to our node modules folder where we will parse scoped packages
    const nodeModules = path.resolve(__dirname, relativePath, 'node_modules')
    // if more scope we can extend an array [scope1,scope2]
    const scopes = scopeArray
    // push all scoped packages here
    const packagesScoped = []

    fs.readdirSync(nodeModules)
        .filter((name) => scopes.includes(name))
        .forEach((scope) => {
            // for each scope do the parsing
            fs.readdirSync(path.resolve(nodeModules, scope))
                .filter((name) => !name.startsWith('.'))
                .forEach((folderName) => {
                    const {
                        ignoreTranspileModules,
                        name
                    } = require(path.resolve(
                        nodeModules,
                        scope,
                        folderName,
                        'package.json'
                    ))
                    if (!ignoreTranspileModules) {
                        packagesScoped.push(name)
                    }
                })
        })

    return packagesScoped
}
module.exports = {
    parseScope
}

```
then all scoped packages injected into next-transpile ....

```
const packagesScoped = parseScope({
    scopeArray: ['@yourscopes'],
    relativePath: '../../../'
})
const withTM = require('next-transpile-modules')([
    'react-children-utilities',
    ...packagesScoped
])
```

and in your webpack don't forget to - > 
 if (!isServer) {
                config.resolve = {
                    ...config.resolve
                }
            }

**Comment by timneutkens** [comment]
https://github.com/vercel/next.js/discussions/23498
