### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2 on Alpine

### ISSUE THREAD

**Issue by dulmandakh** [vercel/next.js#30713]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

16.x

### What browser are you using?

none

### What operating system are you using?

alpine

### How are you deploying your application?

next build

### Describe the Bug

next 12.0.2 app is failing to build on Alpine linux with following error. It was first appeared in 12.0.0, then fixed in 12.0.1. Now it's back in 12.0.2.

```sh
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by ....)
```

### Expected Behavior

**next build** should work

### To Reproduce

create next app using 12.0.2, then try to build on Alpine linux.

**Comment by hnq90** [comment]
I also got this issue.

**Comment by hnq90** [comment]
Downgrade Next.js to `12.0.1` solves the issue.

**Comment by timneutkens** [comment]
Hey! Could you share the full message including after `needed by`

**Comment by brantem** [comment]
```sh
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/node_modules/next/dist/build/swc/index.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by hnq90** [comment]
Mine is:
```
#32 102.2 Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
```

**Comment by kdy1** [comment]
Seems like it's trying to use node binding for glibc environment in musl linux.


I looked at https://unpkg.com/browse/next@12.0.2/dist/build/swc/index.js and I found that it will load glibc binding if it exists. To ensure that, I created a tiny script and inspected value of `triples` map.

```js
const obj = require('@napi-rs/triples').platformArchTriples

console.dir(obj['linux']['x64'])
```

This is relevant to your environment and the result was


```
[
  {
    platform: 'linux',
    arch: 'x64',
    abi: 'gnu',
    platformArchABI: 'linux-x64-gnu',
    raw: 'x86_64-unknown-linux-gnu'
  },
  {
    platform: 'linux',
    arch: 'x64',
    abi: 'gnux32',
    platformArchABI: 'linux-x64-gnux32',
    raw: 'x86_64-unknown-linux-gnux32'
  },
  {
    platform: 'linux',
    arch: 'x64',
    abi: 'musl',
    platformArchABI: 'linux-x64-musl',
    raw: 'x86_64-unknown-linux-musl'
  }
]
```

As `x86_64-unknown-linux-gnu` comes before `x86_64-unknown-linux-musl`, glibc bindings will be used.

---

You can workaround this by removing `node_modules/@next/swc-linux-x64-gnu` for now.

**Comment by degitgitagitya** [comment]
Same here, using Dockerfile from https://nextjs.org/docs/deployment#docker-image with `node:16-alpine`

**Comment by kdy1** [comment]
@degitgitagitya You can remove `node_modules/@next/swc-linux-x64-gnu` as a workaround.

**Comment by degitgitagitya** [comment]
> @degitgitagitya You can remove `node_modules/@next/swc-linux-x64-gnu` as a workaround.

Great! thanks

**Comment by mlnima** [comment]
I had this issue yesterday, then I changed back the 12.0.2 to 12.0.1, a few hours ago tried again 12.0.2, and it worked.

**Comment by knowerlittle** [comment]
> I had this issue yesterday, then I changed back the 12.0.2 to 12.0.1, a few hours ago tried again 12.0.2, and it worked.

Are you also using `node:16-alpine` ?

**Comment by knowerlittle** [comment]
> I had this issue yesterday, then I changed back the 12.0.2 to 12.0.1, a few hours ago tried again 12.0.2, and it worked.

@mlnima Are you also using `node:16-alpine` ?

**Comment by mtsewrs** [comment]
This is the error I'm getting using `node:16-alpine` on next `12.0.2`

```
Failed to compile.

../../node_modules/next/dist/client/next.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/app/services/app/src/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/app/node_modules/next/dist/client/next.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/app/node_modules/next/dist/client/next.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 745
    at Object.transform (/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:114:47
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:114:20)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:125:49
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:125:16)

../../node_modules/next/dist/client/router.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/app/services/app/src/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/app/node_modules/next/dist/client/router.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/app/node_modules/next/dist/client/router.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 749
    at Object.transform (/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:114:47
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:114:20)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:125:49
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:125:16)

../../node_modules/next/dist/pages/_error.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/app/services/app/src/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/app/node_modules/next/dist/pages/_error.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/app/node_modules/next/dist/pages/_error.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 747
    at Object.transform (/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:114:47
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:114:20)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:125:49
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:125:16)
```

**Comment by kdy1** [comment]
Can you check if the proper version of binding is installed?

Required information is `ls -al node_modules/@next` and package.json of the platform-specific binding libraries.
(Named like `-linux-gnu-x64`)

**Comment by mtsewrs** [comment]
@kdy1 Yes they seem to be there

```
drwxr-xr-x    9 root     root          4096 Nov  2 15:34 .
drwxr-xr-x    1 root     root         20480 Nov  2 15:34 ..
drwxr-xr-x    4 root     root          4096 Nov  2 15:34 env
drwxr-xr-x    3 root     root          4096 Nov  2 15:34 eslint-plugin-next
drwxr-xr-x    4 root     root          4096 Nov  2 15:34 polyfill-module
drwxr-xr-x    4 root     root          4096 Nov  2 15:34 react-dev-overlay
drwxr-xr-x    3 root     root          4096 Nov  2 15:34 react-refresh-utils
drwxr-xr-x    2 root     root          4096 Nov  2 15:34 swc-linux-x64-gnu
drwxr-xr-x    2 root     root          4096 Nov  2 15:34 swc-linux-x64-musl
```

**Comment by kdy1** [comment]
Can you share versions of them?

**Comment by mtsewrs** [comment]
Sure

```
{
  "name": "@next/swc-linux-x64-gnu",
  "version": "12.0.2",
  "os": [
    "linux"
  ],
  "cpu": [
    "x64"
  ],
  "main": "next-swc.linux-x64-gnu.node",
  "files": [
    "next-swc.linux-x64-gnu.node"
  ],
  "license": "MIT",
  "engines": {
    "node": ">= 10"
  }
}

{
  "name": "@next/swc-linux-x64-musl",
  "version": "12.0.1",
  "os": [
    "linux"
  ],
  "cpu": [
    "x64"
  ],
  "main": "next-swc.linux-x64-musl.node",
  "files": [
    "next-swc.linux-x64-musl.node"
  ],
  "license": "MIT",
  "engines": {
    "node": ">= 10"
  }
}
```

**Comment by mtsewrs** [comment]
Yes

**Comment by timneutkens** [comment]
Could you try out `npm install next@canary`?

**Comment by esistgut** [comment]
I'm getting this
```
./node_modules/next/dist/client/next.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/app/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/app/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/app/node_modules/next/dist/client/next.js","sourceMaps":true,"inlineSourcesContent":true,"sourceFileName":"/app/node_modules/next/dist/client/next.js"}
....
```
after switching to `12.0.3-canary.2` because of https://github.com/vercel/next.js/issues/30078

**Comment by mtsewrs** [comment]
@timneutkens getting this error now using canary

```
Failed to compile.

../../node_modules/next/dist/client/next.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/app/services/app/src/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/app/node_modules/next/dist/client/next.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/app/node_modules/next/dist/client/next.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 745
    at Object.transform (/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:47
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:20)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:49
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:16)

../../node_modules/next/dist/client/router.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/app/services/app/src/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/app/node_modules/next/dist/client/router.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/app/node_modules/next/dist/client/router.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 749
    at Object.transform (/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:47
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:20)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:49
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:16)

../../node_modules/next/dist/pages/_error.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/app/services/app/src/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/app/node_modules/next/dist/pages/_error.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/app/node_modules/next/dist/pages/_error.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 747
    at Object.transform (/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:47
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:20)
    at /app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:49
    at Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:16)
```

**Comment by kdy1** [comment]
@mtsewrs Seems like old version of `next-swc` is used. Can you reinstall after removing `node_modules`? Only removing `node_modules/@next` might be enough, but just to be sure.

**Comment by kdy1** [comment]
Oh, if you are using musl, I think it will not work currently. I checked https://unpkg.com/browse/next@12.0.2/package.json and it says 


```


"@next/swc-linux-x64-musl": "12.0.1",
--



```

**Comment by atuttle** [comment]
I'm getting this error building in a docker container from scratch in github actions on `node:16.13.0-alpine3.12`.

```
> next build

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Checking validity of types...
info  - Creating an optimized production build...
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/node_modules/next/dist/build/swc/index.js:29:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

Here's my dockerfile:

```Dockerfile
FROM node:16.13.0-alpine3.12 as gitbuilder
RUN apk add --no-cache git

FROM gitbuilder as Builder
WORKDIR /usr/src/app
ENV NODE_ENV=production
COPY ./.npmrc /usr/src/app
COPY ./package.json /usr/src/app
COPY ./package-lock.json /usr/src/app
RUN npm ci

FROM builder
HEALTHCHECK CMD node ./containerHealthCheck.js
EXPOSE 80
WORKDIR /usr/src/app
COPY . /usr/src/app
COPY --from=builder /usr/src/app /usr/src/app
RUN npm run build
CMD npm run start
```

**Comment by atuttle** [comment]
I tried switching to `12.0.3-canary.2` but if anything this seems to have made it worse:

```
> next build

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Checking validity of types...
info  - Creating an optimized production build...
Failed to compile.

./node_modules/next/dist/client/next.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/usr/src/app/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/usr/src/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/usr/src/app/node_modules/next/dist/client/next.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/usr/src/app/node_modules/next/dist/client/next.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 760
    at Object.transform (/usr/src/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:47
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:20)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:49
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:16)

./node_modules/next/dist/client/router.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/usr/src/app/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/usr/src/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/usr/src/app/node_modules/next/dist/client/router.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/usr/src/app/node_modules/next/dist/client/router.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 764
    at Object.transform (/usr/src/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:47
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:20)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:49
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:16)

./node_modules/next/dist/pages/_error.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"module":{"type":"commonjs"},"disableNextSsg":true,"isDevelopment":false,"pagesDir":"/usr/src/app/pages","isPageFile":false,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/usr/src/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/usr/src/app/node_modules/next/dist/pages/_error.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/usr/src/app/node_modules/next/dist/pages/_error.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 762
    at Object.transform (/usr/src/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:47
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:20)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:49
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:16)

./pages/_app.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"disableNextSsg":false,"isDevelopment":false,"pagesDir":"/usr/src/app/pages","isPageFile":true,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/usr/src/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/usr/src/app/pages/_app.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/usr/src/app/pages/_app.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 683
    at Object.transform (/usr/src/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:47
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:20)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:49
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:16)

./pages/index.js
Error: Failed to deserialize argument at `2` as next_swc::TransformOptions
JSON: {"disableNextSsg":false,"isDevelopment":false,"pagesDir":"/usr/src/app/pages","isPageFile":true,"jsc":{"parser":{"syntax":"ecmascript","dynamicImport":true,"jsx":true},"transform":{"react":{"runtime":"automatic","pragma":"React.createElement","pragmaFrag":"React.Fragment","throwIfNamespace":true,"development":false,"useBuiltins":true,"refresh":false},"optimizer":{"simplify":false,"globals":{"typeofs":{"window":"object"}}},"regenerator":{"importPath":"/usr/src/app/node_modules/next/node_modules/regenerator-runtime/runtime.js"}},"target":"es5"},"filename":"/usr/src/app/pages/index.js","sourceMaps":false,"inlineSourcesContent":false,"sourceFileName":"/usr/src/app/pages/index.js"}

Caused by:
    unknown field `regenerator`, expected one of `react`, `constModules`, `optimizer`, `legacyDecorator`, `decoratorMetadata`, `hidden` at line 1 column 685
    at Object.transform (/usr/src/app/node_modules/next/dist/build/swc/index.js:55:21)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:47
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.loaderTransform (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:113:20)
    at /usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:49
    at Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:74:26)
    at Object.swcLoader (/usr/src/app/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js:124:16)


> Build failed because of webpack errors
The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

**Comment by benkiefer** [comment]
Can this be re-opened?

**Comment by timneutkens** [comment]
This is now fixed on next@canary, please give it a try!

Verified based on the Dockerfile shared in this comment: https://github.com/vercel/next.js/issues/30713#issuecomment-959134683

**Comment by mtsewrs** [comment]
@timneutkens Confirmed! Working for me now, thanks!

**Comment by timneutkens** [comment]
Thanks for confirming @mtsewrs, we'll get it out on stable soon (today/tomorrow) 👍 Going to close this issue as we close issues when the fix has landed 👍

**Comment by jonahallibone** [comment]
@timneutkens I am still getting this error on `Next@12.0.3` deploying on Vercel, after a clean install on macOS

**Comment by noahgels** [comment]
> @degitgitagitya You can remove `node_modules/@next/swc-linux-x64-gnu` as a workaround.

How can I remove that one? In the dockerfile? Thanks for help

**Comment by kdy1** [comment]
@noahgels 

You can do `rm -r node_modules/@next/swc-linux-x64-gnu`.

**Comment by noahgels** [comment]
> @noahgels
> 
> You can do `rm -r node_modules/@next/swc-linux-x64-gnu`.

Thanks for quick answer, but I mean in my container before build. I'm actually facing the same problem as mentioned in this issue

**Comment by kdy1** [comment]
You can use the same command in docker.

**Comment by noahgels** [comment]
So I pasted `RUN rm -r node_modules/@next/swc-linux-x64-gnu` into my Dockerfile from https://nextjs.org/docs/deployment#docker-image after `RUN yarn install --frozen-lockfile`but I got the following error now: `HookWebpackError: error:0308010C:digital envelope routines::unsupported`.
Do I have to paste it in another place?

**Comment by TomMarius** [comment]
@noahgels I solved the "digital envelope" errors by downgrading to Node v16 (Docker image node:16-alpine).

**Comment by noahgels** [comment]
@TomMarius Thanks man, that was actually my final step, to everyone who reads this in future: I just built a new project and pasted my old js files in there and most things worked

**Comment by timneutkens** [comment]
> @noahgels I solved the "digital envelope" errors by downgrading to Node v16 (Docker image node:16-alpine). The cause is in Node v17 having newer OpenSSL libraries that are not supported yet.

This has been fixed on Next.js 12.0.3 so you can use Node.js 17 now.

**Comment by jeremyfx** [comment]
This issue is still occurring for me .. I tried all suggestions in convos above and some mixtures of them, etc

**Comment by pavanpodila** [comment]
This is still occurring in `v12.0.4` for node-14 docker image.

**Comment by mrgnou** [comment]
This issue needs to be reopened, vercel pipeline syill crashes when building next on 12.0.7.

**Comment by mdugue** [comment]
same problem on 12.0.7, started to appear today 🤔

**Comment by balazsorban44** [comment]
Hi everyone, if you have issues, please open a new bug report with a reproduction, so we can look into it! :pray:
