### ISSUE TITLE
`loadConfig` mutates the `imageConfigDefault` object

### ISSUE THREAD

**Issue by cdierkens** [vercel/next.js#32430]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Inside of `assignDefaults` function we merge and copy `defaultConfig` with the passed in `config`.

```ts
// https://github.com/vercel/next.js/blob/v12.0.7/packages/next/server/config.ts#L14
const result = { ...defaultConfig, ...config }
```

Then later mutates `result` by assigning sub-properties.

```ts
        // https://github.com/vercel/next.js/blob/v12.0.7/packages/next/server/config.ts#L205
        images.domains.push(new URL(config.assetPrefix).hostname)
      
      // https://github.com/vercel/next.js/blob/v12.0.7/packages/next/server/config.ts#L279
      images.loader = 'default'
      
      // https://github.com/vercel/next.js/blob/v12.0.7/packages/next/server/config.ts#L314
      images.path = `${result.basePath}${images.path}`
```

Because the merge and copy is shallow, when we mutate `result.images`, we are actually mutating the original object `imageConfigDefault` exported from https://github.com/vercel/next.js/blob/v12.0.7/packages/next/server/image-config.ts.

This could cause a number of issues, for example, in the case I'm running into, every time `loadConfig` is called the `basePath` property is pre-pended to `imageConfigDefault.path`.

```ts
console.log(imageConfigDefault.path)
// "/_next/image"

await loadConfig("phase-development-server", "./path/to/config/with/foo/base/path");
await loadConfig("phase-development-server", "./path/to/config/with/foo/base/path");
await loadConfig("phase-development-server", "./path/to/config/with/foo/base/path");

console.log(imageConfigDefault.path)
// "/foo/foo/foo/_next/image"
```

See the [codesandbox](https://codesandbox.io/s/immutable-thunder-g3bj8?file=/server.js) for an example. 

### Expected Behavior

Calling `loadConfig` with a config that has a `basePath` should not mutate `imageConfigDefault` or `defaultConfig`.

### To Reproduce

https://codesandbox.io/s/immutable-thunder-g3bj8?file=/server.js

**Comment by timneutkens** [comment]
So this is indeed unexpected, however `loadConfig` is only ever called once so this would indicate that you're using internals in some way, what are you doing exactly? 🤔

**Comment by cdierkens** [comment]
Nx is using it in their out of the box solution: https://github.com/nrwl/nx/blob/master/packages/next/src/executors/server/server.impl.ts#L71

**Comment by cdierkens** [comment]
Here is where [it's imported](https://github.com/nrwl/nx/blob/7ca6b292765dc8e04d851111e5a54f09ee4804cc/packages/next/src/utils/require-shim.ts#L13), then [called](https://github.com/nrwl/nx/blob/master/packages/next/src/utils/config.ts#L158).

**Comment by cdierkens** [comment]
@timneutkens The main issue here is that `image` and `imageConfigDefault ` are the same object memory reference on this [line](https://github.com/vercel/next.js/blob/v12.0.7/packages/next/server/config.ts#L313). That's certainly not the intended check because that will always be true. They are the same object.

**Comment by styfle** [comment]
Seems like this should be fixed in NX until Next.js provides a public loadConfig()

The code you linked to shows that NX is already using several workarounds to try to read private Next.js internals.

https://github.com/nrwl/nx/blob/7ca6b292765dc8e04d851111e5a54f09ee4804cc/packages/next/src/utils/require-shim.ts#L11-L13

I suggest creating a [Discussion RFC](https://github.com/vercel/next.js/discussions) for a public loadConfig() solution so that other tools read next.config.js

**Comment by cdierkens** [comment]
@styfle Exported publically or not, you still have an internal bug. Exported objects are being mutated and checking references against the same memory reference.

**Comment by styfle** [comment]
Can you share an example that doesn't explicitly call `require("next/dist/server/config")` but still fails?

**Comment by cdierkens** [comment]
```ts
// https://github.com/cdierkens/next.js/blob/canary/packages/next/server/config.ts#L313
    if (images.path === imageConfigDefault.path && result.basePath) {
      images.path = `${result.basePath}${images.path}`
    }
    
    console.log(images === imageConfigDefault)
    // true
```

Which makes that code equivalent to

```ts
    if (result.basePath) {
      images.path = `${result.basePath}${images.path}`
    }
```

Another example:

```ts
https://github.com/cdierkens/next.js/blob/canary/packages/next/server/config.ts#L295
    if (
      images.loader !== 'default' &&
      images.loader !== 'custom' &&
      images.path === imageConfigDefault.path
    ) {
      throw new Error(
        `Specified images.loader property (${images.loader}) also requires images.path property to be assigned to a URL prefix.\nSee more info here: https://nextjs.org/docs/api-reference/next/image#loader-configuration`
      )
    }
    
    console.log(images === imageConfigDefault)
   // true
```

Note that I'm checking `===` object to object, which means they are the same reference in memory. That also means that property checks like `images.path === imageConfigDefault.path` will always be true for every case.  Obviously these checks were intended to cover some cases, but I don't have enough context myself to know what they would be.

**Comment by cdierkens** [comment]
Closing this issue but I do want to address @styfle 's interaction. This is clearly code not working as intended whatever way you slice it. I provided a minimal approach to the solve w/ tests, a non breaking approach, and a breaking change. The  solution that was accepted was the breaking change. However, the PR still at out unmerged. This interaction has me pretty worn out and frankly burnt out with NextJS. 

As a consumer, I already have to vigorously test any updates to NextJS in my applications because I regularly see breaking changes in patches and minors. This interaction gives me even less confidence in the framework.

I hope you can clean up your approach to new contributors because I'm most likely going to withhold any issues I see going forward in this codebase as a result of how this was managed.

**Comment by styfle** [comment]
Hi @cdierkens 

It looks like the PR was approved the day after you submitted it https://github.com/vercel/next.js/pull/32477#pullrequestreview-831683704

I'm not sure why it was closed, it should have been automatically merged by kodiak bot once all the tests pass.

One of the ways in which we prioritize all the issues and PRs we get each day is by number of upvotes, so this one may have been overlooked. We have many contributions from outside contributors so I think this one must have slipped through the cracks, sorry about that!
