### ISSUE TITLE
Pages show 500 error on Vercel, on Netlify they work

### ISSUE THREAD

**Issue by PH4NTOMiki** [vercel/next.js#33459]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021
    Binaries:
      Node: 17.2.0
      npm: 8.1.4
      Yarn: N/A
      pnpm: 6.24.2
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

17.2.0

### What browser are you using?

Edge

### What operating system are you using?

Linux Manjaro

### How are you deploying your application?

Vercel

### Describe the Bug

The repo when deployed to Vercel does 500 errors, 
the same repo when deployed to the Netlify works without any issue.

But when I add `outputFileTracing: false` to `next.config.js` it works

And i think this is related to https://github.com/vercel/next.js/issues/30484 although in that issue is says it's been solved in the version 12.0.8 but I'm using it and it looks like it's not

### Expected Behavior

Working pages on Vercel, like they work on Netlify

### To Reproduce

https://github.com/PH4NTOMiki/nextjs-test-app-vercel-bug

**Comment by ijjk** [comment]
Hi, can you provide additional information on where you are seeing the 500 error? Visiting the latest deployment on the shared repo seems to be working correctly as seen in the below screenshots. Are you seeing any errors in your logs on the deployment when you get the 500 error? 

<details>

<summary>screenshots</summary>

<img width="1388" alt="Screen Shot 2022-01-19 at 10 24 40 AM" src="https://user-images.githubusercontent.com/22380829/150172590-23167ffd-beae-459d-a7ce-d5a94c2984c8.png">
<img width="1388" alt="Screen Shot 2022-01-19 at 10 24 35 AM" src="https://user-images.githubusercontent.com/22380829/150172597-55c385fc-240b-4189-9fdb-fb2fc305c5f1.png">
<img width="1388" alt="Screen Shot 2022-01-19 at 10 23 23 AM" src="https://user-images.githubusercontent.com/22380829/150172600-3531165d-ffe8-4fa2-b431-2fdad2591833.png">

</details>

**Comment by PH4NTOMiki** [comment]
@balazsorban44 Hi there, yes, the deployment is using the main branch that has `outputFileTracing: false` added to the config, and that's why it works, 
I separated the repo now:
https://github.com/PH4NTOMiki/nextjs-test-app-vercel-bug

and created new deployment on the Vercel and look at this:
https://nextjs-test-app-vercel-bug.vercel.app/

it doesn't work

**Comment by balazsorban44** [comment]
Your reproduction throws the following error in dev mode:

![image](https://user-images.githubusercontent.com/18369201/150182837-18649163-0873-4121-8bf6-94a4ff71bdbb.png)


Could you please create a reliable reproduction so we can investigate this further? :pray:

**Comment by PH4NTOMiki** [comment]
I fixed that now, so sorry about that. I tested it on local and it works now, and Vercel link doesn't work, and this is the same deployment on the Netlify https://awesome-goldstine-3aa7ed.netlify.app/ and it works

**Comment by balazsorban44** [comment]
Still getting errors locally:

![image](https://user-images.githubusercontent.com/18369201/150184385-0ed0f831-4b8a-4f35-8b54-5f9fbff7af6c.png)

This might be due to my missing `MONGODB_URI` env variable. I recommend checking your deployment that you haven't missed that in the Vercel dashboard.

Otherwise, your reproduction still needs some tweaking. Unless I can verify it working correctly locally, I cannot decide if the error is actually with Vercel.

**Comment by PH4NTOMiki** [comment]
![Screenshot_20220119_184205](https://user-images.githubusercontent.com/35368241/150185153-af3d01e7-ea9b-4e1f-80fb-c56559106f09.png)
It's added, and I just sent it(that env variable) to you over your email info@balazsorban.com

**Comment by balazsorban44** [comment]
I found the issue. You tried to import types in .js files in multiple places.

Here is an example: https://github.com/PH4NTOMiki/nextjs-test-app-vercel-bug/blob/bfd44e7cc4e28dadcd9ea80c88cb38c9acb976f2/pages/index.js#L7

You have two options here:

1. convert the files to TypeScript (preferably still the [`type` import modifier](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) to indicate to yourself that you are only importing a type). Next.js [supports TypeScript](https://nextjs.org/docs/basic-features/typescript)
2. Use the JSDoc equivalent import. For the given example above, you could do `* @param {import("next").NextPageContext} ctx` instead. (You have done so in `lib/_fetch.js` which is the correct way.)

**Comment by PH4NTOMiki** [comment]
![image](https://user-images.githubusercontent.com/35368241/150188960-a0c946da-7bb1-47e3-aa4f-93f56e49880b.png)
I get that in the Vercel console, so you are sure that that is it?
That's great then, but why does it work on local(npm run start) and Netlify?

**Comment by PH4NTOMiki** [comment]
@balazsorban44 I try to fix it by doing the replacements you told me, and it works now, actually I think I've figured the reason it works for me locally and on Netlify, it's because I use `17.2.0` and Netlify uses `16.x` versions of Node, and Vercel uses `14.x` and that's probably the reason why Vercel is unable to compile it.

Anyway thanks for helping me out

**Comment by balazsorban44** [comment]
I don't think it's Node.js related. Netlify probably does its own module tracing. 

We ignore tracing `next` itself since you shouldn't import it in the first place:

https://github.com/vercel/next.js/blob/1d4f364515d34586b864923dafb7888bf1ff79d2/packages/next/build/webpack/plugins/next-trace-entrypoints-plugin.ts#L20-L23
