### ISSUE TITLE
`swcMinify: true` does not produce an usable build with v12.1.5

### ISSUE THREAD

**Issue by ribeaud** [vercel/next.js#36127]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```bash
 $ npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

`next start` after a `next build`

### Describe the Bug

Locally (running the application locally, in my IDE), everything looks good. Our tests are green as well. Only the PROD artefact is somehow rubbish.

When accessing the homepage, this is what we get in the console:

<img width="578" alt="console" src="https://user-images.githubusercontent.com/13186156/163226690-b735a408-b32c-4cf9-9573-bfc0f906c0e6.png">

When clicking on one of the links displayed, this is what I get:

<img width="468" alt="error_decoder" src="https://user-images.githubusercontent.com/13186156/163226792-c8e14255-e240-4ea5-b9d7-6822a989bf19.png">

### Expected Behavior

No error messages in the console, application is running properly and _swcMinify_ is set to `true`, like it used to be for _v12.1.0_ (application was NOT working with the releases from _v12.1.1_ to _v12.1.4_).

The expected behavior could be achieved if I set _swcMinify_ to `false` in the configuration [file](https://gitlab.com/biomedit/portal/-/blob/dev/frontend/next.config.js).

### To Reproduce

Kindly follow instructions given in the [README.md](https://gitlab.com/biomedit/portal#production-like-local-deployment), _Production-like local deployment_.

More info on the problem could be found [here](https://gitlab.com/biomedit/portal/-/issues/581) and [there](https://gitlab.com/biomedit/portal/-/issues/577).

Please, let me know if you have questions, or whether I should deeply investigate in a given direction, or if I can do anything here to help.

Thanks in advance for your time and investigation.

**Comment by bonesoul** [comment]
same here.

**Comment by powerfulyang** [comment]
same here 
```javascript
/**
 * Create a code check from a regex.
 *
 * @param {RegExp} regex
 * @returns {(code: Code) => code is number}
 */
function regexCheck(regex) {
  return check

  /**
   * Check whether a code matches the bound regex.
   *
   * @param {Code} code Character code
   * @returns {code is number} Whether the character code matches the bound regex
   */
  function check(code) {
    return code !== null && regex.test(String.fromCharCode(code))
  }
}
```
Code above will not work fine.

**Comment by kdy1** [comment]
I fixed the issue reported by @powerfulyang (https://github.com/swc-project/swc/pull/4338), but not sure if this issue is related to this issue.

**Comment by kdy1** [comment]
I'm not sure how can I test the fix

Seems like you are invoking next.js in docker, right? If so, `yarn link` will not help.
Is there a way to run the webapp without docker?

**Comment by smitpatel1010** [comment]
@kdy1 Can you add this change https://github.com/swc-project/swc/pull/4250 in nextjs to fix infinite loops?

**Comment by kdy1** [comment]
@smitpatel1010 Of course, I included it in https://github.com/vercel/next.js/pull/36187

**Comment by smitpatel1010** [comment]
Oh great. Thanks 🙂

**Comment by balazsorban44** [comment]
@ribeaud looking at your reproduction, it seems a bit complicated. Could you please try to create a more minimal one that's focusing on the issue?

I recommend removing any pages/components/technologies that do not contribute to the bug you are experiencing (eg. I'm sure Docker and most of the stuff in the repo are not contributing to the issue here). This will help us verify and fix any bugs much faster. :+1:

**Comment by ribeaud** [comment]
@balazsorban44 makes perfectly sense. However I am not sure being able to do it before coming week-end. What I definitely can do is to test any **canary** release you want.

**Comment by timneutkens** [comment]
@ribeaud no rush on providing the code but we can't investigate it further for your particular case without it. Can you try the latest canary version? A bunch of changes to the minifier were applied.

**Comment by arnovanstaden** [comment]
`swcMinify: true` is causing the exact same problem for me. After removing it from `next.config` the build is running smoothly

**Comment by Luukuton** [comment]
Same issue here with `swcMinify: true`. Was working fine on Next.js `12.1.4` and broke on `12.1.5`. Also tried `v12.1.6-canary.4` which didn't fix it either.

The issue can be reproduced by running the few simple commands listed on https://github.com/Luukuton/shingetsu-blog/tree/main/frontend with the following as `.env.local`:
```
NEXT_PUBLIC_STRAPI_API_URL=https://strapi.luukuton.fi
NEXTAUTH_URL=http://localhost:3000
SECRET=1234
JWT_SIGNING_PRIVATE_KEY={"kty":"oct","kid":"1234","alg":"HS256","k":"1234"}
```


Remember the change the `swcMinify` to `true` in `next.config.mjs` as well.


Errors:
`Application error: a client-side exception has occurred (see the browser console for more information).`

```
ReferenceError: check is not defined
    at Object.7011 (75-8b0d76e33d9d9da7.js:1:226386)
    at a (webpack-dab0b2f9bb1be3f3.js:1:157)
    at Module.334 (index-94cc969871e15009.js:1:289)
    at a (webpack-dab0b2f9bb1be3f3.js:1:157)
    at index-94cc969871e15009.js:1:151
    at main-fd09345e2a348c4f.js:1:25750
```

**Comment by kdy1** [comment]
@Luukuton Seems like it's fixed by https://github.com/vercel/next.js/commit/9456fc6b3b31a3291c69600866e1be3a9eac8835

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/29931815/164485282-9c17a812-0c25-4f39-bf4e-40e60a25a94d.png">

**Comment by Luukuton** [comment]
> @Luukuton Seems like it's fixed by https://github.com/vercel/next.js/commit/9456fc6b3b31a3291c69600866e1be3a9eac8835

Nice! Looks good.

> !!! Set productionBrowserSourceMaps true in next.config.js can get full error trace.

Thanks 😄. I'll remember this in the future if I have to debug something.

**Comment by ribeaud** [comment]
The latest **canary** (_12.1.6-canary.5_) does a much better job. Still NOT working on my end, but now getting following error in the console:

<img width="1053" alt="console" src="https://user-images.githubusercontent.com/13186156/164507932-586dd08e-fd89-4185-b15f-6c1b9d2393ab.png">

**Comment by seanparmelee** [comment]
We have been running into this issue in one of our apps as well (even on the latest canary). In our case, the following error is thrown:

```
TypeError: j is not a function
    at r.exports (util.js:1:46666)
    at Object.112 (util.js:1:46666)
    at __nccwpck_require__ (util.js:1:46666)
    at Object.749 (util.js:1:46666)
    at __nccwpck_require__ (util.js:1:46666)
    at Object.715 (util.js:1:46666)
    at __nccwpck_require__ (util.js:1:46666)
    at Object.3 (util.js:1:46666)
    at __nccwpck_require__ (util.js:1:46666)
    at Object.650 (util.js:1:46666)
```

After some process of elimination, the culprit turned out to be some code that was using

```js
import { isString } from 'util';
```

And removing that code makes the error goes away. 

I pushed up a simple reproduction here in hopes it helps get to the root cause of the issue (this form of it anyway): https://github.com/seanparmelee/nextjs-36127-reproduction

* Pull it down
* Run `yarn build && yarn start`
* Navigate to http://localhost:3000

**Comment by kdy1** [comment]
@seanparmelee 
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/29931815/164603968-3567b9dc-4660-4cd2-bcdf-9a0031a3d59a.png">

It will be fixed by https://github.com/vercel/next.js/pull/36351

(I used my own script to replace `next-swc` binary)

**Comment by VeronikaSergiyenko** [comment]
I tried release https://github.com/vercel/next.js/releases/tag/v12.1.6-canary.13 that should contain fix from https://github.com/vercel/next.js/pull/36351
but still doesn't work 
<img width="1122" alt="зображення" src="https://user-images.githubusercontent.com/63006489/165768405-95019a89-d704-434e-8924-b6a15b8fd7f7.png">
<img width="1122" alt="зображення" src="https://user-images.githubusercontent.com/63006489/165768469-13e4c0ea-8cf2-4692-987f-da56b9184b9b.png">

**Comment by kdy1** [comment]
@VeronikaSergiyenko I think it will be fixed by https://github.com/vercel/next.js/pull/36535

React now uses google closure compiler as their minifier, and it triggered a bug of swc minifier.
So I disabled the problematic pass for now and I'm working on a full fix for alias analyzer

**Comment by Rafcin** [comment]
I just want to add to this, that I ran into a similar issue whereupon deployment I receive invariant 138 saying "Maximum depth exceeded", and disabling swcMinify solves the issue for now. https://reactjs.org/docs/error-decoder.html/?invariant=185

**Comment by kdy1** [comment]
@Rafcin Did you try the latest canary? If so, can you provide a repro?

**Comment by Rafcin** [comment]
@kdy1 I just tested a deployment with [12.1.7-canary.16](https://www.npmjs.com/package/next/v/12.1.7-canary.16) and it threw the same issue. The repo is private, but if you need anything specific let me know!

**Comment by terryli0095** [comment]
Is the solution just to downgrade to 12.10.0? Our build was working with 12.1.6.  Migrated to Material UI 5 . And part of the codebase that's unrelated to the MUI started breaking after minify

**Comment by kdy1** [comment]
@terryli0095 You can provide more information, like repro case, so I can fix it

**Comment by kdy1** [comment]
```js

  let e = -1
  for (let b of a)
    e + b.length + 1;
  return e

```

Is this typo?

**Comment by danilowoz** [comment]
Sorry, yes. The right output is:
<img width="263" alt="Screenshot 2022-06-20 at 11 34 32" src="https://user-images.githubusercontent.com/4838076/174611214-61cbb208-a979-448d-b3a8-f100aae116f3.png">

**Comment by kdy1** [comment]
@danilowoz Can you try canary?

**Comment by OskarD** [comment]
Any progress on this? I want to disable it to debug a bug that doesn't happen in local development mode for some reason

**Comment by kdy1** [comment]
@OskarD All debuggable issues are fixed. Others did not provide any information.

**Comment by OskarD** [comment]
> @OskarD All debuggable issues are fixed. Others did not provide any information.

I'm probably doing something wrong, but with 12.2.3 and this config:
```
    swcMinify: false,
    compress: false
```

I'm getting this kind of error:
```
Error: No credentials
    at e.<anonymous> (70-0c006eaa97bdd322.js:1:193655)
    at 70-0c006eaa97bdd322.js:1:185254
    at Object.next (70-0c006eaa97bdd322.js:1:185359)
    at a (70-0c006eaa97bdd322.js:1:184095)
```

Is there something I'm missing here?

**Comment by kdy1** [comment]
Is it really related to swc minifier?
```
    swcMinify: false,

```

Is this typo?

**Comment by OskarD** [comment]
> Is it really related to swc minifier?
> 
> ```
>     swcMinify: false,
> ```
> 
> Is this typo?

Sorry, I thought this thread was for disabling minifying. I'm using Webpack so my problem is not related, my apologies

**Comment by ribeaud** [comment]
Hi. Just this short notice to let you know that, after many unsuccessful releases, I was able to reactivate `swcMinify: true` on our end with _v12.3.1_.

I do not know what exactly solves it though: whether we changed something relevant on our side, or whether it is due to some changes on your side. Anyway, let's appreciate this momentum and let me tell you thank you!

**Comment by kdy1** [comment]
Nice! I think we can close this issue for now.
Thank for the notice!
