### ISSUE TITLE
12.1.6 CSS generation regression

### ISSUE THREAD

**Issue by suprMax** [vercel/next.js#36675]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.5.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.1
      react: 18.1.0
      react-dom: 18.1.0
```

### Describe the Bug

I'm seeing a CSS generation regression in my setup starting from `12.1.6` and persisting with current `12.1.7-canary.1`.

I'm using React 18 with emotion based UI kit. I see a huge FOUC that gets resolved a moment after load, see dev lighthouse screenshots:

`12.1.5`
<img width="718" alt="Screen Shot 2022-05-04 at 2 38 08 PM" src="https://user-images.githubusercontent.com/789031/166683512-a2b11f7b-4f94-4c87-a4eb-5aa6f41ebc1c.png">

`12.1.6+`
<img width="712" alt="Screen Shot 2022-05-04 at 2 37 20 PM" src="https://user-images.githubusercontent.com/789031/166683578-d89a18fa-6a05-4a85-be53-d1c5b8a07770.png">

Any idea if this is an issue with React 18 or how to mitigate? I locked my packages to 12.1.5 for now.

### Expected Behavior

No FOUC like in 12.1.5

### To Reproduce

1. use React 18
2. use css-in-js library like emotion or ui kit like http://mantine.dev
3. use next version 12.1.6 or later
4. Run lighthouse test or watch content jump around during load

**Comment by nghiepit** [comment]
I am also facing the same issue in MUI v5.

https://user-images.githubusercontent.com/4768095/166811627-9d7571bc-5baf-4716-917e-02f36f3d1c8e.mov

FOUC in Next v12.1.6
https://codesandbox.io/s/beautiful-cray-3bggr7

Without FOUC in Next v12.1.5
https://codesandbox.io/s/sleepy-mclean-l64p1s?file=/pages/_app.tsx

**Comment by gurkerl83** [comment]
@nghiepit Can you share the actual link to the sandbox which has the issue? From your recording, I see only the link of the app running - https://rnwhn.sse.codesandbox.io which shows the distortion. 

The other sandboxes you mentioned seem to work.

**Comment by nghiepit** [comment]
@gurkerl83 sorry, I just updated codesanbox.

**Comment by gurkerl83** [comment]
The problem is real, somehow it works in 12.1.5 but breaks in 12.1.6.

**Comment by ANTARES-KOR** [comment]
One suspicious difference between 12.1.5 and 12.1.6 is,

on 12.1.5,
you can see the <style/> tags are inserted inside <body/> tag when disabled javascript on browser ( I think this is some sort of bug, too)
![스크린샷 2022-05-06 오후 2 00 05](https://user-images.githubusercontent.com/75557859/167070521-ad15d66b-f4c8-4f9d-95c0-3cfcaa1a4120.png)

and on 12.1.6
the <style/> tags are not inserted inside <body/> tag.
![스크린샷 2022-05-06 오후 2 03 03](https://user-images.githubusercontent.com/75557859/167070579-d5bceff6-4112-42c1-9c16-1714f1253b4f.png)

**Comment by MathiasKandelborg** [comment]
There's definitely a regression in how styles are applied. I've been trying to go through the commits, but haven't found any contenders. Not that I'm intimate with the codebase or have spent more than 5 minutes going through commit names.

I'm going to look more into this, but I'm pretty certain it has to do with custom document, and how emotion injects styles/how styles are injected.

**Comment by MathiasKandelborg** [comment]
So, after trying to read changes in the Next code, I thought the new rendering seemed like it would populate the application with logic from custom document on the first render.
So I took the most abstract conclusion:
Now, that we are trying to render everything, without any subsequent renderings; maybe the styles are being applied twice?
> The FOUC seems (from my code reviewing) to be caused by logic in custom app - and as such
> **I tried removing the cache component in _app, and the FOUC stopped completely**.

I'm still testing, and have to get home to play around with this some more.
I can, though, confirm that using the latest stable versions of MUI, React, and Next works with MUI.Emotion styling, _without_ any FOUC, in my app; I simply removed the cache component in my custom app

**Comment by huozhi** [comment]
emotion css currently requires to extract styles from the rendered html, but in react 18, next.js currently opt-in streaming rendering which couldn't get the full html at the time of gIP is called.

I [patched some changes to the _document page of the reproduction](https://github.com/beeebox/emotion-gip-styles-repro/commit/54b0ab48929ac097ffb041e89fd5baf22fdbf564#diff-b929c3253a9e359b8f6fe97cf17d130980cdd27eece598c0db54dcdbe1f69a83). Could you try it to see if it can be considered as a workaround for your case? The shortcut is the app will be rendered twice in the patch.

**Comment by huozhi** [comment]
It should be fixed in `next@12.1.7-canary.4`, I tested it works for the reproduction. could y'all try it to see if resolves your issue?

**Comment by srk-sharingan** [comment]
> It should be fixed in `next@12.1.7-canary.4`, I tested it works for the reproduction. could y'all try it to see if resolves your issue?

I still have this distortion issue even after upgrading it to `next@12.1.7-canary.5`.

**Comment by huozhi** [comment]
@srk-sharingan Could you file a new issue with your reproduction? Thanks

**Comment by zhulduz** [comment]
Version 12.1.7-canary.4 works properly for me
