### ISSUE TITLE
When fetching a Request object in middleware, the method is ignored

### ISSUE THREAD

**Issue by ambrauer** [vercel/next.js#37123]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.11
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When fetching a Request object in middleware, the method is ignored:

```ts
const request = new Request('http://example.com', { method: 'POST', body: 'hello'})
const response = await fetch(request)

expect(response.req.method).toEqual('POST') // <-- return 'GET'
```

This is related to #36522 (case 2 here, which I believe was lost in the shuffle).

### Expected Behavior

Specified 'method' should be used for the request

### To Reproduce

A simple repro we have in a middleware.ts:

```ts
import { NextResponse } from 'next/server';

export default async function () {
  const ok = await fetch('https://httpbin.org/post', {
    method: 'POST',
    body: 'test',
  });
  console.log(ok); // <-- 200 OK

  const fails = await fetch(
    new Request('https://httpbin.org/post', {
      method: 'POST',
      body: 'test',
    })
  );
  console.log(fails); // <-- 405 METHOD NOT ALLOWED (GET is sent)

  return NextResponse.next();
}
```

**Comment by ijjk** [comment]
Hi, this should be fixed by https://github.com/vercel/next.js/pull/36539 which is available in `v12.1.7-canary.19` of Next.js

**Comment by ambrauer** [comment]
Hi @ijjk, thanks for the update although I'm still seeing the issue with `12.1.7-canary.19` (and I also tried `12.1.7-canary.23`, latest canary I had trouble quickly setting up same repro). The mentioned fix only applies to request cloning. Seems like this issue should be re-opened?
