### ISSUE TITLE
Rewrites not working on client-side navigation in 12.2+

### ISSUE THREAD

**Issue by luukdv** [vercel/next.js#40549]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Binaries:
  Node: 14.20.0
  npm: 6.14.17
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.0.1-canary.0
  react: 18.2.0
  react-dom: 18.2.0
```

### Describe the Bug

When using version `12.2` or higher, rewrites don't work on client-side navigation anymore. It does work when visiting a url directly / refreshing the page. Initially reported in https://github.com/vercel/next.js/issues/38338.

### Expected Behavior

Client-side navigations work the same as server-side page loads.

### Link to reproduction

https://github.com/luukdv/next-bug

### To Reproduce

- Clone https://github.com/luukdv/next-bug
- Run `npm i && npm start`
- Open http://localhost:3000
- Click "Visit this link"
- Click "Refresh the page"

**Comment by vibhor-web-headout** [comment]
having same issue here

**Comment by chrilis** [comment]
@luukdv Having the same issue (maybe related to #39638 and #39837) I found that replacing the last trailing slash of the `source` with `{/}?` does _fix_ the rewrites on client-side.

```diff
{
-  source: "/pages/test/",
+  source: "/pages/test{/}?",
   destination: "https://example.com/",
}
```

I do not know if this is a bug or the [documentation](https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewriting-to-an-external-url) should be updated:
> If you're using trailingSlash: true, you also need to insert a trailing slash in the source parameter. If the destination server is also expecting a trailing slash it should be included in the destination parameter as well.

**Comment by samithaf** [comment]
> @luukdv Having the same issue (maybe related to #39638 and #39837) I found that replacing the trailing slash of the `source` with `{/}?` does _fix_ the rewrites on client-side navigation.
> 
> ```diff
> {
> -  source: "/pages/test/",
> +  source: "/pages/test{/}?",
>    destination: "https://example.com/",
> }
> ```
> 
> I do not know if this is a bug or the [documentation](https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewriting-to-an-external-url) should be updated:
> 
> > If you're using trailingSlash: true, you also need to insert a trailing slash in the source parameter. If the destination server is also expecting a trailing slash it should be included in the destination parameter as well.

Yep it's working with your approach! If it is not a bug might need to update the documentation.

**Comment by TommySorensen** [comment]
I'm using rewrites with trailingSlash: false (default) and rewrites still dont work. Going to `http://localhost:300/api/proxy/some/page` never hits the rewrite rule. If i change the next.config.mjs file to next.config.js everything just works.
```
{
  source: '/api/proxy/:path*',
  destination: `${apiUrl}/api/:path*`,
}
```

**Comment by luukdv** [comment]
> @luukdv Having the same issue (maybe related to #39638 and #39837) I found that replacing the trailing slash of the `source` with `{/}?` does _fix_ the rewrites on client-side navigation. I do not know if this is a bug or the [documentation](https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewriting-to-an-external-url) should be updated

Nice workaround! Does not seem to work for every page though, for example on a home page (`/`) this error is returned: `source does not start with / for route…`.

Based on this and the fact that it's a sudden regression since `12.2` with no alternative solution (and the docs clearly state that the source should include the trailing slash as well), it still seems very much like a bug.

**Comment by chrilis** [comment]
For the home page we used `/{/}?`, which worked for us @luukdv. But not sure if that is actually a good idea.

**Comment by luukdv** [comment]
Updated the reproduction repository to use Next 13.

**Comment by will0684** [comment]
> I have the same issue in next 13.3.1.
> 
> After upgrading from next 12.2.5 to 13.3.1 this issue started to occur - but only when running next dev.
> 
> When running next build and next start everything works fine. In next dev **all rewriting rules from next.config.js are ignored when the page is called directly**. Does anyone have an idea what could be the reason for that?
> 
> I am not using trailingSlash options so I can not try the workaround from above.


We are having the same issue with Next 13.3.1. With `yarn dev`, rewrites are simply not being respected but with `yarn build` everything works as expected. We are using Next/Link for navigation. We use rewrites to manage internationalization of our paths.

Our repo is [here](https://github.com/DTS-STN/Service-Canada-Labs).

To reproduce it:

Pull the repo and create a .env with the following values:

ADOBE_ANALYTICS_URL=
AEM_GRAPHQL_ENDPOINT=https://www.canada.ca/content/_cq_graphql/decd-endc/endpoint.json

Upgrade Next to 13.3.1, run `yarn dev`, go to localhost:3000/fr/accueil (our rewrite destination is /fr/home) and you will see that the page cannot be found, but that /fr/home _does_ work.

Before updating Next, our rewrite config would work as expected.

**Comment by ijjk** [comment]
@will0684 could you create a fresh issue with your reproduction it looks unrelated to this issue and this one should be resolved. Yours seems specific to i18n and dev handling of rewrites. 

I'm gonna close this one out as the original issue from Next.js 12.2 should no longer be relevant and the issue with trailing slashes with rewrites should be handled.

**Comment by luukdv** [comment]
@ijjk As noted [here](https://github.com/vercel/next.js/issues/40549#issuecomment-1293416213), this issue still exists using Next.js 13.

Can this please be reopened?

**Comment by luukdv** [comment]
The reproduction steps outlined [here](https://github.com/vercel/next.js/issues/40549#issue-1372869488) still apply with Next.js 13.4 for example.
