### ISSUE TITLE
[appDir] Next.js can't pickup css imports from client components

### ISSUE THREAD

**Issue by SukkaW** [vercel/next.js#41791]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Wed Oct 26 2022 00:58:23 GMT+0800 (China Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 12.3.2-canary.43
      eslint-config-next: N/A
      react: 18.3.0-next-fecc288b7-20221025
      react-dom: 18.3.0-next-fecc288b7-20221025

### Describe the Bug

When using `experimental.appDir`, Next.js can not pick the CSS import from React Client Components located under the `app` dir. Both CSS Modules and Global Stylesheets can't work.

cc @shuding

### Expected Behavior

The imported CSS should be collected, processed, and then bundled by Next.js.

### Link to reproduction

https://stackblitz.com/edit/nextjs-4ur55n

### To Reproduce

Open the reproduction from stackblitz attached above:

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/40715044/197837739-a008b9a5-e7fc-4292-be0b-c2d0505ca625.png">

**Comment by jmikrut** [comment]
Having the same issue with Payload CMS' new site. If we remove the `use client` directive, the CSS is loaded properly.

**Comment by alexis78i** [comment]
I got the answer in the nextjs 13 documentation page that styles need to be imported directly into Layout for this to work. But all the charm of using CSS modules and many imports is lost.

**Comment by jmikrut** [comment]
@alexis78i can you link me to where you saw that?

I see here that they say CSS modules can be imported into any file within `/app`:

https://beta.nextjs.org/docs/styling/css-modules#usage

**Comment by jmikrut** [comment]
@alexis78i I don't see a single mention of CSS or styles on that page but I am likely blind and / or stupid

**Comment by alexis78i** [comment]
@jmikrut I noticed that the thread was resolved 
<img width="398" alt="thread" src="https://user-images.githubusercontent.com/15069001/198106971-3f4cd0a2-daad-4b5f-8de4-48bec3581684.png">

**Comment by jack-szeto** [comment]
@alexis78i that's weird. I'm already importing the `.module.css` in the `layout.tsx`, still doesn't work. I can see the class name imported successfully tho.

**Comment by kochie** [comment]
It seems to be that the css is not being bundled and sent to the client, possibly some sort of mismatch between server and client components?

**Comment by OlegMikhailov23** [comment]
Have the same problem. Next does't see my imported css module.

**Comment by arzafran** [comment]
Still happening when using:

```
Binaries:
  Node: 17.0.1
  npm: 8.1.0
  pnpm: 7.14.0
Relevant packages:
  next: 13.0.1-canary.0
  eslint-config-next 13.0.1-canary.0
  react: 18.2.0
  react-dom: 18.2.0
```

**Comment by dmaynard24** [comment]
I'm running into the same problem. CSS Modules styles aren't working. Interestingly enough, the generated CSS classnames are still being appended to elements.

**Comment by tonypeng** [comment]
+1, having this issue as well

**Comment by Nfinished** [comment]
I'm also experiencing exactly what @tonypeng has described

**Comment by OlegMikhailov23** [comment]
In my case css modules don't work if we have a client component, but,if you switch to server component, it works fine. Is it a right behavior?

**Comment by mjmcgrath2010** [comment]
Tagging on (might be separate issue, can file)...

When using styled components, it appeared that their CSS was getting applied (somewhat inconsistently, oftentimes it took a hard page load to see changes). However, when adding a loading.tsx file, this styles were certainly not getting applied in many areas. 

On my phone rn but can follow up with an example

**Comment by controversial** [comment]
Adding `'use client'` still breaks styling for me on Next.js 13.0.1

**Comment by shuding** [comment]
> Adding `'use client'` still breaks styling for me on Next.js 13.0.1

@controversial Would you mind providing a detailed reproduction so that I can take a look? Thanks!

**Comment by controversial** [comment]
Never mind, it was my mistake @shuding 😅 Of course, I realized as soon as I went to start creating a reproduction. Thanks for being on top of it! ❤️

**Comment by outdoteth** [comment]
@controversial what was the mistake? Hi did you fix it?
