### ISSUE TITLE
Next 13: Missing Types for generateStaticParams

### ISSUE THREAD

**Issue by sdorra** [vercel/next.js#41884]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
Binaries:
  Node: 16.18.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.13.4
Relevant packages:
  next: 13.0.0
  eslint-config-next: 13.0.0
  react: 18.2.0
  react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

A next 13 app with typescript and `generateStaticParams` can not be build. The following code works in dev mode, but fails on build:

```tsx
import { use } from "react";
import { fetchPeople, fetchPeoples } from "../../../lib/people";

type Params = {
  id: string;
};

type Props = {
  params: Params;
};

const People = ({ params }: Props) => {
  const people = use(fetchPeople(params.id));
  return (
    <>
      <h1>{people.name}</h1>
    </>
  );
};

export const generateStaticParams = async (): Promise<Params[]> => {
  const peoples = await fetchPeoples();

  const result = peoples.map((people) => ({
    id: people.id,
  }));

  return result;
}

export default People;
```

The build fails with the following error:

```
Type error: Page "app/people/[id]/page.tsx" does not match the required types of a Next.js Page.
  Invalid configuration:
    The exported page component isn't correctly typed.
        Expected "Props", got "PageProps".
          Invalid configuration:
            Expected "Params", got "PageParams | undefined".
              Expected "Params", got "undefined".
```

Sadly i was not able to find the mentioned types of the error.

Have a look at the following discussions for more informations:
* https://github.com/vercel/next.js/discussions/41826#discussioncomment-3966869
* https://github.com/vercel/next.js/discussions/41745#discussioncomment-3971314

### Expected Behavior

The example above can be build or the required types are exported.

### Link to reproduction

https://github.com/sdorra/next-13-missing-types

### To Reproduce

Run `pnpm build` in the example repository

**Comment by czterystaczwarty** [comment]
I'm facing the same problem during build:
```ts
type PageParams = {
  slug: string;
};

type PageProps = {
  params: PageParams;
};

export const dynamicParams = true;

export async function generateStaticParams(): Promise<PageParams[]> {
  const payload = await getNodes();

  return payload.nodes.map((node) => ({
    slug: node.path
  }));
}

export default async function NodePage({ params }: PageProps) {
  const node = await getNode(params.slug);
  if (!node) return notFound();
  return (
    <div>
      <h1>Hello, Next.js! {params.slug}</h1>
      <pre>{JSON.stringify({ node }, null, 2)}</pre>
    </div>
  );
}
```

```
...
info  - Compiled successfully
info  - Linting and checking validity of types ...Failed to compile.

Type error: Page "app/[slug]/page.tsx" does not match the required types of a Next.js Page.
  Invalid configuration:
    The exported page component isn't correctly typed.
          Invalid configuration:
            Expected "{ slug: string; } | undefined", got "PageParams | undefined".

```

**Comment by patrickedqvist** [comment]
Same here

```.tsx
export async function generateStaticParams() {
  const client = getClient();
  const res = await client.fetch(getArticlesSlugQuery);
  const articles = z.array(z.object({ slug: z.string() })).parse(res);

  return articles.map((article) => ({
    slug: article.slug,
  }));
}

export default async function Page({ params }: {
  params: { slug: string },
}) {

  // Queue up the promises here...
  const _article = getArticle(params.slug);
  const _relatedArticles = getRelatedArticles(params.slug);

  const article = await _article;

  return (
    <div>
      <div className='grid gap-x-20 grid-cols-[minmax(68ch,_1fr)_1fr] lg:items-start'>
        <article className='prose lg:text-lg'>
          <h1>{article.title}</h1>
          <RichText content={article.content} />
        </article>
        <aside className='sticky top-4'>
          <TableOfContent headings={article.tableOfContents} />
        </aside>
      </div>
      {/* Load related articles later on */}
      <Suspense fallback={<p>Loading related articles…</p>}>
        <RelatedArticles promise={_relatedArticles} />
      </Suspense>
    </div>
  );
}
```

```bash
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - Creating an optimized production build
info  - Compiled successfully
info  - Linting and checking validity of types ...Failed to compile.

Type error: Page "app/article/[slug]/page.tsx" does not match the required types of a Next.js Page.
  Invalid configuration:
    The exported page component isn't correctly typed.
        Expected "{ params: { slug: string; }; }", got "PageProps".
          Invalid configuration:
            Expected "{ slug: string; }", got "PageParams | undefined".
              Expected "{ slug: string; }", got "undefined".
```

**Comment by gabrielgrover** [comment]
@shuding Any idea when this will be released?

**Comment by shuding** [comment]
@gabrielgrover We already released `13.0.1`, let us know if the issue is still happening!

**Comment by gabrielgrover** [comment]
@shuding I still seem to be getting this error.  Here is the result of running `next build` 

<img width="821" alt="Screen Shot 2022-10-31 at 9 19 19 PM" src="https://user-images.githubusercontent.com/12038578/199157763-385a5bdc-d98a-443f-9dc8-25aba992ac1e.png">

Here is the file it is failing at `https://github.com/gabrielgrover/improved-octo-spoon/blob/main/app/blog/%5Bslug%5D/page.tsx`

**Comment by iAmmar7** [comment]
After updating to 13.0.1, I was still facing the issue. However, I fixed it by updating the page's type from **NextPage** to **FC**.

**Comment by gabrielgrover** [comment]
> After updating to 13.0.1, I was still facing the issue. However, I fixed it by updating the page's type from **NextPage** to **FC**.

This won't work for me because my blog page is `async`

**Comment by KushibikiMashu** [comment]
I know it's not a good way. However, I typed page props as below, then build was success.

```tsx
export default async function PostPage({ params }: { params: { slug: string } }) { ... }
```

**Comment by komzweb** [comment]
I was able to build for now after removing `generateStaticParams()`.

**Comment by daveteu** [comment]
> I know it's not a good way. However, I typed page props as below, then build was success.
> 
> ```tsx
> export default async function PostPage({ params }: { params: { slug: string } }) { ... }
> ```

can u try typing with searchParams as well?

**Comment by samstr** [comment]
I was seeing this error too. My mistake was accidentally forgetting to export `generateStaticParams` as an `async` function. Solved the problem after adding async

**Comment by fizzterious** [comment]
> 

I'm still running into this in 13.0.3. If anybody else stumbles on this, using `FC` also did the trick for me as a work around as a work-around. With new app folder, a page at `app/cameras/[id]/page.tsx` and `app/cameras/page.tsx` both get the same type error:

```
Type error: Page "app/cameras/page.tsx" does not match the required types of a Next.js Page.
  Invalid configuration:
    The exported page component isn't correctly typed.
      The exported page component isn't correctly typed.
```

In case it helps anybody else, this was my original code

```
import type { NextPage } from 'next'

type PageProps = {
  params?: {
    id: string
  }
  searchParams?: {
    search?: string
  }
};

const Home: FC = ({ params }: PageProps) => {
  // render stuff here
})

export default Home
```

It now works after making these changes:

```
import { FC } from "react";

type PageProps = {
  params?: {
    id: string
  }
  searchParams?: {
    search?: string
  }
};

const Home: FC = ({ params }: PageProps) => {
  // render stuff here
})

export default Home
```

**Comment by pmb0** [comment]
@thaddeuscleo I have got it now: `params` and if necessary `searchParams` must be declared as optional, then the compiler does not complain anymore.

```diff
-  searchParams: { currentPage: number };
+  searchParams?: { currentPage: number };
```

With it also own separately declared props types work.

**Comment by NotoriousPyro** [comment]
I got it working with the type hints as follows:

```typescript
export type Params<T> = { [key in keyof T]: string | string[] | undefined } | undefined
export type PageProps<T> = {
    params: Params<T>
    searchParams: Record<string, string>
} 
export type GenerateStaticParams<T extends Params<T>> = () => Promise<Params<T>[]>

type SearchPageSearchParams = Params<{
    slug: string
}>

export const generateStaticParams: GenerateStaticParams<SearchPageSearchParams> = async () => {
    return AllSearchTypes.map((value, index) => {
        return { slug: value.name }
    })
}

const SearchPage = ({params, searchParams}: PageProps<SearchPageSearchParams>) => {
    console.log(params)
    console.log(searchParams)
}

export default SearchPage
```

```
{slug: 'project'}
{q: '%'}
{slug: 'project'}
{q: '%'}
```

```
support-console-nextjs:build: └ ● /search/[slug]                         142 B          66.7 kB
support-console-nextjs:build:     ├ /search/user
support-console-nextjs:build:     ├ /search/project
support-console-nextjs:build:     ├ /search/service
support-console-nextjs:build:     └ /search/node
```

Doesn't appear to be any compiler errors and the types are visible.

**Comment by olowoseun** [comment]
@pmb0 is spot on. I experience the same error and all I had to do was use the optional chaining operator. The error from @sdorra console explains this as well.

**Comment by SANDAY-JS** [comment]
I found this error also occurs when you use `NextPage` type.

`const Page: NextPage = () => {.....`

fixed this after I remove or change this type like `React.FC`.

**Comment by mpereira** [comment]
This is still happening for me on Next 13.1.4, only during `next build`:
```
Type error: Page "app/[username]/[storySlug]/page.js" does not match the required types of a Next.js Page.
  Invalid configuration:
    The exported Page component isn't correctly typed.
        Expected "{ params: any; searchParams: any; }", got "PageProps".
```

`app/[username]/[storySlug]/page.js`
```js
async function StoryPage({ params, searchParams }) {
  ...
}

export default StoryPage;
```

**Comment by mtrenker** [comment]
> Next.js provides a TypeScript-first development experience for building your React application.

Weird that there is no generic for one of the most important components

**Comment by alsherif-khalaf** [comment]
> This is still happening for me on Next 13.1.4, only during `next build`:
> 
> ```
> Type error: Page "app/[username]/[storySlug]/page.js" does not match the required types of a Next.js Page.
>   Invalid configuration:
>     The exported Page component isn't correctly typed.
>         Expected "{ params: any; searchParams: any; }", got "PageProps".
> ```
> 
> `app/[username]/[storySlug]/page.js`
> 
> ```js
> async function StoryPage({ params, searchParams }) {
>   ...
> }
> 
> export default StoryPage;
> ```
> 
> Changing it to the following causes the error to **not happen**:
> 
> `app/[username]/[storySlug]/page.js`
> 
> ```js
> async function StoryPage(props) {
>   const { params, searchParams } = props;
>   ...
> }
> 
> export default StoryPage;
> ```

the perfect fix
It worked :)
thank you

**Comment by neotan** [comment]
was facing the same error, but my case was wrongly added `'use client'` at the top of the `page.tsx` file, **removing this line resolved.**
