### ISSUE TITLE
Next.js 13 stuck at `Creating an optimized production build...` when building with `swcMinify`

### ISSUE THREAD

**Issue by tianenpang** [vercel/next.js#42171]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```text
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.12.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.14.1
Relevant packages:
  next: 13.0.0 (13.0.1-canary.1)
  eslint-config-next: 13.0.0
  react: 18.2.0
  react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Chrome 107.0.5304.88

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Running `next build` will freeze at `Creating an optimized production build...` but will build successfully after disable the SWC Minifier in `next.config.js`. 

Similar with issue https://github.com/vercel/next.js/issues/37825 but, the build will always be stuck whether the development server is running or not.

Refer to https://github.com/nextui-org/nextui/issues/848

### Expected Behavior

Build successfully when using SWC Minifier.

### Link to reproduction

https://codesandbox.io/s/quizzical-tess-nnw9js

#### CodeSandbox
  1. Fork and add a new [terminal](https://codesandbox.io/docs/learn/repositories/terminal) then run `yarn build`
#### Locally
  1. Export the CodeSandbox project
  2. `pnpm install && pnpm build`

<details>
<summary>How to export the project from the CodeSandbox to local?</summary>

![how-to-export-project-from-codesandbox](https://user-images.githubusercontent.com/32772271/198870358-285491ab-e2d3-4a04-88f9-bb738dd5a90e.png)

</details>

**Comment by kdy1** [comment]
Thank you for creating a repro!
I started working on it

**Comment by kdy1** [comment]
This should be fixed by https://github.com/swc-project/swc/pull/6300 (Done, waiting for review)

**Comment by 0x3Anthony** [comment]
@tianenpang  Hey Buddy, how to solve this problem, I use the latest nextjs version and still encounter this problem?

**Comment by tianenpang** [comment]
Hi @0x3Anthony what version of Next.js are you using and which step is the build stuck at?

This issue has been fixed and I couldn't reproduce it using the latest version `(13.0.5)` of Next.js, if you are using `pnpm` or `yarn` you can update the dependencies with the following command, please remove `node_modules` and re-install them if necessary.

Upgrade deps:
```bash
# pnpm
pnpm up -L -i

# yarn
yarn upgrade-interactive --latest
```

My env:
```text
Binaries:
  Node: 18.12.1
  pnpm: 7.17.1
Relevant packages:
  next: 13.0.5
  eslint-config-next: 13.0.5
  react: 18.2.0
  react-dom: 18.2.0
  @nextui-org/react: 1.0.0-beta.10
```
