### ISSUE TITLE
Next 13 - When running turbo, scss stylesheets are not loaded

### ISSUE THREAD

**Issue by rmsheppard** [vercel/next.js#42375]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.2-canary.0
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

Scss modules do not appear to be loading under the new turbo 

The style import always returns undefined.

### Expected Behavior

Style is loaded and the red background css is present on the div.test element.

### Link to reproduction

used npx-create-next-app

### To Reproduce

When creating a new project from following command:

`npx create-next-app@latest --experimental-app`

And updating dev script to inlclude the turbo flag
`"dev": "next dev --turbo",`

Also loaded npm package "sass" as per instruction

When creating a very basic scss file: (./test.module.scss) in the app directory
`
.test {
	background-color: red;
}
`

And creating an page.js file in app directory
`
import styles from './test.module.scss';

const Home = () => {

	return (
		<div className={styles.test}>
			test
		</div>
	);
};

export default Home;
`

**Comment by AlexLup06** [comment]
It does not even work without turbo. No styles are applied whatsoever when navigating between pages. Guess css modules are just broken. 
Regular css files get applied, like global.scss
Always have to reload the page for styles to be applied

**Comment by nabil-betaflux** [comment]
Is this issue resolved ? I guess it was bad decision to use Next 13 at the moment for new projects.

**Comment by nabilnalakath** [comment]
Is this issue resolved? I guess it was a bad decision to use Next 13 at the moment for new projects.

But we have noticed that the styles are getting loaded if we use `<a>` tags instead of links for navigating. But that shouldn't; be the solution I believe.

**Comment by akomm** [comment]
The problem is not specific to scss or css modules. I use tailwind and have the same problem. Its a general problem of imported css files, no matter what generated them:

```ts
// app/layout.tsx
import "./layout.css"
```

When change and save the file, next dev compiler detects "a change" and outputs:
```
wait  - compiling...
[dev:*app] event - compiled client and server successfully in
```
I check the webpack resource url directly and its updated there as well.

The reason why there is no update is because the style tag does not get reloaded. The browser does not know the file has changed, it does not some event to reload the css file and recompute & repaint.

**Comment by akomm** [comment]
I found at least one reason, why css does not reload. Because the author of the issue has a different version than me, it might be two different bugs.


I'm using next 13.0.5. I'm pretty sure the following PR in 13.0.5 broke the css reload:

https://github.com/vercel/next.js/pull/43185

When I downgrade to 13.0.4 reload on css update works again.

The PR has removed the timestamp from the css file and so the url never changes and the browser does not reload it.

Maybe some of the people here, especially those transpiling from scss have the same issue?

**Comment by akomm** [comment]
@thecrypticace looks like what I'v observed and suspected. No update event and prior to removal of the timestamps in 1. from the CSS files, the bug was unnoticed because the refresh was triggered by browser reloading the file as the URL changed. 

I wonder: Since the output css **does** change and its imported on a route (tsx) shouldn't it be tracked by HMR for changes as it is a dependency of the tsx file?

**Comment by dawsnap** [comment]
I was having issues with tailwind styles to load as well, just fixed it by upgrading to next@13.1.1

https://github.com/vercel/next.js/releases/tag/v13.1.1

**Comment by joaoroche** [comment]
Guys, any news about?

**Comment by joaoroche** [comment]
Guys, problem solved in version 13.4.1

**Comment by meshack254** [comment]
Am using Next 13.4.1 and getting this error when using Turbo 
 "Turbopack does not yet support importing Sass modules."

**Comment by NEOdinok** [comment]
`Next.js @13.4.3` still get the error `"Turbopack does not yet support importing Sass modules."`

**Comment by kostalexis89** [comment]
I have the same issue. SCSS modules are not loaded on SSR. When i do 'use client' to my components then the styles are there. Also for the components that Im loading directly into the Layout file, styles are working on SSR and on Client Side. I have tried everything. Downgrade from 13.4.3 to 13.4.1, install postscss, loaders and I dont know what to do. 
Can somebody help here ?

**Comment by gabimoncha** [comment]
Same issue in `"next": "^13.5.4",`
```bash
SassError: SassError: Can't find stylesheet to import.
  ╷
1 │ @import "Auth.scss";
```

**Comment by pietro909** [comment]
Not related to Next itself, but I hope it'll help the next dev landing on this discussion: as silly as it sounds, my issue was that I had somehow set an override for the CSS files.
No idea how it happened but took me a bloody hour to find it 😢

**Comment by ckizer** [comment]
Any fixes for this? I can't keep the turbo flag engaged in any Next.js project and update my CSS, meaning I can't use TurboPack in any projects in October 2025.

**Comment by marcoshernanz** [comment]
Thanks for the report. The original failure was caused by Turbopack not supporting Sass at the time. Sass support landed in #49882 and vercel/turborepo#4985, and imported Sass HMR was fixed in vercel/turborepo#7813. I verified the minimal SCSS Module case plus HMR through an imported partial on Next.js 16.3.1 and the latest canary. Since newer reports represent different cases and should have current reproductions, I’m closing this as fixed. If the original minimal case still fails on a current release, please open a new issue with a reproduction.
