### ISSUE TITLE
Nextjs 13 - infinite `Creating an optimized production build`

### ISSUE THREAD

**Issue by jasperkooij** [vercel/next.js#42483]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Node v18.12.0 on Os X Ventura 13.0

package.json:

    "@nextui-org/react": "1.0.0-beta.9",
    "next": "latest",
    "react": "18.2.0",
    "react-dom": "18.2.0"
(also tried canary ->     "next": "13.0.2-canary.3",)

I'm using the Next UI example:

pnpm create next-app --example with-next-ui with-next-ui-app

pnpm run build is stuck building:

![image](https://user-images.githubusercontent.com/18720/199978564-2d005de4-e39a-4ba7-a4ba-6fc4e1e7fbab.png)

When I add:

'  swcMinify: false,` to next.config.js, it will be built correctly.

Next-UI is currently at `v1.0.0-beta.10` but that makes no difference.

I hoped this pull request https://github.com/vercel/next.js/pull/42326 would fix the issue

### How are you deploying your application? (if relevant)

pnpm run build

### Describe the Bug

Stuck in building the app:

Creating an optimized production build ...

### Expected Behavior

A full build😀

### Link to reproduction

https://github.com/vercel/next.js/tree/canary/examples/with-next-ui

### To Reproduce

pnpm create next-app --example with-next-ui with-next-ui-app
pnpm run build

**Comment by timneutkens** [comment]
According to @kdy1 this should be fixed by https://github.com/vercel/next.js/pull/42326, can you try running Next.js 13.0.2?

**Comment by jasperkooij** [comment]
That's what I was hoping for. I did a fresh build which gives me 13.0.2

![image](https://user-images.githubusercontent.com/18720/199987778-479268ce-e08f-40fe-809e-8bb434fc4f27.png)

then I tried with canary:
![image](https://user-images.githubusercontent.com/18720/199988063-9b47a731-16d6-472f-bfd4-77674c1127c5.png)

![image](https://user-images.githubusercontent.com/18720/199988263-2b6c93b1-4887-4658-adbf-41c3cd48c9eb.png)

**Comment by tianenpang** [comment]
Fixed in [`v13.0.3-canary.0`](https://github.com/vercel/next.js/releases/tag/v13.0.3-canary.0) install `next@canary` and give it a try 🎉

**Comment by jasperkooij** [comment]
@tianenpang Success!

<img width="969" alt="image" src="https://user-images.githubusercontent.com/18720/200123284-d1d1be79-a588-40fd-b45a-5d786a5f02e8.png">

Thanks for looking into this👍 🙌. How can I return the favor?

**Comment by 0x3Anthony** [comment]
now nextjs version 13.0.5, this compilation problem still exists, how can I solve it?This compilation problem still exists, how can I solve it?
