### ISSUE TITLE
[NEXT-658] Nextjs 13 Link not scrolling to anchor element

### ISSUE THREAD

**Issue by vladgardus** [vercel/next.js#44295]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

no github link

### To Reproduce

- Add Link with href={{ pathname: `/`, hash: "home" }}
- add div with id="home"
- clicking on link will not scroll to div

### Describe the Bug

Working on a next 13 app using the experimental flag. 

Created a header that has 3 next/link elements and the purpose of those 3 links is to set a hash on the URL and scroll to that anchor element.

The issue is that clicking on those links change the URL but does not scroll to the anchor element, but the strange thing is that by manually changing the hash in the URL does in fact trigger that scroll to the anchor element.

### Expected Behavior

Links that add hashes to URL should scroll to the anchor element.

<sub>[NEXT-658](https://linear.app/vercel/issue/NEXT-658/nextjs-13-link-not-scrolling-to-anchor-element)</sub>

**Comment by apriltaoyvr** [comment]
Can confirm that this is happening on 13.1.1

**Comment by myl7** [comment]
Can use plain old `<a>` to temporarily resolve it, in case anyone like me gets stuck by this

**Comment by grzegorzpokorski** [comment]
I'm confirm that this issue is happening on v13.1.1

**Comment by pabx12** [comment]
i have the same problem

**Comment by magnusriga** [comment]
Same issue here. Neither `/foo/#bar` or `/foo#bar` works.

**Comment by olavocarvalho** [comment]
Im facing the same issue. Workaround: currently using the react-scroll lib to scroll between sections in the page.

**Comment by magnusriga** [comment]
I solved this by checking, in a component with an id that might be scrolled to, whether it could find an element with the id set in window.location.hash. If so, scroll to it. I created the below hook to make it easier to use.

PS: The first component that uses the hook and finds the element, will handle the scroll. I tried to target the specific current element with a ref callback, but it did not scroll every time (have no idea why, see suggestion below).

Hook that always works:

```javascript
import { useEffect, useContext } from "react";
import { NavbarContext } from "@context/NavbarContext";

const useSmoothScrollTo = (targetHash = null) => {
  const { navRect } = useContext(NavbarContext);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const hash = targetHash || window.location.hash;

    if (!hash) return;

    const headerOffset = navRect?.height || "70";

    // Only proceed if target is a single hash tag
    const startWithHashRegex = /^#\w+/g;
    if (!startWithHashRegex.test(hash)) return;

    let target = document.querySelectorAll(`${hash}`)[0];

    if (!target) return;

    const elementPosition = target.getBoundingClientRect().top;
    const offsetPosition = elementPosition + window.pageYOffset - headerOffset;

    window.scrollTo({
      top: offsetPosition,
      behavior: "smooth",
    });
  }, [navRect.height, targetHash]);
};

export default useSmoothScrollTo;
```

Callback ref hook that only scrolls now and then:

```javascript
import { useContext, useCallback } from "react";
import { NavbarContext } from "@context/NavbarContext";

const useSmoothScrollTo = (hash = null) => {
  const { navRect } = useContext(NavbarContext);

  const ref = useCallback(
    (node) => {
      if (node !== null) {
        // Runs on mount of node

        if (typeof window === "undefined") return;
        const targetHash = hash || window.location.hash;

        if (!targetHash) return;

        // Only proceed if target is a single hash tag
        const startWithHashRegex = /^#\w+/g;
        if (!startWithHashRegex.test(targetHash)) return;

        const targetHashId = targetHash.substring(1);

        const headerOffset = navRect?.height || "70";

        const currentNodeId = node.id;

        console.log('targetHashId :>> ', targetHashId);
        console.log('currentNodeId :>> ', currentNodeId);

        if (targetHashId !== currentNodeId) return;

        const elementPosition = node.getBoundingClientRect().top;
        const offsetPosition =
          elementPosition + window.pageYOffset - headerOffset;

        window.scrollTo({
          top: offsetPosition,
          behavior: "smooth",
        });
      } else {
        // Runs on unmount of node
      }
    },
    [navRect.height, hash]
  );

  return ref;

  // useEffect(() => {

  // }, [navRect.height, targetHash]);
};

export default useSmoothScrollTo;
```

**Comment by grzegorzpokorski** [comment]
Another strange behavior which I am noticing in nextjs v13.2 with experimantal `/app` dir is that when I have a link e.g.: `<Link href="#place-on-page">link</Link>` on page located on `/page` path, it always redirect to `/#place-on-page` instead `/page#place-on-page`.

**Comment by nosovandriy** [comment]
Next 13.2.1 the same trouble with the anchor link

**Comment by jayantasamaddar** [comment]
Facing this same issue in **Next 13.2.3**

> Can use plain old `<a>` to temporarily resolve it, in case anyone like me gets stuck by this

@myl7 That will come with the window scroll-to-top problem, which has to be resolved on its own.

@magnusriga The issue isn't that we cannot write an useEffect to handle this. The issue is: **"Really, that's how we are gonna do things?"** so although calculating the offSet and manually scrolling may work, that's not the route we want to take at all. Not optimal.

**Comment by grzegorzpokorski** [comment]
URL hash (#) handling is in the Routing roadmap (https://beta.nextjs.org/docs/app-directory-roadmap), so we just need to wait for it to arrive.

**Comment by katakeynii** [comment]
Having the same trouble in Next 13.2.4 while using Link getting back to a tag

**Comment by franknoel** [comment]
I also have the same issue on 13.2.4, it worked before.

**Comment by pdhoward** [comment]
Same issue with 13.3.0

**Comment by tomas-cani** [comment]
Same issue with 13.3.2 when using router.push

**Comment by magnusriga** [comment]
I wanted to point out that linking to hash fragments now work in Next (as of a recent update), however it does not seem it is possible to make it scroll instead of jumping straight to the location. I also couldn't find a built-in way of accounting for the navbar height, so the current implementation by next.js is suboptimal.

I have implemented a custom solution using scrollTo, for now, but looking forward to a built-in solution.

**Comment by vanyapr** [comment]
Next js perceives the anchor link as a link to the main page. Now I have fixed it as follows, but scrolling the page to the anchor does not work.

`<Link href={`${document?.location.href}${link}`}>
              {title}
</Link>`

**Comment by vanyapr** [comment]
Here is my solution. First of all, I implemented a hook based on the suggestion of @**[magnusriga](https://github.com/magnusriga ).** 

``` jsx
const useScrollToAnchor = (offset: number = 70) => {
  return (anchor: string) => {
    if (!(typeof window === 'undefined')) {
      const startWithHashRegex = /^#\w+/g;
      const targetElement = document?.getElementById(`${anchor}`);

      if (!startWithHashRegex.test(anchor) || !targetElement) {
        return;
        // You can throw an error here
      }

      const elementPosition = targetElement.getBoundingClientRect().top;
      const offsetPosition = elementPosition + window.pageYOffset - offset;

      window.scrollTo({
        top: offsetPosition,
        behavior: 'smooth',
      });
    }
  };
};

export default useScrollToAnchor;
```

Next, I use this hook in the component. I replaced the links to the buttons, because the idea allows it.

``` jsx
import useScrollToAnchor from '@hooks/useScrollToAnchor';

function Component() {
	const scrollToAnchor = useScrollToAnchor(42);

	const makeActive = (link: string) => {
	  scrollToAnchor(link);
	};

	return (
		<button onClick={() => makeActive(link)} onKeyDown={() => makeActive(link)}>
		  {title}
		</button>
	)
}
```

In my solution, I am disconnected from the window object or the routing of the application, respectively, it is guaranteed to work. I hope it will help someone.

**Comment by SaveliiLukash** [comment]
Next 13.4.2 using app directory. I have a `Link` with `href="#all"` property on the `/transactions/deposits` page. 
As far as browser knows the resulting destination is `/transactions/deposits#all`, however I get routed to the homepage `/#all` when following the link.

Works as expected with native `a` anchors

**Comment by Maxservais** [comment]
I still face the issue as well - it links to the main page instead of the anchor element. You can try it live here: https://web3xplorer.com/

**Comment by hannupekka** [comment]
Same issue here.

**Comment by francisceril** [comment]
Having the same issue but only to the published app on Azure. On my local dev environment, it works as expected.

**Comment by eme-hache** [comment]
Having the same issue, but is funny, sometimes it works.

**Comment by AlexEnrique** [comment]
Same issue in NextJS v13.4.1. Using the default anchor as a temporary solution.

**Comment by shubh140601** [comment]
<Link href='#' redirects to Homepage same issue with v13.4.2

**Comment by shubh140601** [comment]
> Same issue in NextJS v13.4.1. Using the default anchor as a temporary solution.

**Comment by ShortyLogos** [comment]
I have the same problem. With a <Link> component, I'm trying to direct the user to "/anotherpage#dynamicanchor" from home page ("/") and it does so with a really strange offset. The temporary fix that works for me is using an anchor element (<a></a>) but it obviously makes the page reloads, which is not ideal.

**Comment by oliverkidd** [comment]
Just to confirm. Is there seriously still not a functional way to build anchor links to elements on the same page in a supposedly "stable" release of nextJs? The only workaround I can find using the Link element is to pass in the full URL by obtaining the current pathname from usePathName() and appending the anchor link. Surely there is a better way?

**Comment by ShortyLogos** [comment]
The fix I talked about (using an HTML anchor element) works in dev environment but not in production. Any idea why?

**Comment by danlevison** [comment]
I am having the same issue. In dev on my local server, scroll to hash-id works. However, once deployed on Netlify it does not work. If I inspect the <Link> tags (<a> tags) I can click the /#id and it will take me to the correct page. 

Also, I cannot seem to get smooth-scrolling to work even on my local server, it just jumps to the /#id. I hope we can find a fix for all this.

**Comment by rutenisrailanfq** [comment]
can confirm that these issues are present on:

    "next": "13.4.4",

**Comment by mtschuden** [comment]
I had the same problem.
I solved the problem by removing `overflow: scroll;` in my parent component.

**Comment by mtschuden** [comment]
> Does it automatically smooth scroll to fragments (hash ids)? Both when coming from another page and for in-page links?

Yes it scrolls smoothly to the section fragment when you come from another page. (`<Link>` without `scroll props`)

It is important to set the following for `html` in your css.

```css
html {
    --scroll-behavior: smooth !important;
    scroll-behavior: smooth !important;
}
```

**Comment by YoniChechik** [comment]
@timneutkens can you please reopen this issue? a fix is still not available...

**Comment by YoniChechik** [comment]
my fix works in prod:

```
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

export default function Heading({ id }: any): JSX.Element {
  const pathname = usePathname();

  return (

      <Link
        href={`${pathname}#${id}`}
        aria-label={anchorTitle}
        title={anchorTitle}
      >
        #
      </Link>
    </As>
  );
}
```

**Comment by clevinson** [comment]
I can confirm the same problems arise for me where locally the anchor links work as expected, but when deployed on netlify, it strips the anchor tag from the URL and reloads hte page:

> I am having the same issue. In dev on my local server, scroll to hash-id works. However, once deployed on Netlify it does not work. If I inspect the 'Link' tags ('a' tags) I can click the /#id and it will take me to the correct section of my page.
> 
> Also, I cannot seem to get smooth-scrolling to work even on my local server, it just jumps to the /#id. I hope we can find a fix for all this.

It would be great to have this issue re-opened if the issue on netlify is related to this same source problem. Otherwise, I can fine a new issue.

**Comment by clevinson** [comment]
Seems like the issue with netlfiy is that Netlify's latest version of "Next.js Runtime" only supports next v13.4.3 still. I think they've only been fixed as of next v13.4.5.

**Comment by timneutkens** [comment]
@YoniChechik if you're talking about `<Link href="#somewhere">` that was fixed on May 9th in this PR: #49521, landed in canary on [v13.4.5-canary.1](https://github.com/vercel/next.js/releases/tag/v13.4.5-canary.1) and then on stable in [v13.4.5](https://github.com/vercel/next.js/releases/tag/v13.4.5).

**Comment by AlmazHecker** [comment]
> > Does it automatically smooth scroll to fragments (hash ids)? Both when coming from another page and for in-page links?
> 
> Yes it scrolls smoothly to the section fragment when you come from another page. (`<Link>` without `scroll props`)
> 
> It is important to set the following for `html` in your css.
> 
> ```css
> html {
>     --scroll-behavior: smooth !important;
>     scroll-behavior: smooth !important;
> }
> ```

u'r a life saver!

**Comment by TiagoJeronimo** [comment]
> > Does it automatically smooth scroll to fragments (hash ids)? Both when coming from another page and for in-page links?
> 
> Yes it scrolls smoothly to the section fragment when you come from another page. (`<Link>` without `scroll props`)
> 
> It is important to set the following for `html` in your css.
> 
> ```css
> html {
>     --scroll-behavior: smooth !important;
>     scroll-behavior: smooth !important;
> }
> ```

This helped! But in my case, I also had to add the prop `scroll={false}` to the NextLink to make it work: 
```
import NextLink from 'next/link';

<NextLink href={href} scroll={false}>
  {children}
</NextLink>
```

**Comment by vdaguenet** [comment]
> @YoniChechik if you're talking about `<Link href="#somewhere">` that was fixed on May 9th in this PR: #49521, landed in canary on [v13.4.5-canary.1](https://github.com/vercel/next.js/releases/tag/v13.4.5-canary.1) and then on stable in [v13.4.5](https://github.com/vercel/next.js/releases/tag/v13.4.5).

The problem is still happening on v13.4.10.

**Comment by timneutkens** [comment]
@vdaguenet please open a new issue and include a reproduction.

**Comment by rtrembecky** [comment]
> > @YoniChechik if you're talking about `<Link href="#somewhere">` that was fixed on May 9th in this PR: #49521, landed in canary on [v13.4.5-canary.1](https://github.com/vercel/next.js/releases/tag/v13.4.5-canary.1) and then on stable in [v13.4.5](https://github.com/vercel/next.js/releases/tag/v13.4.5).
> 
> The problem is still happening on v13.4.10.

I confirm it worked for me on 13.4.6 and it doesn't now when I upgrade to 13.4.10.

**Comment by timneutkens** [comment]
https://github.com/vercel/next.js/issues/44295#issuecomment-1639816687
