### ISSUE TITLE
SWC breaks full calendar

### ISSUE THREAD

**Issue by christianjuth** [vercel/next.js#44983]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.4.0
      npm: 9.2.0
      Yarn: 3.3.1
      pnpm: N/A
    Relevant packages:
      next: 13.1.3-canary.2
      eslint-config-next: 13.1.2
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC minifier (swcMinify: true)

### Link to the code that reproduces this issue

https://github.com/breakthelovenewyork/next-full-calendar-test

### To Reproduce

Build the repository and visit the top level index route.

Alternatively you can try this deployment I already made and look at the console.

https://full-calendar-test-christianjuth-breakthelovenewyork.vercel.app//

### Describe the Bug

Next app builds and page loads initially. However, as soon as I try to interact with full calendar I get this weird null pointer error in the console. It seems – without really knowing how minifiers work – that SWC is removing an object it shouldn't be, causing the app to crash when full calendar tries to access properties on that object.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'allDay')
    at ns (e501331d-4147ea66e121ec61.js:1:53236)
    at ru.render (e501331d-4147ea66e121ec61.js:1:89153)
    at T (407-ab674bd8c72b08ef.js:1:13663)
    at w (407-ab674bd8c72b08ef.js:1:9982)
    at T (407-ab674bd8c72b08ef.js:1:14047)
    at w (407-ab674bd8c72b08ef.js:1:9982)
    at 407-ab674bd8c72b08ef.js:1:15199
    at T (407-ab674bd8c72b08ef.js:1:15569)
    at w (407-ab674bd8c72b08ef.js:1:9982)
    at T (407-ab674bd8c72b08ef.js:1:14047)
```

If I set the following option it starts working.
```javascript
// next.config.js
const nextConfig = {
  swcMinify: false
}
```

### Expected Behavior

My app should word the same whether SWC is enabled or not.

### How are you deploying your application? (if relevant)

Vercel

**Comment by mohux** [comment]
I am having the same issue and due to it, had to disabled SWC

**Comment by kdy1** [comment]
Fixed by https://github.com/vercel/next.js/pull/45776

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/29931815/218335842-6a0b8d43-423e-4b3e-bed0-491260deb034.png">

**Comment by mohux** [comment]
@kdy1 thank you for your response
but the issue still exists when ever you use things "selectMirror" prop
which causes the same exact issue as before

disabling this prop makes it work,
potentially https://github.com/swc-project/swc/issues/6914 could lead to why this is an issue

**Comment by mohux** [comment]
I can confirm that this solved the issue for me
updating to next@canary solved the issue

@kdy1 thank you so much
