### ISSUE TITLE
Hight number of processes of /next/dist/compiled/jest-worker/processChild.js still alive after next build

### ISSUE THREAD

**Issue by zqjimlove** [vercel/next.js#45508]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.26.2
    Relevant packages:
      next: 12.0.9
      react: 17.0.2
      react-dom: 17.0.2

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/files/10565355/reproduce.zip

### To Reproduce

[reproduce.zip](https://github.com/vercel/next.js/files/10565355/reproduce.zip)

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/3240259/216242566-6f87ae6e-e369-405f-9fca-e525e051797d.png">

This problem can reproduce above next@12.0.9, but 12.0.8 was all right.

Or remove `getInitialProps` in `_app.tsx ` was all right above next@12.0.9.

```ts
// GlobalApp.getInitialProps = async function getInitialProps(appContext) {
//   const appProps = await App.getInitialProps(appContext);

//   return {
//     ...appProps,
//   };
// };
```

### Describe the Bug

Hight number of processes of /next/dist/compiled/jest-worker/processChild.js still alive after next build

### Expected Behavior

Kill all child processes.

<sub>[NEXT-1348](https://linear.app/vercel/issue/NEXT-1348/hight-number-of-processes-of-nextdistcompiledjest-workerprocesschildjs)</sub>

**Comment by Francoois** [comment]
I think I have the same issue.
I am using headless CMS Keystone on a virtual environment allowing a maximum of 250 processes in parallel. 
I'm getting a lot of `keystone-app/node_modules/next/dist/compiled/jest-worker/processChild.js` processes in parallel, which block the build of the app.
I'm trying to find a workaround.

**Comment by yzubkov** [comment]
In my case I get several ".../node_modules/next/dist/compiled/jest-worker/processChild.js" of these processes taking up lots of memory. I see these appear after executing "npm run start", and they disappear when I terminate the app (Ctrl+c).
Not sure if or how this potentially relates to the build process.

**Comment by schorfES** [comment]
We have also observed this issue in production, where it consumes memory that is likely not used or needed. This behavior was introduced in version `13.4.0`. There is an open discussion about this topic, which you can find at: https://github.com/vercel/next.js/discussions/49238.

**Comment by nicosh** [comment]
We have the same problem, after few deployments server is going out of memory.  As temporary fix i added the following script in the deployment pipeline : 
```bash
#!/bin/bash

# Find the process IDs of all processes containing the string "processChild.js" in the command path
pids=$(pgrep -f "processChild.js")

# Iterate over each process ID and kill the corresponding process
for pid in $pids; do
    echo "Killing process: $pid"
    kill "$pid"
done
```
But even with this script seems that applications keep spawning zombie processes.

**Comment by switz** [comment]
Seeing this as well in prod

**Comment by MonstraG** [comment]
Downgrading to `<13.4.0` for now I guess

**Comment by leerob** [comment]
Merged this discussion into here: https://github.com/vercel/next.js/discussions/49238

This might be related: https://github.com/vercel/next.js/commit/83b774eeb69f1fe4f636260f83ed98c6d0717a3d#diff-90d1d5f446bdf243be25cc4ea2295a9c91508859d655e51d5ec4a3562d3a24d9L1930

**Comment by leerob** [comment]
Small favor, could you include a reproduction as a CodeSandbox instead of a `zip` file?

**Comment by bfife-bsci** [comment]
I am commenting as a +1 to #49238 which I think more accurately described our issue.  We only have 2 processChild.js processes, but this is likely due to running on GKE nodes with 2 CPUs.  We run a minimum of 3 pods behind a service/load balancer.

We were running 13.4.1 on node v16.19.0 in our production environment, and discovered that after some volume of requests or perhaps even period of time (as short as a day and a half, as long as 5 days), some next.js servers were becoming slow to unresponsive.  New requests would take at least 5 seconds to process a response.  CPU usage in the pod was maxed out, divided roughly at 33% user and 66% system.  We discovered that requests are being proxied to a `processChild.js` child process, which is listening on a different port (is this the new App Router?).  We observed the following characteristics:

- excessive CPU usage
- no extra logging was observed (we don't see any logs after server startup)
- there were over 3100 TCP connections established between the parent and `processChild.js` process
- the parent process appeared to be retrying/attempting to retransmit requests that were queued up inside of it

strace'ing showed the following signature over and over again with different sockets/URLs

```
...
write(1593, "GET /URL1"..., 2828) = -1 EAGAIN (Resource temporarily unavailable)
write(1600, "GET /URL2"..., 2833) = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(13, [{EPOLLOUT, {u32=266, u64=266}}, {EPOLLOUT, {u32=276, u64=276}}, {EPOLLOUT, {u32=280, u64=280}}, {EPOLLOUT, {u32=267, u64=267}}, {EPOLLOUT, {u32=315, u64=315}}, {EPOLLOUT, {u32=20, u64=20}}, {EPOLLOUT, {u32=322, u64=322}}, {EPOLLOUT, {u32=275, u64=275}}, {EPOLLOUT, {u32=325, u64=325}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=332, u64=332}}, {EPOLLOUT, {u32=336, u64=336}}, {EPOLLOUT, {u32=314, u64=314}}, {EPOLLOUT, {u32=358, u64=358}}, {EPOLLOUT, {u32=324, u64=324}}, {EPOLLOUT, {u32=360, u64=360}}, {EPOLLOUT, {u32=281, u64=281}}, {EPOLLOUT, {u32=335, u64=335}}, {EPOLLOUT, {u32=296, u64=296}}, {EPOLLOUT, {u32=343, u64=343}}, {EPOLLOUT, {u32=377, u64=377}}, {EPOLLOUT, {u32=379, u64=379}}, {EPOLLOUT, {u32=359, u64=359}}, {EPOLLOUT, {u32=285, u64=285}}, {EPOLLOUT, {u32=268, u64=268}}, {EPOLLOUT, {u32=392, u64=392}}, {EPOLLOUT, {u32=366, u64=366}}, {EPOLLOUT, {u32=378, u64=378}}, {EPOLLOUT, {u32=406, u64=406}}, {EPOLLOUT, {u32=326, u64=326}}, {EPOLLOUT, {u32=323, u64=323}}, {EPOLLOUT, {u32=420, u64=420}}, ...], 1024, 0) = 275
write(266, "GET /URL3"..., 2839) = -1 EAGAIN (Resource temporarily unavailable)
write(276, "GET /URL4"..., 2830) = -1 EAGAIN (Resource temporarily unavailable)
write(280, "GET /URL5"..., 2825) = -1 EAGAIN (Resource temporarily unavailable)
...
```

It looks like the parent process continuously retries sending requests which are not being serviced/read into the child process.  We're not sure what puts the server into this state (new requests will still be accepted and responded to slowly), but due to the unresponsiveness we downgraded back to 13.2.3.

**Comment by billnbell** [comment]
I get next/dist/compiled/jest-worker/processChild.js  running in NODE_ENV=production when running `next start` ??

Downgrading.

**Comment by csi-lk** [comment]
> Downgrading

Hmm I don't know if downgrading helps @billnbell , I've seen this in our traces going back a few versions now, let me know if you have a specific version where this isn't an issue, I'm worried about memory utilisation as we're seeing it max out on our containers :)

**Comment by cjcheshire** [comment]
Here to say me too. We’ve recently jumped on the 13.4 bandwagon and the last two weeks started to see memory maxing.

**Comment by BuddhiAbeyratne** [comment]
maybe this will help too  


        git pull
        npm ci || exit
        BUILD_DIR=.nexttemp npm run build || exit
        if [ ! -d ".nexttemp" ]; then\
                echo '\033[31m .nexttemp Directory not exists!\033[0m'; \
                exit 1; \
        fi;
        rm -rf .next
        mv .nexttemp .next
        pm2 reload all --update-env
        echo "Deployment done."
        
```

**Comment by BuddhiAbeyratne** [comment]
seems like the jest worker is required or else pm2 can't serve the site on prod mode

**Comment by BuddhiAbeyratne** [comment]
the solution im using now is kill all and restart the service so it only makes 2 workers

**Comment by cjcheshire** [comment]
> I just had a massive outage thanks to this it creeps up on you and doesn't die there's no way to easily kill the workers and also it stops build systems once it hits max ram

This is freaky. We just did too!

We have 800 pages, some more than others have more than two api requests to build the page. We had a 1gb limit on our pods, upped to 2gb and has helped us.

**Comment by billnbell** [comment]
> I'm on `13.4.1` if that helps to debug
That is why I switched to 13.2.3. I have not tried newer versions or canary yet.

**Comment by billnbell** [comment]
Just to be clear - we get out of memory in PRODUCTION mode when serving the site. I know others are seeing it when using `next build` but we are getting this over time when. using `next start`. Downgrading worked for us.

I don't really know why jest is running and eating all memory on the box. Can we add a parameter to turn off jest when running `next start` ?

**Comment by cjcheshire** [comment]
@billnbell its not jest though right it’s the jest-worker package. 

We even prune dev dependencies in production!

**Comment by billnbell** [comment]
What is a jest-worker?

**Comment by S-YOU** [comment]
The name jest-worker is actually confusing (at least for me) because of popular test framework jest, 
jest itself seems to be huge repository with a lot of packages, it should called facebook's web server / worker or something else.

**Comment by S-YOU** [comment]
> there were over 3100 TCP connections established between the parent and processChild.js process

This kind of task perform best with unix sockets, and seems like Next.js team is not interested on unix sockets (PR closed: https://github.com/vercel/next.js/pull/20192). PR itself is about front side, but with current architecture, 
communication between parent and children with Unix sockets would be nice improvement (when available of course)

**Comment by BuddhiAbeyratne** [comment]
@billnbell app dir is not stable on that as far as I was aware. can you let me know if you use it ?

**Comment by billnbell** [comment]
> It’s a package. Which we presume is how the background tasks work for building. https://www.npmjs.com/package/jest-worker?activeTab=readme

Why would it be running in `next start` mode? We are not building anymore.

**Comment by billnbell** [comment]
> @billnbell app dir is not stable on that as far as I was aware. can you let me know if you use it ?

What do you mean? What is app dir?

**Comment by cjcheshire** [comment]
@billnbell There’s now two route approaches. The older of the two was the [pages](https://nextjs.org/docs/pages/building-your-application/routing), the newer that seems to still need some love is the [app](https://nextjs.org/docs/app/building-your-application/routing) folder. 

We have the issue and use the older architectural approach - pages not app.

**Comment by billnbell** [comment]
We are using pages

**Comment by bfife-bsci** [comment]
> > It’s a package. Which we presume is how the background tasks work for building. https://www.npmjs.com/package/jest-worker?activeTab=readme
> 
> Why would it be running in `next start` mode? We are not building anymore.

This is what we see as well; there are jest-worker `processChild.js` running at run time in production, not at build time.  They seem to be used for rendering requested pages.

**Comment by HamAndRock** [comment]
We are also having memory issues on app router with some apps just running out of memory after few hours and forcing restarts.

Can't really give much info here :/ But we are having similar issues since some versions

**Comment by nicosh** [comment]
In my case, I had a component that made some socket connections, which caused the application to crash. PM2 will respawn the application in cluster mode without killing those processes so I ended up with three additional ghost processes every time the application crashed.

**Comment by t0mtaylor** [comment]
> I can confirm downgrading worked for me. `13.2.3`

@billnbell i'm running `13.3.4` which is below `13.4.x` and things seem ok with the jest-worker.

do you want to give that a try and confirm? otherwise ill try and drop down further to `13.2.3`

**Comment by DenisBessa** [comment]
This error lead up to make a 7-node Kubernetes deployment goes completely unresponsive randomly. Almost got nuts here.

**Comment by christopherbowers** [comment]
> > I can confirm downgrading worked for me. `13.2.3`
> 
> @billnbell i'm running `13.3.4` which is below `13.4.x` and things seem ok with the jest-worker.
> 
> do you want to give that a try and confirm? otherwise ill try and drop down further to `13.2.3`

After our EC2 m6i.2xlarge went unresponsive on `13.4.2` we downgraded to `13.3.4` to fix the `jest-worker` and `processChild.js` processes

**Comment by ericmgoeken** [comment]
Our site uses the app folder routes. I'm not sure downgrading to 13.3.4 is an option.

**Comment by BuddhiAbeyratneAL** [comment]
it is not @ericmgoeken solution we used was to cull that process using the snip of @nicosh and do a restart on a cron tab at random intervals
^ This is not a fix and I frankly hate we have to resort to this 

The zero downtime deployments kinda handles this abuse

**Comment by billnbell** [comment]
Is the consensus is 13.3.4 works ?

**Comment by ericmgoeken** [comment]
Yeah, I even got the app route working on 13.3.4

**Comment by t0mtaylor** [comment]
> Yeah, I even got the app route working on 13.3.4

@ericmgoeken can you put here how with any code snippets which may help @BuddhiAbeyratne @BuddhiAbeyratneAL and anyone else run app routing for 13.3.4?

**Comment by ericmgoeken** [comment]
@t0mtaylor, I just changed the package.json to 13.3.4 and added the experimental config
```
  experimental:{
    appDir: true
  },
```

Also, to add context to the issue. For my project it would go out of control from npm start. If I reboot the server it go out of control again. So, you need to do npm build before npm start, but its not the build command that caused the issue for me.

**Comment by faridvatani** [comment]
What is the minimum amount of RAM required for the processChild.js process? Has anyone had experience adding more RAM?

**Comment by cjcheshire** [comment]
> What is the minimum amount of RAM required for the processChild.js process? Has anyone had experience adding more RAM?

We had 1gb in our pods. We upped to 2gb. This prevented the freak out the Friday before last where our pods just kept rebooting. They’d always peak on spin up, as the cache was cold. We are looking into sharing the cache between pods to help with that.

We dropped to 13.2.3 the following week as our pods never scaled back. Since the revert they were happy (but we all know this)

**Comment by redaxle** [comment]
@billnbell it seems like 13.2.4 is the most recent version that doesn't create these jest-worker processes.

**Comment by betoquiroga** [comment]
I have a project deployed on AWS and we had upgraded to 13.4 to use Next/fonts on production. But, after the deploy the jest-worker processes kill our website with only 300 concurrent users. 
AWS autoscaling went into create until 10 new images to balance the load in minutes! Crazy!

We solved it, for now, going down to 13.2.4

**Comment by cannontrodder** [comment]
Seems relevant: https://github.com/vercel/next.js/pull/51271

**Comment by EpicIvo** [comment]
Hosting on Platform.sh here and downgrading from 13.4 to 13.2.4 seems to have solved the issue for now 👌🏽

**Comment by ijjk** [comment]
@cannontrodder is correct and the reduced workers can explain any noticed slowdown, please upgrade to `13.4.6` and see if this alleviates any issues noticed here!

**Comment by daiyam** [comment]
I'm using pages dir and I still have the issue with `13.4.6`.

**Comment by ijjk** [comment]
@daiyam what is the issue you seeing persisting in `v13.4.6`?

**Comment by daiyam** [comment]
@ijjk Yes, if `/next/dist/compiled/jest-worker/processChild.js` are only created by `next build`. (I've only tested on a new website in prod, so there is always `next start` just after. I found out about the issue only yesterday, after the docker container was using 3GB of memory...)

**Comment by masterkain** [comment]
this thread seems to be a mixed bag of people having issues during *build* time and/or *runtime* -- I can add my experience with the runtime https://github.com/vercel/next.js/issues/49623 (tl;dr add RAM)

**Comment by masterkain** [comment]
> We had 1gb in our pods. We upped to 2gb. This prevented the freak out the Friday before last where our pods just kept rebooting and scales to 10. They’d always peak on spin up, as the cache was cold. We are looking into sharing the cache between pods to help with that.

I did exactly that using Helm (https://github.com/icoretech/helm/blob/main/charts/airbroke/values.yaml#L22) but did not change a thing and also I'm sure this should be done

**Comment by cjcheshire** [comment]
@masterkain there's a thread here on this: https://github.com/vercel/next.js/discussions/23017#discussioncomment-5230940. There’s a flag `isrMemoryCacheSize` you’ll need to set to zero for it to work it looks like. 

Slightly worrying about it possible causing a race condition though - https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#self-hosting-isr

**Comment by masterkain** [comment]
> There’s a flag `isrMemoryCacheSize` you’ll need to set to zero for it to work it looks like.
> 
> Slightly worrying about it possible causing a race condition though - https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#self-hosting-isr

interesting, thanks for that, I did think about the race condition but I was missing `isrMemoryCacheSize`, time to experiment again, but I deviated a bit from the original topic so back to you people 👍

**Comment by lazarv** [comment]
Next.js 13 using an app router (which is by default on since 13.4) is always using workers to run the app, see at https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/start-server.ts#L182, while the main app (main thread) is acting as a proxy for the workers. I created an issue about this at https://github.com/vercel/next.js/issues/50586

At runtime, this is not related to any build process, as I see. Next.js is just using `jest-worker` as a solution to start child processes. My assumption is that this is like that to speed up the new RSC rendering, as that is not optimal, see https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/use-flight-response.tsx

**Comment by madjam002** [comment]
All of my servers have been seeing `TCP: out of memory -- consider tuning tcp_mem` in the kernel logs recently, causing Nginx connection reset issues when talking to the NextJS upstream, after digging into it there's a bunch of connections appearing from the NextJS process like so:

```
$ ip netns exec xxx ss -aemnpt

...
CLOSE-WAIT               142051                 0                                                127.0.0.1:48390                                          127.0.0.1:33853                 users:(("node",pid=14777,fd=85)) ino:88488113 sk:5a -->
	 skmem:(r208866,rb2358342,t0,tb2626560,f30,w0,o0,bl0,d0)                                                                       
CLOSE-WAIT               174810                 0                                                127.0.0.1:45838                                          127.0.0.1:33853                 users:(("node",pid=14777,fd=50)) ino:88446849 sk:5c -->
	 skmem:(r183190,rb4978722,t0,tb2626560,f1130,w0,o0,bl0,d1)                                                                     
....
```

All going out to port 33853, which turns up "jest-worker/processChild.js", which lead me to find this GitHub issue

```
$ ps aux | grep xxx
root     14927  0.5  0.4 32811872 135924 ?     Sl   14:13   0:06 /nix/store/m00hsyaqpin3awwjyx0v7lxwzix73ibd-next-13.4.6-c2942e4eb7.zip/node_modules/next/dist/compiled/jest-worker/processChild.js
```

After a few hours there are thousands of connections in the CLOSE-WAIT state per NextJS process. Seeing this on NextJS 13.4.7 as well. Downgrading to 13.2.4 fixes the issue.

**Comment by hnsr** [comment]
Confirming this issue. We deploy in standalone mode and run our app with PM2 instances, but PM2 no longer reports accurate memory usage (making the max memory restart feature broken), and leaves jest-worker processes running even after killing the parent PM2 instances, causing constant OOM situations.

**Comment by Innei** [comment]
> Confirming this issue (at runtime). We deploy in standalone mode and run our app with PM2 instances, but PM2 no longer reports accurate memory usage (making the max memory restart feature broken), and leaves jest-worker processes running even after killing the parent PM2 instances, causing constant OOM situations.

Is there another solution, my app also deploys in standalone mode and runs our app with PM2 instances, but not using appDir and `next/images`, middleware as well.

Something, `/dist/standalone/node_modules/.pnpm/next@13.4.5_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js` memory leak and not trigger system OOM killer, leads to system hanging up.

**Comment by Innei** [comment]
About atop monitor. It leak 1G memory costs about 5 seconds

<img width="2065" alt="CleanShot 2023-06-27 at 5 23 04@2x" src="https://github.com/vercel/next.js/assets/41265413/e3ee9ede-5302-4cd1-b345-8703fbd05b18">

**Comment by uncvrd** [comment]
> Confirming this issue (at runtime). We deploy in standalone mode and run our app with PM2 instances, but PM2 no longer reports accurate memory usage (making the max memory restart feature broken), and leaves jest-worker processes running even after killing the parent PM2 instances, causing constant OOM situations.

@hnsr were you able to confirm that disabling appDir reduced your memory footprint on your project? I see that you referenced a PR here and I just gave it a shot on mine. I made sure to match your NextJS version (13.4.5) and still had a large bump in memory consumption upon first request 🤔 

<img width="155" alt="image" src="https://github.com/vercel/next.js/assets/25097099/2c90a4f7-42b0-45bf-a9a5-f755f6665f09">

**Comment by hnsr** [comment]
@uncvrd It seems that disabling appDir didn't work for us either to avoid the use of jest-worker. I haven't had time to look into it further, but will give this another look and let you know if I find a workaround.

**Comment by hnsr** [comment]
> > Confirming this issue (at runtime). We deploy in standalone mode and run our app with PM2 instances, but PM2 no longer reports accurate memory usage (making the max memory restart feature broken), and leaves jest-worker processes running even after killing the parent PM2 instances, causing constant OOM situations.
> 
> Is there another solution, my app also deploys in standalone mode and runs our app with PM2 instances, but not using appDir and `next/images`, middleware as well.
> 
> Something, `/dist/standalone/node_modules/.pnpm/next@13.4.5_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js` memory leak and not trigger system OOM killer, leads to system hanging up.

Our hoster also noted this, that the whole server we run on went down, as opposed to the OOM killer being invoked to keep things under control. I wonder why that is 🤔

**Comment by hnsr** [comment]
@uncvrd So it seems that the `server.js` that is generated in standalone is simply written to always use workers:

- Older version: https://github.com/vercel/next.js/blob/v13.2.4/packages/next/src/build/utils.ts#L1892-L1950
- Current version: https://github.com/vercel/next.js/blob/canary/packages/next/src/build/utils.ts#L1931-L2004

As you can see the new version uses `createServerHandler` from https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/render-server-standalone.ts which always uses workers.

I am probably going to see if we can simply stick to an older version of nextjs for now

**Comment by Innei** [comment]
Yes, OOM killer not working. This is my server monitor, it increases IO, CPU, Memory suddenly.

<img width="527" alt="CleanShot 2023-06-27 at 9 19 43@2x" src="https://github.com/vercel/next.js/assets/41265413/c4b144fd-0952-48e8-9686-f03b260b791a">

**Comment by uncvrd** [comment]
@hnsr thanks for confirming on your end. That's really odd, I had some luck reverting to 13.3.2 today so I'll stick with that for now

**Comment by hnsr** [comment]
The worker process seems to be introduced in this commit: [Fix standalone mode with appDir running in a single proces](https://github.com/vercel/next.js/commit/83b774eeb69f1fe4f636260f83ed98c6d0717a3d#diff-55074c0b0e3d88f7cd3d222e45b05d703b054a99776663e9e95c800bb80fd740)

This is released in [13.4.0](https://github.com/vercel/next.js/releases/tag/v13.4.0), the last release without the workers is 13.3.4

Why we are downgrading:

1. We had an issue where a process crashed, but the worker wasn't cleaned up. PM2 restarted nextjs several times a second, causing it to eat up 60GB of memory in a few seconds, crashing the server.

2. We're currently using pm2 to run the application, but pm2 is unable to report the used memory (which we are trying to use to automatically restart when it is running out).

   Creating a worker process for the standalone mode seems somewhat odd in my opinion, according to the docs:

   > Additionally, a minimal server.js file is also output which can be used instead of next start.

   Using separate worker processes isn't as minimal as it could be. Is there any way to get it 'flat' again @shuding?

**Comment by billnbell** [comment]
Or maybe we can add a parameter to turn off workers in Standalone mode?

What would be the impact of turning it off? And why was it added?

**Comment by ijjk** [comment]
The separate processes are needed to ensure `app` and `pages` routes are rendered separately as they require different versions of react. The workers also already monitor memory usage and restart when running out so pm2 shouldn't be needed here to achieve that. 

What was the crash where the workers weren't cleaned up, sounds like that's more of the issue we should be addressing here.

**Comment by broksonic21** [comment]
@ijjk not sure if the crash you speak of, but I can create a crash even on the stock template app with workers here: https://github.com/vercel/next.js/issues/51560

Doesn’t repro without workers. (appDir false)

**Comment by S-YOU** [comment]
> app and pages routes are rendered separately as they require different versions of react. 

Didn't realize two versions of react is needed. Hopefully it will be one in the future then.

**Comment by billnbell** [comment]
OK, can we set the usage of memory on the box? 90% is not what we need.

```
const MAXIMUM_HEAP_SIZE_ALLOWED =
(v8.getHeapStatistics().heap_size_limit / 1024 / 1024) * 0.9

```

Question - for us only using pages can we turn this off ?

**Comment by billnbell** [comment]
Also, if our process has NODE memory set with `--max-old-space-size=8192` will v8.getHeapStatistics().heap_size_limit return right value?

**Comment by hnsr** [comment]
> The separate processes are needed to ensure `app` and `pages` routes are rendered separately as they require different versions of react. The workers also already monitor memory usage and restart when running out so pm2 shouldn't be needed here to achieve that.
> 
> What was the crash where the workers weren't cleaned up, sounds like that's more of the issue we should be addressing here.

I agree mostly that this is the thing that needs to be investigated and fixed. The crashes in our case were mainly startup errors, i.e. EADDRINUSE because the standalone server.js failed to bind on port 3000. Another earlier cause was a SynaxError (due to running the wrong node version). During `next dev` this can happen as well if I make a typo, hot reloading will fail and it will crash, leaving a jest-worker running. Since I am a bad programmer, this can lead to my macbook going OOM 😅 

For our production setup I would still like to have some control over memory usage through. The way PM2 allowed us to do this through `--max-memory-restart` was ideal for us; is there any documentation on how we can accomplish this with the workers that next now uses?

**Comment by nicosh** [comment]
@hnsr not sure if this can help, but this is how we  make PM2 to kill processes when respawning : 

**kill_processChild.sh**
```bash
#!/bin/bash

# Find the process IDs of all processes containing the string "processChild.js" in the command path
pids=$(pgrep -f "processChild.js")

# Iterate over each process ID and kill the corresponding process
for pid in $pids; do
    echo "Killing process: $pid"
    kill "$pid"
done
```
**Pm2 ecosystem.config.js** 

```js
module.exports = {
  apps: [
 {
      name: 'main',
      script: 'npm',
      args: 'run app:start:force',
    },
  ],
};

```

and in **package.json** i have this script

`"app:start:force": "./kill_processChild.sh && cd apps/cms && npm run start",
`

In this way pm2 will kill orphan process childs before respawn the application.

**Comment by cjcheshire** [comment]
Has anyone tried 13.4.8 yet?

**Comment by S-YOU** [comment]
No difference on performance so far for 13.4.7 -> 13.4.8 in standalone production mode for me.

**Comment by billnbell** [comment]
Is it better or still running out of memory ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by S-YOU** [comment]
> Is it better or still running out of memory ?

I believe the memory or cpu issue is because of high traffic, and my sites don't have enough traffic to reproduce the issue since the start and also I normally tune application periodically for general performance problems. I am here in this thread just because I am the one who informed 13.4.0 has two jest-worker processes in the [Discussion](https://github.com/vercel/next.js/discussions/49238).

**Comment by DenisBessa** [comment]
I can confirm the problem stil happens 13.4.8.

The weird part is that I cannot reproduce it. It looks just random to me.

**Comment by apoco** [comment]
In case it's of interest, I tried downgrading to 13.3.4 and setting `experimental.appDir` to `true`, and the same problem happens. Of note, this is happening for me when running `next dev`. When I make a change which causes a page or layout to be recompiled, that seems to be what triggers _massive_ amounts of memory consumption for these worker processes (100s of GBs) and then OOM crashes.

Right now the app is running in a stable state at 100GB consumed among the three worker processes. That memory seems to be retained forever.

**Comment by constmoon** [comment]
```
// next.config.js
experimental: {
    appDir: false 
}
```
Fortunately, since it was before using app route, I resolved the issue of excessive processChild.js processes by adding option in `next.config.js` https://github.com/vercel/next.js/issues/49929#issuecomment-1602592624.
I hope the issue is resolved in the next version so that excessive process waste doesn't occur even without using such experimental options.

**Comment by billnbell** [comment]
@constmoon Does this fix the issue on latest Next Versions? Or were you just adding that we should turn if off?

**Comment by constmoon** [comment]
@billnbell  Does this fix the issue on latest Next Versions? Or were you just adding that we should turn if off?

I am using Next.js 13.4.7 and issue was resolved when I added that configuration in that version.
I'm not sure if it applies to the latest version though.

**Comment by avkarenow** [comment]
I had this problem with free account on serv00.com server
reduction of a number of processes helps to run next build.

My `next.config.js`:
```js
/** @type {import('next').NextConfig} */

const nextConfig = {
  experimental: {
    cpus: 1
  }
}
module.exports = nextConfig
```

My version:
next@13.4.9
Node v16.20.0

**Comment by AdamZajler** [comment]
On 13.4.9 problem still exists (server is way more laggy, have to go back to 13.2.4)

**Comment by AdamZajler** [comment]
> The worker process seems to be introduced in this commit: [Fix standalone mode with appDir running in a single proces](https://github.com/vercel/next.js/commit/83b774eeb69f1fe4f636260f83ed98c6d0717a3d#diff-55074c0b0e3d88f7cd3d222e45b05d703b054a99776663e9e95c800bb80fd740)
> 
> This is released in [13.4.0](https://github.com/vercel/next.js/releases/tag/v13.4.0), the last release without the workers is 13.3.4
> 
> Why we are downgrading:
> 
> 1. We had an issue where a process crashed, but the worker wasn't cleaned up. PM2 restarted nextjs several times a second, causing it to eat up 60GB of memory in a few seconds, crashing the server.
> 2. We're currently using pm2 to run the application, but pm2 is unable to report the used memory (which we are trying to use to automatically restart when it is running out).
>    Creating a worker process for the standalone mode seems somewhat odd in my opinion, according to the docs:
>    > Additionally, a minimal server.js file is also output which can be used instead of next start.
>    
>    
>    Using separate worker processes isn't as minimal as it could be. Is there any way to get it 'flat' again @shuding?

Same here on 13.4.9

**Comment by pawelmidur** [comment]
I have a question. Do you enable the next server in `pm2` with the `"exec_mode": "cluster"` configuration? Or as a single process?

**Comment by billnbell** [comment]
I did it as single.

**Comment by iamstuxn3t** [comment]
originally had jest-worker issue, downgraded to ### 13.2.3 as suggested above, jest-woker process is gone. However I am getting a different CPU spike from /.bin/next start as describe here https://github.com/vercel/next.js/discussions/49203

**Comment by timneutkens** [comment]
Since these issues are being confused, this particular issue is about processes being retained after the build exits. It does not refer to running in production and processes being spawned in that case, for production memory usage refer to this issue: #49929. On that issue I wrote down exactly what the 4 processes are: https://github.com/vercel/next.js/issues/49929#issuecomment-1637185156.

**Comment by w7br** [comment]
### The problem also exists in version 13.2.4... I will revert back to version **13.1.6**, as this version was still stable regarding memory leaks, although it was not lighter than **13.1.5**.

It's frustrating not to have the confidence to start a project, as every version that fixes one bug brings dozens of others. There could be a truly stable version.

**Comment by sedlukha** [comment]
still see the problem with 13.4.10 and still too many jest-worker processes

next v.13.2.4
![image](https://github.com/vercel/next.js/assets/14075940/0017cf5a-cda8-4fe2-bf0c-a340f2e9632e)

next v.13.4.10
![image](https://github.com/vercel/next.js/assets/14075940/285e380e-3714-4595-bf0e-035fc1da86b9)

**Comment by S-YOU** [comment]
FYI, latest version (13.4.12) does not spawn jest-worker anymore, but new dedicated processes for each renderer (not sure it is just renamed or not).

- next-router-worker
- next-render-worker-pages

**Comment by billnbell** [comment]
OK lets try it.

**Comment by hanoii** [comment]
The processes rename happened on #52779, I wonder if the new releases fixes the high number of these processes

**Comment by fab1an** [comment]
Is anyone else concerned that these workers all open on all tcp-interfaces instead of just localhost? Meaning that they are exposed to the internet on a standard-VM.

Is this a security risk? My next.js process is started using `/usr/bin/npm run start -- --port=XYZ --hostname=127.0.0.1`, which works for the central service, but the workers just ignore this.

Is this a security risk?

**Comment by sedlukha** [comment]
13.4.12 - still high number of processes and bigger memory load 


13.4.12
![image](https://github.com/vercel/next.js/assets/14075940/0c2a4b58-a446-48c5-9811-1a348afdecde)

13.2.4
![image](https://github.com/vercel/next.js/assets/14075940/b3830b60-bc75-4a1e-a8ab-2549b475d8d3)

**Comment by timneutkens** [comment]
Just re-read every single post in this issue and there's a common topic of sharing screenshots. In order for us to investigate what your application is running into we need access to the code. Without this we can't verify what you're running into as you can understand.

I've posted an update around production memory usage on this issue: https://github.com/vercel/next.js/issues/49929#issuecomment-1649637524. At this point we are fairly certain there is no memory leak in production. We're still working on bringing down the number of processes to 2 instead of 4. We haven't investigated development yet as we've focused on slowdowns first in #48748.

@w7br you're talking about 13.2.4 and 13.1.6. Those versions are from months ago, there have been many optimizations landed since then. Would recommend using the latest version first. Either way please provide access to the application on which you're seeing memory issues so that we can confirm what you're seeing and investigate.

As we've shown in #49929 and #48748 we've dedicated significant engineering time towards investigating and improving these, however, the only way we can do this for memory usage issues is by having access to your code and running it ourselves. 

As you can see in my previous updates on #49929 we had to run the lowest level tools dumping v8 memory allocations to investigate these. For slowdowns luckily we don't need access because you can share a CPU profile, for investigating memory allocation a heap dump is not enough.

**Comment by hnsr** [comment]
Hey @timneutkens, I appreciate all the work in debugging the memory issues.

As you indicated in https://github.com/vercel/next.js/issues/45508#issuecomment-1637831723 this particular issue is about processes being retained after a build exits, as opposed to memory usage issues.

We are currently running into this problem also when `next dev` crashes, or when running in production in standalone mode and the main server.js process crashes (which only happens during some rare issues during startup, like EADDRINUSE, so is probably less relevant).

Do you still need a reproduction case for this lingering worker process problem? I will be happy to see if I can provide one.

**Comment by hanoii** [comment]
@timneutkens I am on the same boat as @hnsr, anytime the `next build` fails for any reason, starting the server (even in the command line with `npm start` fails with something like: `Error: Could not find a production build in the '/app/.next' directory.` (In my case the build is now currently failing because of #53086) but it failed for many other reasons before as this is part of a deploy process.

To make this worst, I am using `pm2` that tries to restart the app frequently so it quickly ends up with a lot of worker processes and they are doing something, using memory and everything. Is like the worker thread lose its parent process so eventhough npm start finishes with error the process sticks.

**Comment by timneutkens** [comment]
> Do you still need a reproduction case for this lingering worker process problem? I will be happy to see if I can provide one.

This would be helpful indeed if you're able to provide that, saves me significant amounts of time trying to figure out how this is being run into. I guess the "next start without a build" case @hanoii is talking about is a good start if that reproduces though 👍

**Comment by timneutkens** [comment]
I just checked with @ijjk and as it turns out he saw something similar and fixed it in a recent refactor: https://github.com/vercel/next.js/blob/46677ccda6a62203d7a7ae359c1020780aeccee5/packages/next/src/server/lib/router-server.ts#L247-L262. Could you try with `next@canary`?

**Comment by hanoii** [comment]
@timneutkens I tried it locally as I was able to reproduce it as well and yes, next@canary at least doesn't leave the process in a straight out start fail:

I am getting a different error:

`[Error: ENOENT: no such file or directory, open '/var/www/html/next/.next/BUILD_ID'] {`

but I guess that's ok.

Maybe this fixes it.

**Comment by sedlukha** [comment]
@timneutkens 
> Also please make it clear what you're running. I.e. @sedlukha is that development? I guess so?

No, this is prod. I run it for **17 apps**.

And i've tried canary, now even worse memory usage, **4.9G** (13.4.13-canary.6) vs **2.4G** (v13.2.4) vs **3.16G** (v13.4.12)

![image](https://github.com/vercel/next.js/assets/14075940/a38cc496-ae88-4321-9ab5-cb1000212623)

**Comment by sedlukha** [comment]
@timneutkens it seems that experimental.appDir: false might disable next-render-worker-app and solve the problem for those, who use only pages routing.

I would be happy to test it, but I can't do it on my real apps because of next issue
https://github.com/vercel/next.js/issues/52875

**Comment by timneutkens** [comment]
Seems what you're reporting is exactly the same as #49929 in which I've already explained the memory usage, there is no leak, it's just using multiple processes and we're working on optimizing that: https://github.com/vercel/next.js/issues/49929#issuecomment-1637185156

Setting `appDir: false` is not supported and that option will go away in a future version, we just haven't gotten around to removing the feature flag.

---

@hanoii thanks for checking 👍

**Comment by Nirmal1992** [comment]
Same here.. my macbook crashed when I used Nextjs latest with turbo repo..  multiple child processes were running in the background even after terminating the server...

**Comment by S-YOU** [comment]
FYI: experimental: {appDir: false} does not work anymore on 13.4.13 for me (page rendered, but url changes failed to load json and triggering ssr), and now become next 3 processes apart from main process.
- next-router-worker
- next-render-worker-app
- next-render-worker-pages

**Comment by timneutkens** [comment]
@Nirmal1992 @S-YOU @space1worm I'm surprised you did not read my previous comment. I thought it was clear that these types of comments are not constructive? https://github.com/vercel/next.js/issues/45508#issuecomment-1653226340

@space1worm I'm even more surprised you're posting "same issue" without trying the latest version of Next.js...

**Comment by space1worm** [comment]
@timneutkens  Hey, yeah sorry I missed it, here I made my test repo public. 

You can check this commit [tracer](https://gitlab.cern.ch/nzurashv/tracer/-/commit/c2aee3dddf98e445a421c5125cc2fb945cebf1b8)

I had memory usage problem on version 13.4.8 for some reason, after navigating on any page my pod's memory would skyrocket for some reason... and after that whole app was braking an becoming unresponsive.

Here as a refference

<img width="1116" alt="Screenshot 2023-08-09 at 20 38 59" src="https://github.com/vercel/next.js/assets/84189246/53828d95-0e21-42ed-988c-bf14d3fb8612">

**Comment by timneutkens** [comment]
Application is still not using the latest version of Next.js, same in the commit linked: https://gitlab.cern.ch/nzurashv/tracer/-/blob/master/package-lock.json#L4673

**Comment by space1worm** [comment]
@timneutkens  I have updated to latest version, created new branch [tracer/test](https://gitlab.cern.ch/nzurashv/tracer/-/tree/test)

Issue still persist

here you can check this link as well

[tracer-test.web.cern.ch](https://nextjs-test2.web.cern.ch/)

<img width="1064" alt="Screenshot 2023-08-09 at 21 17 07" src="https://github.com/vercel/next.js/assets/84189246/591e67da-4d92-4e43-9da4-11e6da535b36">
<img width="1388" alt="Screenshot 2023-08-09 at 21 17 14" src="https://github.com/vercel/next.js/assets/84189246/38198940-a2bc-4d99-87b4-aeb863ec98a1">

**Comment by glaustino** [comment]
> FYI: experimental: {appDir: false} does not work anymore on 13.4.13 for me (page rendered, but url changes failed to load json and triggering ssr), and now spawning 3 processes apart from main process.
> 
> * `next-router-worker`
> * `next-render-worker-app`
> * `next-render-worker-pages`

I have a question about these child processes, currently it seems they open random ports which broke my application behind WAF in Azure, this happened because we only open certain ports. Is there anyway for me to force the ports these child processes are going to use at all? I am on the latest next release

**Comment by jrscholey** [comment]
FYI: With 13.4.11 we were unable to start our app in Kubernetes. We received a spawn process E2BIG from jest-worker. This only happened when our rewrites were above a certain length (although still below max).

Downgrading back to 13.2.4 resolved the issue.

**Comment by S-YOU** [comment]
FYI: now main process started with `node server.js` is gone in Next.js 13.4.15, and `next-router-worker`'s parent PID become 1 (init). This could probably use less memory since It has one less process.

```
1362416       1      00:00:02 next-router-worker
1362432 1362416      00:00:00 next-render-worker-app
1362433 1362416      00:00:05 next-render-worker-pages
```

**Comment by S-YOU** [comment]
@timneutkens, sorry, I probably misread it. I do not mean to claim or anything. I am just sharing what I've observed in the version I am using (which supposed to be latest release).

**Comment by timneutkens** [comment]
In 13.4.15 (but really upgrade to 13.4.16 instead) this PR has landed to remove one of the processes indeed: https://github.com/vercel/next.js/pull/53523

**Comment by sladg** [comment]
Experiencing same. Version 13.4.4

<img width="1437" alt="image" src="https://github.com/vercel/next.js/assets/26263265/46f84d46-a86d-4286-9682-b8c06bba2573">

**Comment by timneutkens** [comment]
@sladg is this a joke?

**Comment by timneutkens** [comment]
It's entirely unclear what you're running / filtering by, e.g. you're filtering by `next-` but `13.2.4` doesn't set process.title to anything specific.

Sharing screenshots is really not useful, I keep having to repeat that in every single comment around these memory issues.

Please share code, I can't do anything to help you otherwise.

**Comment by billnbell** [comment]
> @timneutkens I've tried [v13.4.20-canary.2](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.2).
> 
> It was expected that #53523 and #54143 would reduce the number of processes, resulting in lower memory usage.
> 
> Yes, the number of processes has been reduced; after the update, I see only two processes. However, memory usage is still higher than it was with v.13.2.4.
> 
> node v.16.18.1 (if it matters)
> 
> v13.4.20-canary.2 ![image](https://user-images.githubusercontent.com/14075940/262681408-4b5f6b27-62b2-4110-92ec-b913bb335743.png)
> 
> 13.2.4 ![image](https://user-images.githubusercontent.com/14075940/255425887-b3830b60-bc75-4a1e-a8ab-2549b475d8d3.png)

The memory looks stable - but it is really hard to see anything in the screen shots.

**Comment by magalhas** [comment]
I'm seeing this behaviour running `next dev` starting on 13.3 and newer versions (13.4 included). This isn't happening on 13.2. Somehow this looks like it's happening whenever files are being added/removed from the FS while the dev script is running.

**Comment by timneutkens** [comment]
I'm amazed by how often my comments are flat out ignored the past few weeks on various issues. We won't be able to investigate/help based on comments saying the equivalent of "It's happening". Please share code, I can't do anything to help you otherwise.

I'll have to close this issue when there is one more comment without a reproduction as I've checked multiple times now and the processes are cleaned up correctly in the latest version.

**Comment by magalhas** [comment]
By latest version you mean the latest RC @timneutkens ?
