### ISSUE TITLE
Error occurs in @next/font when setting up a monorepo using yarn berry (pnp) and yarn workspace.

### ISSUE THREAD

**Issue by badjfas** [vercel/next.js#45606]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.19.0
      npm: 8.19.2
      Yarn: 3.4.1
      pnpm: N/A
    Relevant packages:
      next: 13.1.7-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (@next/font)

### Link to the code that reproduces this issue

https://github.com/badjfas/next-font-issue

### To Reproduce

1. yarn install

2. yarn workspace c dev

3. dev server start "localhost:3000"

4. error.... 

<img width="976" alt="image" src="https://user-images.githubusercontent.com/51310757/216923319-c31df237-79d2-4f17-9c7c-c9374303cb72.png">

### Describe the Bug

An error has occurred saying that the dependency of "@next/font" could not be found in Next.js.

### Expected Behavior

.

### Which browser are you using? (if relevant)

chrome

**Comment by WCByrne** [comment]
I am seeing the same thing and commented on [this issue](https://github.com/vercel/next.js/issues/44462) last week, initially thinking it was related. 

I rated a project from the starter and it worked fine until I set up workspaces. The failing project can be found [here](https://github.com/WCByrne/next-test).

**Comment by Adelrisk** [comment]
@WCByrne I shoud your issues and have a workaround: install the package at the top level of your monorepo as a dev dependency.

```bash
yarn add @next/font -D
```

Worked for me! I've had worse work-arounds.

**Comment by WCByrne** [comment]
Badda Bing! Thank you, that worked.

**Comment by badjfas** [comment]
@Adelrisk  thank you !!!!

**Comment by Adelrisk** [comment]
Wonderful that this problem is fixed. In which version could we hope to see the fix? I don't mind tracking the commit myself.

**Comment by lucasriondel** [comment]
@Adelrisk installing it at the top level of my turborepo monorepo did not fix the issue for me

**Comment by Adelrisk** [comment]
@lucasriondel You probably need to merge the following into your `.yarnrc.yml` as in this [similar issue](https://github.com/styled-components/styled-components/issues/3082#issuecomment-606641463)

```yaml
packageExtensions:
  "@next/font@*":
    dependencies:
      next: "*"
```

See [the docs](https://yarnpkg.com/configuration/yarnrc#packageExtensions) for further explanations.

Yarn is much stricter when resolving dependencies, and this package `@next/font` includes magic/hacks to work. Which is why my help is only a workaround for a buggy system. This issue is not actually resolved OP @badjfas

**Comment by legion151** [comment]
Well as I understood @Adelrisk 's WORKAROUND isn't a FIX as he made clear...

**Comment by lucasriondel** [comment]
> @lucasriondel You probably need to merge the following into your `.yarnrc.yml` as in this [similar issue](https://github.com/styled-components/styled-components/issues/3082#issuecomment-606641463)
> 
> ```yaml
> packageExtensions:
>   "@next/font@*":
>     dependencies:
>       next: "*"
> ```
> 
> See [the docs](https://yarnpkg.com/configuration/yarnrc#packageExtensions) for further explanations.
> 
> Yarn is much stricter when resolving dependencies, and this package `@next/font` includes magic/hacks to work. Which is why my help is only a workaround for a buggy system. This issue is not actually resolved OP @badjfas 

Thank you for your answer, but I am using npm, not yarn. I do not know if that makes a big difference. My fix was to actually download the font and use them locally as static fonts.

**Comment by caelinsutch** [comment]
I'm still running into this issue even after both workarounds (editing `.yarnrc.yml` and installing with -D at root of monorepo
