### ISSUE TITLE
FOUC with TailwindCSS and NextJs 13

### ISSUE THREAD

**Issue by kevinlowe0x3F7** [vercel/next.js#46510]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 19.6.1
      npm: 9.4.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-yxetxb?file=app%2Fpage.tsx

### To Reproduce

1. Navigate to app/page.tsx once the dev command is running
2. Try changing the Hello World text. On rerender it will inconsistently show a FOUC. It may require several tries

### Describe the Bug

Split second of white screen and unstyled content while iterating in dev. The StackBlitz should be a pretty minimal Tailwind + NextJS project setup. 

### Expected Behavior

No FOUC

### Which browser are you using? (if relevant)

Chrome 109.0.5414.119 (Official Build) (x86_64)

**Comment by unbelivr** [comment]
same issue https://github.com/vercel/next.js/issues/46197

**Comment by geotrev** [comment]
You beat me to the punch.

This happens for normal CSS modules too. The issue is being discussed at some length in the [app dir discussion thread](https://github.com/vercel/next.js/discussions/41745#discussioncomment-5106716).

[Here's a simple reproduction](https://stackblitz.com/edit/vercel-next-js-mtml7p?file=app%2Fabout%2Fpage.tsx) with a colocated CSS file (navigate to /about and the h1 on subsequent page should initially render in its default size, then pop into the size defined in the stylesheet).

**Comment by timfee** [comment]
Also see https://github.com/vercel/next.js/issues/46947 :)

**Comment by abusada** [comment]
Hello there, facing the same issue did anyone figure out how to solve it?
I'm using appDirectory

**Comment by medonat** [comment]
We also have this issue.

**Comment by tangochris** [comment]
Hi, below is a video of our FOUC. It causes a CLS of **0.703** (!).

We're using app directory and tailwindcss.

So hey, it's my fault for telling our dev team to go ahead and use Next 13 with all the new features. I'm the business guy and I shouldn't have. I thought the new Next 13 features would be stable by now.

But now, 6 months later, we're ready to launch, and the whole reason we went with NextJS — fantastic performance and scores on Core Web Vitals — is not a reason at all.

I'm trying to make a decision on whether to spend 10-20 hours to stop using app directory and go back to the old way, or whether this issue will happen to get fixed in a release in the next couple of weeks. Does anyone know?

https://user-images.githubusercontent.com/19203848/233195350-5c145b98-56ef-4051-89b6-27d308f941af.mov

**Comment by nickwild-999** [comment]
Yes happening for me too

**Comment by tangochris** [comment]
For me, this issue is resolved in NextJS 13.3.1. CLS now 0.033. Yay!

**Comment by geotrev** [comment]
Confirmed this issue is fixed as well after updating to v13.3.1. 🤝

**Comment by nickwild-999** [comment]
Worked for me too. Thanks for the heads up

**Comment by shuding** [comment]
This issue is fixed in recent versions with a test add in #47708.

**Comment by ImraKocis** [comment]
FOUC still present on Firefox for me

**Environment information**

I am using `pages/_app.tsx`

```
"next": "^13.3.1",
"react": "^18.2.0",
"tailwindcss": "3.2.4",
```

**Problem description**

FOUC is only present on Firefox browser. I can notice it only on fonts, I'm using next/font google font's along side with tailwind css.

I can show some code if needed

**Comment by john-whiting** [comment]
I am also having the FOUC issue only on the Firefox browser. Testing against Chrome shows no FOUC. Mine is with tailwind styling too, and not just fonts.

```
    "next": "13.4.2",
    "postcss": "8.4.23",
    "react": "18.2.0",
    "tailwindcss": "3.3.2",
```
