### ISSUE TITLE
Prefetching and client side navigation not working coreclty

### ISSUE THREAD

**Issue by mitjapotocin** [vercel/next.js#47516]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.4.0
      npm: 9.2.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/mitjapotocin/NextJS-LinkTest

### To Reproduce

The example app in the GH repo has branches with different next versions used.
To reproduce the bug use branch `next-13.2.4` or `next-canary`. Build and start the app.

Hover over the link and observe, that the prefetched `json` has an empty object instead of the props. 

Branch `next-12.2` has a working example (the only difference is the next version)

Do mind that the app is using `middleware` maybe that is causing the issue, but it worked on `next@12.2`

### Describe the Bug

When hovering over a link for the page that has `getServerSideProps` props get prefetched and `test.json` should contain the props, but it only has an empty object `{}` and when navigating to that page, the props on the page are also wrong every other time. See the video.

https://user-images.githubusercontent.com/36345162/227701941-4bd63b9e-5d8b-41c0-b363-11df6b5e2af7.mov

### Expected Behavior

When hovering over a link the server-side props should be prefetched as they did in version `12` and when navigationg to the page the props should be correct.

https://user-images.githubusercontent.com/36345162/227702140-691a672d-541d-454d-b7a5-296d292fd051.mov

### How are you deploying your application? (if relevant)

next start

**Comment by BBugala** [comment]
It might be connected to middleware, I am experiencing a similar issue.

**Comment by bartekbugala** [comment]
The middleware seems to break on prefetch (menu / link)
Try adding this to middleware, maybe it'll help
```
 const reqHeaders = new Headers(req.headers)
    const purpose = reqHeaders.get('purpose')
    if (purpose && purpose.match(/prefetch/i)) {
      await reqHeaders.delete('x-middleware-prefetch') // empty json bugfix
    }
```
Then depending on the middleware setup:
```
response = NextResponse.next({
      request: {
        headers: reqHeaders,
      },
    })
    return response
```

**Comment by bartekbugala** [comment]
A possible workaround... ?

On an earlier next version the workaround for me seems to work:
```
const reqHeaders = new Headers(req.headers)
const purpose = reqHeaders.get('purpose')
const isPrefetch = purpose && purpose.match(/prefetch/i)
if (isPrefetch) {
      // console.log('before', reqHeaders)
      reqHeaders.delete('x-middleware-prefetch') // empty json bugfix (in the browser headers still show, but here it is gone)
      // console.log('after', reqHeaders)
    }
```
Then
`return NextResponse.next({request: {headers: reqHeaders}})`

**Comment by paales** [comment]
I can confirm that @bartekbugala's solution works.

We ran into this issue because we implemented https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale

**Comment by pk936** [comment]
Alternative to @bartekbugala solution, we can add the following code in next.config.js

```
const allPathsIncludingRoot = "/:path*{/}?";

async headers() {
    return [
      // if the header `x-middleware-prefetch` is present,
      // the `Cache-Control: no-cache` header will be applied
      {
        source: allPathsIncludingRoot,
        has: [
          {
            type: "header",
            key: "x-middleware-prefetch",
          },
        ],
        headers: [
          {
            key: "Cache-Control",
            value: "no-cache",
          },
        ],
      },

      // if the header `x-middleware-prefetch` is not present,
      // the `Cache-Control: public, max-age=300` header will be applied
      {
        source: allPathsIncludingRoot,
        missing: [
          {
            type: "header",
            key: "x-middleware-prefetch",
          },
        ],
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=300",
          },
        ],
      },
    ];
  },```

**Comment by irfancoder** [comment]
@pk936 's solution works great. Faced this issue after implementing the middleware, and some of `getServerSideProps` pages occasionally returns empty `pageProps`. Pretty frustrating when debugging, because it only happens in production.

**Comment by remorses** [comment]
I think removing this line would solve this issue
https://github.com/vercel/next.js/blob/928c4c097c2fd160715acecbec6bed30eda162c8/packages/next/src/server/base-server.ts#L1613-L1618

I think the real problem is that routes with `getServerSideProps` should not be prefetched, but that's harder to debug why it happens

**Comment by remorses** [comment]
This issue may have been fixed by https://github.com/vercel/next.js/pull/54732, if you host Next.js with a CDN like Cloudflare in front it would cache the prefetch requests

**Comment by xdamman** [comment]
I'm still running into this issue with nextjs 14.0.4.

The issue seems to be related to the rewrites rules in `next.config.js`. It seems that their behavior has changed.

What I used to have:

```js
  async rewrites() {
    return [
      {
        has: [
          {
            type: "host",
            value: "(?<host>.*)",
          },
        ],
        source: "/",
        destination: "/:host",
      },
      {
        has: [
          {
            type: "host",
            value: "(?<host>.*)",
          },
        ],
        source: "/:path*",
        destination: "/:host/:path*",
      },
    ];
  },
```

It used to work just fine with nextjs 12.3.1, but not anymore. This is now preventing the loading of the json file for client-side rendering (not sure which version broke this between 12.3.1 and 14.0.4). Adding a new rule to exclude `/_next/*` did the trick:

```js
  async rewrites() {
    return [
      {
        has: [
          {
            type: "host",
            value: "(?<host>.*)",
          },
        ],
        source: "/_next/:path*",
        destination: "/_next/:path*",
      },
      {
        has: [
          {
            type: "host",
            value: "(?<host>.*)",
          },
        ],
        source: "/",
        destination: "/:host",
      },
      {
        has: [
          {
            type: "host",
            value: "(?<host>.*)",
          },
        ],
        source: "/:path*",
        destination: "/:host/:path*",
      },
    ];
  },
```

**Comment by malaville** [comment]
Hello we are still having the issue in 14.0.3. I don't understand entirely the solution of @bartekbugala, but I confirm that the fix  #54732 is likely not to work considering that we have the problem on static pages prefetching. It seems possible to me that generating static pages on-the-fly might be possible... but we are witnessing the problem on "fallback: blocking" pages. I don't know if prefetches cares about "fallback: blocking".

**Comment by Lezzio** [comment]
I found this solution to work in our case:
This requires in `next.config.js`:
- the `DefinePlugin` to replace the `BUILD_ID` variable with Next.js' buildId
- `skipMiddlewareUrlNormalize` set to true

This helps the client to eventually force refresh its JavaScript and aligns the version again for smooth experience and client-server communication

```
export const middleware = (req: NextRequest): NextResponse | void => {
  if (req.nextUrl.buildId && req.nextUrl.buildId !== process.env.BUILD_ID) {

    return NextResponse.json(
      { message: 'client version outdated, propagate exception to the client to force refresh' },
      { status: 500 }
    )
  }
 // ...
}
```

Since this is a version skew problem, there is a few options among:
- Backward compatibility, which is isn't supported by the default build system
- Force the client to update/refresh which seems to work with the snippet above (let's improve it ?)
