### ISSUE TITLE
GitHub Pages <Link href="/"> goes to  to <user-name>.github.io/<repo-name>.txt 

### ISSUE THREAD

**Issue by JoostGevaert** [vercel/next.js#48414]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.7
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

github-pages

### What browser are you using? (if relevant)

I tested it in Chrome, Edge and Brave

### How are you deploying your application? (if relevant)

to GitHub Pages with npm run deploy

### Describe the Bug

I can't get back home 😟

The <Link href="/"> on the About page leads to <user-name>.github.io/<repo-name>.txt (see image below).

![image](https://user-images.githubusercontent.com/50735562/232203058-4a5170f8-aa2e-41a9-965e-7b11418480b5.png)

When hovering over that link, the url displayed in the bottom left hand corner does seem correct (see image below).

![image](https://user-images.githubusercontent.com/50735562/232203029-8f9a4676-6dd7-4917-a712-48895a539e05.png)

### Expected Behavior

Bring me back home when I click the home link

### To Reproduce

Deploy the github-pages example

**Comment by ciruz** [comment]
Can confirm this issue:
https://ciruz.github.io/gh-pages-test/about

https://github.com/ciruz/gh-pages-test/blob/main/app/about/page.tsx

**Comment by hariria** [comment]
Any updates on this? For me personally I noticed this is happening on Next.js 13, with the app directory enabled, and `output: 'export'` turned on. When I don't export it as a static page, it doesn't have this issue. Now, all of a sudden, all links are linking to PATHNAME.txt instead of just PATHNAME. (ie. `/docs` links to `/docs.txt`) Cc @rauchg @leerob

**Comment by Geo-W** [comment]
even though I changed it to <a href="/" />  it still navigates to that txt page

**Comment by dscafati** [comment]
This is fixed at least on 13.4.7, could you all please check that?

**Comment by yacine-karim** [comment]
I just tested with the version 13.4.7, and still facing the same issue, any updates?

**Comment by 0xadada** [comment]
> This is fixed at least on 13.4.7, could you all please check that?

i'm on `14.1.0` and still see it https://github.com/0xadada/0xadada.pub [website](https://0xadada.pub)
