### ISSUE TITLE
File based metadata broken on Windows

### ISSUE THREAD

**Issue by LuudJanssen** [vercel/next.js#48470]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Education
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.8
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js), Operating System (Windows, MacOS, Linux)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/gracious-ramanujan-gxyzsh?file=%2FREADME.md

### To Reproduce

Run the reproduction example on Windows, or create a new reproduction environment and add a `sitemap.ts` file that returns anything. Start the dev server and go to `localhost:3000/sitemap.xml`.

### Describe the Bug

In the `v13.3.1` canary releases the file based metadata seems to be broken on Windows. `v13.3.0` seems to be working, but has other Windows related bugs. Instead of showing the Sitemap contents it shows an error page.

Also doesn't seem to work for static files, so a `app/robots.txt` also won't show up.

### Expected Behavior

Shows the sitemap (or other file based metadata) contents.

**Comment by XEngine** [comment]
Somehow nextjs makes everything harder for other environments but macOS. 13.3.0 has windows path issues now it's fixed in the canaries yet canary has other windows path issues. I think Vercel should buy a desktop PC for testing 😆

**Comment by XEngine** [comment]
https://github.com/vercel/next.js/blame/a92c5465cac0a123eee2a8086dbfff8482d811b8/packages/next/src/lib/metadata/get-metadata-route.ts#L57-L62

in these lines it generates : 
\icon\[[...__metadata_id__]]\route
\sitemap.xml\route

for icon.js and sitemap.js. When I put ```route = route.replace(/\\/g, "/");``` at the end, everything works fine but I don't really sure this is the fix. It may brake the mac env and maybe break a lot more. So I will silently fix this inside my node_modules and wait a PR from an author because I don't fully know enough nextjs to create a PR

**Comment by huozhi** [comment]
Should be fixed by #48779

**Comment by arialpew** [comment]
I don't think it's fixed, there's another problem that surface (at least on my configuration).

See https://github.com/vercel/next.js/issues/48921#issuecomment-1528746751
