### ISSUE TITLE
ISR generated dynamic pages doesn't scroll to top on route change

### ISSUE THREAD

**Issue by Farhaan9082** [vercel/next.js#48868]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Don't have my PC right now
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Farhaan9082/personal-website

### To Reproduce

https://farhaan.vercel.app
In the above site, go to work in navbar to /projects and then click on any 1 project, it persists the scroll position while moving to projects/{id}

### Describe the Bug

ISR generated dynamic pages on production persists scroll position on route change

### Expected Behavior

Should scroll to top of the page on route change

### Which browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

Vercel

**Comment by nowseemee** [comment]
@feedthejim https://github.com/vercel/next.js/pull/48346#discussion_r1174382874

**Comment by nowseemee** [comment]
this is fixed in the latest canary release 🎉

**Comment by Gawdfrey** [comment]
I am still experiencing this issue in the pages directory, even with the latest canary release.

**Comment by liho00** [comment]
me too

**Comment by timneutkens** [comment]
In the App Router we've completely reworked how scrolling on navigation and on back navigation is applied to solve the longstanding issues `pages` had around this. I'm going to close this issue as it was confirmed the changes work and the reproduction is no longer available.
