### ISSUE TITLE
Package subpath './server.edge' is not defined by "exports"

### ISSUE THREAD

**Issue by medonat** [vercel/next.js#48948]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.18.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.12
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/medonat/nextjs-revalidate-test

### To Reproduce

1. Clone the repository
2. npm install
3. npm run build
4. npm run start
5. Open localhost:3000
6. The cat fact shouldn't change onreload
7. Make a POST request: localhost:3000/api/revalidate
8. There should be an error 500 and no update if you reload localhost:3000 
9. Checkout branch 13.3.0 - and repeat the procedure to see that it worked in 13.3.0

### Describe the Bug

ISR does not work. Stale data is displayed after calling revalidate.

Error in console:
`TypeError: Cannot set properties of undefined (setting 'current')
    at ue (C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:113:42)
    at C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:151:127
    at new Promise (<anonymous>)
    at Object.exports.renderToReadableStream (C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:151:53)
    at C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\server\node-web-streams-helper.js:195:117
    at NextTracerImpl.trace (C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\server\lib\trace\tracer.js:86:20)     
    at renderToInitialStream (C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\server\node-web-streams-helper.js:195:37)
    at C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\server\app-render\app-render.js:918:92`

### Expected Behavior

Revalidate should work like it did in previous versions (e.g. 13.3.0)

### How are you deploying your application? (if relevant)

next start

**Comment by LotharVM** [comment]
Facing the exact the same issue here. Any update on this @timneutkens ?

**Comment by Djboy08** [comment]
I get the same issue

**Comment by xFoolCode** [comment]
Can confirm ,
Got the same issue on my local machine
```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A
    Binaries:
      Node: 19.9.0
      npm: 9.6.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.4
      eslint-config-next: 13.3.4
      react: 18.2.0
      react-dom: 18.2.0
```
```
TypeError: Cannot set properties of undefined (setting 'current')
    at ue (/home/thegreatlogician/Projects/app-next/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:113:42)
    at /home/thegreatlogician/Projects/app-next/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:151:127
    at new Promise (<anonymous>)
    at exports.renderToReadableStream (/home/thegreatlogician/Projects/app-next/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:151:53)
    at /home/thegreatlogician/Projects/app-next/node_modules/next/dist/server/node-web-streams-helper.js:195:117
    at NextTracerImpl.trace (/home/thegreatlogician/Projects/app-next/node_modules/next/dist/server/lib/trace/tracer.js:86:20)
    at renderToInitialStream (/home/thegreatlogician/Projects/app-next/node_modules/next/dist/server/node-web-streams-helper.js:195:37)
    at /home/thegreatlogician/Projects/app-next/node_modules/next/dist/server/app-render/app-render.js:937:92
```

**Comment by shuding** [comment]
Thanks, I've identified the cause and am working on a fix right now.

**Comment by khuezy** [comment]
Was hoping canary.4 would fix it but it didn't :(

**Comment by khuezy** [comment]
@shuding can you reopen the ticket please, the latest canary:
```
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /var/task/node_modules/react-dom/package.json
```

**Comment by karlhorky** [comment]
Yeah I'm also seeing this `Error: Package subpath './server.edge' is not defined by "exports"` with `next@13.3.5-canary.6` in a monorepo which has other packages using non-experimental `react-dom` versions (maybe this `18.2.0` below is the version from those other packages?)

@shuding should we open a new issue to track this?

```bash
$ cat node_modules/react-dom/p
ackage.json
{
  "name": "react-dom",
  "version": "18.2.0",
  "description": "React package for working with the DOM.",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/react.git",
    "directory": "packages/react-dom"
  },
  "keywords": [
    "react"
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/facebook/react/issues"
  },
  "homepage": "https://reactjs.org/",
  "dependencies": {
    "loose-envify": "^1.1.0",
    "scheduler": "^0.23.0"
  },
  "peerDependencies": {
    "react": "^18.2.0"
  },
  "files": [
    "LICENSE",
    "README.md",
    "index.js",
    "client.js",
    "profiling.js",
    "server.js",
    "server.browser.js",
    "server.node.js",
    "test-utils.js",
    "cjs/",
    "umd/"
  ],
  "exports": {
    ".": "./index.js",
    "./client": "./client.js",
    "./server": {
      "deno": "./server.browser.js",
      "worker": "./server.browser.js",
      "browser": "./server.browser.js",
      "default": "./server.node.js"
    },
    "./server.browser": "./server.browser.js",
    "./server.node": "./server.node.js",
    "./profiling": "./profiling.js",
    "./test-utils": "./test-utils.js",
    "./package.json": "./package.json"
  },
  "browser": {
    "./server.js": "./server.browser.js"
  },
  "browserify": {
    "transform": [
      "loose-envify"
    ]
  }
}
```

**Comment by khuezy** [comment]
@karlhorky Can you open a ticket please? I think it warrants a new one since it's different than the original ticket. Thanks.

**Comment by karlhorky** [comment]
It's the same error message that you posted above.

**Comment by karlhorky** [comment]
@shuding here's a repro, seems like it's affecting custom servers:

CodeSandbox Demo: https://codesandbox.io/p/sandbox/heuristic-aryabhata-7ce33w?file=%2Fserver.mjs

**Comment by karlhorky** [comment]
I can confirm `next@13.3.5-canary.8` is working with custom servers 🎉 Thanks @shuding !!

CodeSandbox: https://codesandbox.io/p/sandbox/quirky-bell-o5tl8l?file=%2Fserver.mjs

![Screenshot 2023-05-04 at 11 42 39](https://user-images.githubusercontent.com/1935696/236169510-4e397f00-8522-4024-ba60-2b227f89f674.png)

**Comment by klarstrup** [comment]
Seeing this error with a standalone server on `next@13.3.5-canary.9` :[

**Comment by daszkowski** [comment]
Have same error (for next@13.4.0) - Package subpath './server.edge' is not defined by "exports" - for On-demand Revalidation using res.revalidate([url])

**Comment by LotharVM** [comment]
Also still facing this issue with 13.4.0:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /Users/user/Documents/folder/client/frontend/node_modules/react-dom/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:729:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at /Users/user/Documents/folder/client/frontend/node_modules/next/dist/server/require-hook.js:180:36
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Error: Invalid response 500
    at NextNodeServer.revalidate (/Users/lothar-bravoure/Documents/folder/client/frontend/node_modules/next/dist/server/next-server.js:1208:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.<anonymous> (/Users/user/Documents/folder/client/frontend/node_modules/next/dist/server/lib/server-ipc/index.js:54:30)
```

**Comment by briankulp** [comment]
Running into the same issue on `13.4.1` with the `output: 'standalone'` setting as well.

**Comment by berekuk** [comment]
I had this issue on `13.4.0` when I deployed on Vercel (local `next dev` was fine). I didn't use `output: 'standalone'` or revalidation.

Removing `react` and `react-dom` (18.2.0) from explicit dependencies in `package.json` helped.

**Comment by jwalcher** [comment]
the error persists for in 13.4.2, both local and self-hosted. Do we reopen the ticket @shuding or create a new one?

**Comment by shuding** [comment]
@jwalcher opening a new one with a minimal reproduction repo will definitely help, thanks!

**Comment by jwalcher** [comment]
I tried around a bit, and in my current setup the error only appears when the revalidation path gets rewritten by middleware. However, I am still calling res.revalidate from api route instead of using route handler in app directory. If the error persists after complete migration, I will post a new report. Thanks!

**Comment by jwalcher** [comment]
Whoever is still following this: The new `revalidatePath` function from `next/cache` to be used in route handlers in the app directory does not work for me on dynamically generated routes, and fails to rebuild the page at the first refresh even on static routes. 

@shuding: I have opened an issue https://github.com/vercel/next.js/issues/49955 reporting the problems with `res.revalidate` through middleware, and those with `revalidatePath` for dynamically generated routes. 

Minimal code is at https://github.com/jwalcher/revalidation

**Comment by jwalcher** [comment]
> @jwalcher opening a new one with a minimal reproduction repo will definitely help, thanks!

@shuding  Please could someone take another look at this, perhaps through the issue https://github.com/vercel/next.js/issues/50464

The `Package subpath './server.edge' is not defined by "exports"` error persists during on-demand revalidation when the `middleware-invoke` flag is set on a path in the `app` directory (without middleware getting invoked per se during revalidation). This might well be a router issue, but it might also arise later during re-render.
