### ISSUE TITLE
[NEXT-1157] deploying NextJS 13 `appDir` site to Digital Ocean App platform, Direct link opening doesn't work.

### ISSUE THREAD

**Issue by dhruvilxcode** [vercel/next.js#49130]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 9.6.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.4
      eslint-config-next: 13.3.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

github.com/dhruvilxcode/eshop

### To Reproduce

Deploy the NextJS site to Digital Ocean App Platform or any host. 
then access the any sub page such as Login page by accessing URL directly, not by Link component (because that works well)

### Describe the Bug

When i access url let's say Login page, by this domain.com/login/ then it's not loading, instead it showing this (refer to linked image).
![Screenshot 2023-05-03 at 12 13 16 PM](https://user-images.githubusercontent.com/60258514/235849054-b43d4986-db5f-48e3-b69d-b14a438d4752.png)

### Expected Behavior

A page should render by accessing it's URL.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Digital Ocean App Platform

<sub>[NEXT-1157](https://linear.app/vercel/issue/NEXT-1157/deploying-nextjs-13-appdir-site-to-digital-ocean-app-platform-direct)</sub>

**Comment by dhruvilxcode** [comment]
For now, i downgraded the next version to `13.2` and It worked well.

`npm i next@13.2`

**Comment by HamAndRock** [comment]
Is there a CDN involved? Got the same weird RSC payload like you did when we started using CDN on a project:

https://github.com/vercel/next.js/pull/49140

**Comment by Fredkiss3** [comment]
One potential solution (for cloudfare) : https://github.com/vercel/next.js/issues/48569#issuecomment-1518887170

**Comment by conor909** [comment]
Same issue here deploying to firebase, I thought it was [a firebase issue](https://github.com/firebase/firebase-tools/issues/5756) but it seems to be a `next` thing.  Upgrading to the latest canary version seemed to work yesterday, but the issue is back now somehow.  I'm lost.

**Comment by dhruvilxcode** [comment]
@conor909 downgrade next version to 13.2, and check.
it might work for you as well, as it worked for me.

**Comment by conor909** [comment]
I know my issue could be different, being on Firebase, but I've just deployed successfully using a local node 16 environment, when I use `18` it fails with the NextJS error `Error: > Couldn't find a `pages` directory. Please create one under the project root`

I'm using `next: 13.3.5-canary.3`

**Comment by dhruvilxcode** [comment]
@timneutkens not changed any settings on Digital Ocean app Platform. currently I downgraded next version to 13.2 and it works well on same.

sorry I can't push my website with the latest version. One thing is sure I settled up the server correctly.

**Comment by Livog** [comment]
I experienced the same issue with my Next.js 13 app when using Cloudflare in front of it. I realized that the problem is caused by the DigitalOcean App Platform's built-in Cloudflare, and since Cloudflare doesn't properly handle the Vary header by default it became clear that I have to switch. To resolve this, I had to move my deployment away from the DigitalOcean App Platform.

I chose a pre-installed easypanel droplet and set it up with continuous deployment using webhooks, and now my app is now building the same way as it did on the App Platform. Thankfully, my Dockerfile made the transition smooth. With Cloudflare now in front of my droplet, I can ensure that everything works as expected using my custom worker.

Ideally, Cloudflare would need to add an option to add cache rules that can consider response or request headers to then force Cloudflare to cache the response with a different cache key / cache URL. 
Additionally, it would be helpful if DigitalOcean provided an option to disable their global CDN ( it's probablt possibly through an app.yaml configuration), but their documentation is too extensive to quickly find a solution.

For reference, here is my Cloudflare worker code. I'd appreciate any suggestions for improvements, bug fixes, or more efficient solutions:
```
/* eslint-disable import/no-anonymous-default-export */
const addHeadersToUrl = (headersObj: Headers, url: URL, headers: string[]): URL => {
  headers.forEach((header) => {
    if (headersObj.has(header)) url.searchParams.set(header.toLowerCase(), encodeURIComponent(`${headersObj.get(header)}`))
  })
  return url
}

function shouldCacheResponse(response: Response): boolean {
  const cacheControl = response.headers.get('Cache-Control')

  if (!cacheControl) {
    return true
  }

  const cacheDirectives = ['private', 'no-cache', 'no-store']
  return !cacheDirectives.some((directive) => cacheControl.includes(directive))
}

function addUrlParams(url: URL, params: Record<string, string>): URL {
  for (const [key, value] of Object.entries(params)) {
    url.searchParams.set(key, value)
  }
  return url
}

const hasRequestSomeHeaders = (request: Request, headers: string[]) => {
  const headersObj = request.headers
  return headers.some((header) => headersObj.has(header))
}

async function handleRequest(request: Request, ctx: any) {
  const originUrl = new URL(request.url)
  const cacheUrl = new URL(request.url)

  console.log('Request URL:', request.url)

  if (originUrl.pathname.startsWith('/api')) {
    // @ts-ignore
    return fetch(request, originUrl.pathname.startsWith('/api/auth') ? { cf: { cacheTtl: -1 } } : undefined)
  }

  if (hasRequestSomeHeaders(request, ['RSC', 'Next-Router-State-Tree', 'Next-Router-Prefetch'])) {
    addUrlParams(cacheUrl, { 'content-type': 'text/x-component' })
  }

  const cacheKey = new Request(cacheUrl, request)
  /* @ts-ignore */
  const cache = caches.default

  let response = await cache.match(cacheKey)
  console.log('Cache match:', response ? 'Found' : 'Not found', originUrl.toString(), cacheUrl.toString())

  if (!response) {
    response = await fetch(request)
    console.log('Cache URL before reading response:', cacheUrl.toString())
    const modifiedResponse = new Response(response.body, response)

    // Modify cacheUrl based on response 'Content-Type' header
    if (hasRequestSomeHeaders(request, ['RSC', 'Next-Router-State-Tree', 'Next-Router-Prefetch']) && response.headers.get('Content-Type') === 'text/x-component') {
      addHeadersToUrl(modifiedResponse.headers, cacheUrl, ['Content-Type'])
    }

    console.log('Cache URL after reading response:', cacheUrl.toString())

    const modifiedCacheKey = new Request(cacheUrl, request)

    if (shouldCacheResponse(modifiedResponse)) {
      // Cache the response
      console.log('Caching the response with modified cache key:', cacheUrl.toString())
      await cache.put(modifiedCacheKey, modifiedResponse.clone())
    }

    return modifiedResponse
  }

  return response
}

export default {
  async fetch(request: Request, ctx: any) {
    return handleRequest(request, ctx)
  }
}

```

**Comment by timneutkens** [comment]
Posted a reply here: https://github.com/vercel/next.js/pull/49140#issuecomment-1549405009

**Comment by rusted-love** [comment]
Does https://github.com/vercel/next.js/pull/50970 fixed it?

**Comment by timneutkens** [comment]
Should be fixed in #50970 indeed 👍

**Comment by roeean** [comment]
It's still not working in v13.4.10... My site deployed to AWS ECS with AWS Cloudfront as CDN and I still can't load the pages that are under App Router properly, everyone keeps coming as x-document

**Comment by cduff** [comment]
> It's still not working in v13.4.10... My site deployed to AWS ECS with AWS Cloudfront as CDN and I still can't load the pages that are under App Router properly, everyone keeps coming as x-document

@roeean I've got a similar setup working but you need a custom CloudFront cache policy like:

![image](https://github.com/vercel/next.js/assets/7855146/9dea45be-a95c-4eb9-af83-edc557e2daa8)

The `q`, `w` & `url` query string entries allow use of `next/image`.

**Comment by timneutkens** [comment]
@roeean please provide a reproduction in a new issue. We've added a query string parameter to the end of the request for the RSC payload so it's hard to say why you'd still see this without being able to investigate the application.

**Comment by uam2023** [comment]
> @roeean please provide a reproduction in a new issue. We've added a query string parameter to the end of the request for the RSC payload so it's hard to say why you'd still see this without being able to investigate the application.

13.4.4 still happens
