### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'call') in the latest 13.4.x version

### ISSUE THREAD

**Issue by MartinXPN** [vercel/next.js#49330]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/MartinXPN/profound.academy

### To Reproduce

The latest version of NextJS seems to have an issue of occasionally throwing a `TypeError` in the production build. Everything works fine in dev mode. Yet, as soon as the app is deployed to production or run with `yarn build && yarn start`, it starts crashing when refreshing the page a couple of times.

To reproduce one can open this page: https://profound.academy/python-introduction
And then refresh the page several times in a row while disabling the cache (command + fn + R on Macs).
The page will crash and display that "Something Went Wrong".

### Describe the Bug

The bug only appears in production mode and is very hard to trace. Everything is fine in the dev mode.
Several refreshes with disabled cache (this part is important) result in `TypeError: Cannot read properties of undefined (reading 'call')` 

```
{
    "componentStack": "\n    at r (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:31878)\n    at d (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:32439)\n    at c (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:30212)\n    at A (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:23804)\n    at s (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:17794)\n    at r (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:20617)\n    at w (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:21812)\n    at o (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:34168)\n    at x (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:24046)\n    at n.default (http://localhost:3000/_next/static/chunks/app/%5Blang%5D/layout-a9bfa8188b6bca25.js:1:5887)\n    at n.default (http://localhost:3000/_next/static/chunks/app/%5Blang%5D/layout-a9bfa8188b6bca25.js:1:2578)\n    at t (http://localhost:3000/_next/static/chunks/app/%5Blang%5D/layout-a9bfa8188b6bca25.js:1:9680)\n    at d (http://localhost:3000/_next/static/chunks/91893-d7f779692e0b3e0f.js:1:2091)\n    at h (http://localhost:3000/_next/static/chunks/91893-d7f779692e0b3e0f.js:1:2587)\n    at g (http://localhost:3000/_next/static/chunks/91893-d7f779692e0b3e0f.js:1:2792)\n    at http://localhost:3000/_next/static/chunks/app/%5Blang%5D/layout-a9bfa8188b6bca25.js:1:9161\n    at l (http://localhost:3000/_next/static/chunks/app/%5Blang%5D/layout-a9bfa8188b6bca25.js:1:7238)\n    at body\n    at html\n    at C (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:22061)\n    at r (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:31878)\n    at d (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:32439)\n    at c (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:30212)\n    at A (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:23804)\n    at s (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:17794)\n    at r (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:20617)\n    at w (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:21812)\n    at o (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:34168)\n    at x (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:24046)\n    at r (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:31878)\n    at d (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:32439)\n    at c (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:30212)\n    at w (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:10277)\n    at r (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:16844)\n    at s (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:17794)\n    at C (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:14111)\n    at w (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:4673)\n    at x\n    at A (http://localhost:3000/_next/static/chunks/78139-769309dd34c3f2a6.js:1:5064)"
}
```

### Expected Behavior

It should not throw a `TypeError: Cannot read properties of undefined (reading 'call')` no matter the number of refreshes of a page.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by nicholasgriffintn** [comment]
I've already plus +1'd this, but just to add, this is happening a lot for me on development, it's making the app pretty much unusable, it's happening across all pages (even the 404 and error pages) and causes an infinite reload sometimes, it's definitely an issue not just on Vercel / in production.

**Comment by MartinXPN** [comment]
It's frustrating that there is no way to debug this. I can't see the logs or exact error messages to figure out what's exactly going wrong. Would be great to get some hints/guidance on how to debug these types of issues.

**Comment by amlcodes** [comment]
getting this with server actions using a form and action

**Comment by MartinXPN** [comment]
Seems like there might be an issue with the app router and Microsoft Edge. Although it works fine in most cases for Chrome but fails most of the time on Edge.

**Comment by nicholasgriffintn** [comment]
It's definitely not just an edge thing if we're getting the same error, I'm get this on local dev when the page is hot reloaded repeatedly:

```
{
  "severity": "ERROR",
  "msg": {
    "type": "TypeError",
    "msg": "Cannot read properties of undefined (reading 'call')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'call')\n    at options.factory (http://localhost:3000/_next/static/chunks/webpack.js:722:31)\n    at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js:37:33)\n    at fn (http://localhost:3000/_next/static/chunks/webpack.js:377:21)\n    at self.__next_require__ (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:52:17)\n    at requireModule (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:148:32)\n    at initializeModuleChunk (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:1213:17)\n    at readChunk (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:1043:7)\n    at mountLazyComponent (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:15601:19)\n    at beginWork$1 (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:17312:16)\n    at beginWork (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:25650:14)\n    at performUnitOfWork (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24501:12)\n    at workLoopConcurrent (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24487:5)\n    at renderRootConcurrent (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:24443:9)\n    at performConcurrentWorkOnRoot (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23321:38)\n    at workLoop (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:261:34)\n    at flushWork (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:230:14)\n    at MessagePort.performWorkUntilDeadline (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js:537:21)"
  }
}
```

The app then reloads infinitely, with this error.

Will try to make a reproduction when I have time, but I haven't brought this to production yet, and won't as long as this happens.

**Comment by MartinXPN** [comment]
Has anyone managed to resolve the issue or found its root cause? 
Any idea how to debug this?

**Comment by MartinXPN** [comment]
I have been trying to drill down to find the real cause of this crash.
Seems like it happens with MUI Drawer. In the Drawer component as soon as I introduce any [MUI](https://mui.com/core/)-related component like a `Box`, `List`, etc., or use any of the MUI hooks like `useTheme()`, or style a component with `styled()`, the app starts crashing from time to time with the message `Cannot read properties of undefined (reading 'call')`.

Interestingly all of these things work perfectly fine in other areas of the app. The only place this issue keeps popping up is the Drawer component. So, I'm not sure about what's special with the MUI Drawer or maybe it's related to the code organization, but I'd love to hear any constructive ideas on how to debug this and what might be the real cause of the issue.

**Comment by MartinXPN** [comment]
Somehow the issue was fixed in the `next.js@13.4.8`.

**Comment by fran-cadenas-fu** [comment]
Hello, I'm still getting this error calling my server action.

**Comment by DusanStojanovic-gowago** [comment]
Can we reopen this issue? It is not solved, definitely.

It doesn't work for me. Tested in version `13.4.9`, `13.4.9`, and `13.4.10`

**Comment by fran-cadenas-fu** [comment]
I found what was causing my issue. O was using a server action on a route that was the interception target of another route.

I removed the intercepted route and I'm fine.

**Comment by DusanStojanovic-gowago** [comment]
I removed the whole `pages` directory, and added only one route, just to test:

```
├── app
│   ├── layout.tsx
│   ├── page.tsx
```

... and it still doesn't work. Weird.

**Comment by DusanStojanovic-gowago** [comment]
For anyone facing the same issue, I found the reason:

I had this line in the `next.config.js`, in the `webpack` part:

```js
config.resolve.alias['react'] = path.resolve(__dirname, 'node_modules', 'react');
```

When I remove it, everything works just fine.
