### ISSUE TITLE
[NEXT-1208] Hot reloading in the app directory causes infinite rerenders

### ISSUE THREAD

**Issue by UgoRomi** [vercel/next.js#49881]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.9.0
      npm: 9.6.3
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/UgoRomi/hot-reload-rerender-bug

### To Reproduce

1. Start the project with `pnpm dev`
2. navigate to localhost:3000 and open the console
3. edit anything (for example) the console log message in `page.tsx` or `AsyncServerComponent.tsx` and save the file
4. Go back to the webpage and you can notice the console.log statements caused by the rerendering of the components
5. As far as I can tell this only happens when there is a fetch inside a client component that has an async server component as a child. It also happens if you fetch the data using `swr`

### Describe the Bug

Whenever you fetch data in a Client Component that has an async Server Component as a child, hot reloading the files will cause infinite rerenders

### Expected Behavior

To not have infinite rerenders

<sub>[NEXT-1208](https://linear.app/vercel/issue/NEXT-1208/hot-reloading-in-the-app-directory-causes-infinite-rerenders)</sub>

**Comment by danspratling** [comment]
I've just run into this same issue and boiled it down to as small an issue as I can find

For me, all you need is an empty page inside the `/app` folder with `use client` enabled

```
// app/test/page.tsx
"use client";

export default async function TestPage() {
  console.log("test");
  return <div className="test"> Test Page </div>;
}
```

Editing anything causes an infinite loop. This happens within any file that is underneath any `use client` component, which in development mode (especially if you're trying to view draft content) could be _any_ file.

**Comment by bernatfortet** [comment]
Same issue here

**Comment by huyitan** [comment]
Same issue here, this bug happens even in production build.

**Comment by arackaf** [comment]
The issue buries the lede. 

This issue appears to be caused by client components being declared as async. 

**That is not yet a stable feature in React, yet**, which is probably why this is not yet integrated with Next, and therefore breaking.

Removing the async from the client component fixed it (it was never even meant to be async, and I wasn't awaiting anything - but just returning a Promise from a client component appears to be enough to wreck havoc on Next)

https://twitter.com/sophiebits/status/1647775289790050304

**Comment by leerob** [comment]
We're aware of this and exploring solutions to better handle this. In the meantime, you should use a server component for data fetching, and forward the result to a client component. This is effectively the same thing as a "data loader" like `getServerSideProps`. [Learn more here](https://www.youtube.com/watch?v=YQMSietiFm0).

**Comment by timtbdev** [comment]
Same issue, and it's even get worse when you add custom hooks into the component. It makes unresponsive the whole page.  You can call a async function in Layout as serverClientComponent and pass it to the client component as a parameter.

**Comment by TommySorensen** [comment]
How often do the infinite rerenders occur for you guys? Mine is reloading server components one pr. second 🤔
<img width="450" alt="image" src="https://github.com/vercel/next.js/assets/4134473/d236a54b-5bc7-4237-a1fe-bfb75ce4d972">

**Comment by leerob** [comment]
@TommySorensen please ensure you are not using an `async` component that's marked with the `"use client"` directive. We just landed an ESLint rule for this as well.

**Comment by TommySorensen** [comment]
@leerob Thx for heads up. I'm running `13.4.8-canary.9` now with the new eslint rule. Running the linter gave 0 errors, and i also double checked all async components, and none of them have  "use client". I guess i should triple check

**Comment by UgoRomi** [comment]
@TommySorensen In my initial reproduction I didn't have any async client components either. I had an async server component which was imported inside of a client component that fetched some data. 
Maybe you have something similar? If so you could try doing the data fetching in a server component, and then wrap your client component with it passing props down ([Learn more here](https://www.youtube.com/watch?v=YQMSietiFm0))

**Comment by TommySorensen** [comment]
@leerob I found the cause of it. I'm using parallel routes where i didn't use the `page.tsx` since i have no use for it on that level. As soon as i provide as screenshot it stop reloading

<img width="257" alt="image" src="https://github.com/vercel/next.js/assets/4134473/bc06151a-b5da-4f28-b222-3d1dccc4d1d1">

```jsx
// Fixed by passing null in (shop) folder
export default function TestPage() {
  return null;
}
```

**Comment by Viktror-INC** [comment]
Infinity loop

page.tsx
```
import MainPageView from "@/views/main-page-view";

async function getStaticProps() {
  const res = await fetch('https://www.deckofcardsapi.com/api/deck/new/')
  return res.json()
}

export default async function Home() {

  const data = await getStaticProps()

  return (
    <div>
      <MainPageView data={data} />
    </div>
  );
}
```
MainPageView, if click on button i have infinity loop

```
"use client";
import { getNewDeck } from "@/shared/requests";
import axios from "axios";
import React, { use, useCallback, useState } from "react";

interface IMainPageView {
  data: any;
}


const MainPageView = async (props: IMainPageView) => {
  const [num, setNum] = useState(0);
  const { data } = props;
  console.log("data", data);
  console.log("num", num);

  return (
    <div>
      <button onClick={() => setNum(1)}>click</button>
    </div>
  );
};

export default MainPageView;
```

![image](https://github.com/vercel/next.js/assets/62958520/f62fd845-341b-45cc-843d-484613b6e217)

**Comment by leerob** [comment]
@TommySorensen fixed here https://github.com/vercel/next.js/pull/52061.

**Comment by TommySorensen** [comment]
@leerob Seems like the bug still exsist in v. 13.4.8.
I installed 13.4.8 and deleted my page.tsx that returns null. I also deleted the `.next` folder to check if there was some caching happening.
<img width="196" alt="image" src="https://github.com/vercel/next.js/assets/4134473/8c47b799-5ed7-48f7-a3b3-5a6139ac5f9f">

I do not have a reproduction you could test on unfortunately.

**Comment by tnoor-co** [comment]
@TommySorensen - try the latest canary version - #52061 was released as part of [v13.4.9-canary.2](https://github.com/vercel/next.js/commit/0b470753b7b2df4bc10abbf0453888d79e321e02). 

I do still see infinite refreshing in next dev with my dynamic routes inside of parallel routes with that version though, so I may have to create a minimal repro for it.

**Comment by lei0gre** [comment]
Me to, infinite re-render into parallel routes still exists here

**Comment by lei0gre** [comment]
Me too, infinite re-render into parallel routes still exists here

**Comment by Ronbalt** [comment]
Same here...

**Comment by h0tw4t3r** [comment]
Greetings.

It seems that #52362 didn't fix this and the issue is present as of now, and blocks me from using parallel routes.

A repro made by @subfallen – https://github.com/subfallen/nested-routes-inf-refresh-repro/blob/main/README.md proves the issue still exists (https://github.com/vercel/next.js/pull/52061#issuecomment-1619145129):
![Screenshot 2023-11-24 at 18 57 20](https://github.com/vercel/next.js/assets/35642018/64dc7dae-30b6-4f6c-86cc-e61be7c5155b)

NextJS Version: `13.4.8-canary.15`

**Comment by h0tw4t3r** [comment]
> Greetings.
> 
> It seems that #52362 didn't fix this and the issue is present as of now, and blocks me from using parallel routes.
> 
> A repro made by @subfallen – https://github.com/subfallen/nested-routes-inf-refresh-repro/blob/main/README.md proves the issue still exists ([#52061 (comment)](https://github.com/vercel/next.js/pull/52061#issuecomment-1619145129)): ![Screenshot 2023-11-24 at 18 57 20](https://user-images.githubusercontent.com/35642018/285512526-64dc7dae-30b6-4f6c-86cc-e61be7c5155b.png)
> 
> NextJS Version: `13.4.8-canary.15`

The merged fix #52362 might have been broken by  #55026.

**Comment by h0tw4t3r** [comment]
> Greetings.
> 
> It seems that #52362 didn't fix this and the issue is present as of now, and blocks me from using parallel routes.
> 
> A repro made by @subfallen – https://github.com/subfallen/nested-routes-inf-refresh-repro/blob/main/README.md proves the issue still exists ([#52061 (comment)](https://github.com/vercel/next.js/pull/52061#issuecomment-1619145129)): ![Screenshot 2023-11-24 at 18 57 20](https://private-user-images.githubusercontent.com/35642018/285512526-64dc7dae-30b6-4f6c-86cc-e61be7c5155b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDc2MDEsIm5iZiI6MTcwMDkwNzMwMSwicGF0aCI6Ii8zNTY0MjAxOC8yODU1MTI1MjYtNjRkYzdkYWUtMzBiNi00ZjZjLTg2Y2MtZTYxYmU3YzUxNTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDEwMTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NTAxZDk0ZDI1YTk0MWYxYjYzYmFmNmRiMzhiZDgwMTBjYmE3ZTFlZTU1YmUwYWJjMjJiYjM1YTAzMGVkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UFDtIPtSb_cme9iWpI8oD9s0IkO_U6D6xqt1lw_On6I)
> 
> NextJS Version: `13.4.8-canary.15`

Not reproducible in the latest canary.

**Comment by marcinincreo** [comment]
This is still an issue in 14.0.4

**Comment by sehrish30** [comment]
I see this issue when I have both app router and pages router in my old project. The reload happens 2  3 times with full refresh of the page

**Comment by Hrishi1999** [comment]
Also had this infinite re-rendering issue with a server-side component being used within a client-side component. LazyLoading with React.Lazy() + Suspense fixed it for me :)

**Comment by blooser** [comment]
When I put `opengraph-image.png` image into my app dir, next.js started infinity rerender loop - does any body has the same problem?  

I'm using next.js 14

**Comment by devjiwonchoi** [comment]
Hey everyone, this is one of the common mistake with using Client Component and Server Component together.

Let's say we have a Server Component `S` and Client Component `C`.

If you **import** `S` from `C`, then the `S` will become a Client Component as well.
This is the root cause of this issue, that a Client Component `S` was marked as `async`, which is an anti-pattern for now.

![Screenshot 2024-08-06 at 12 02 01 AM](https://github.com/user-attachments/assets/91ce7e97-1a21-4b36-afc1-9a75d0b42163)

Therefore we have to pass `S` as a children of `C` instead of importing it.
This is the [Supported Pattern of Passing Server Components to Client Components](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#supported-pattern-passing-server-components-to-client-components-as-props).

![Screenshot 2024-08-06 at 12 06 27 AM](https://github.com/user-attachments/assets/e230e056-d1bf-4bdc-ae2b-1985ea8ad1f3)

I opened a [PR with fix](https://github.com/UgoRomi/hot-reload-rerender-bug/pull/1) to @UgoRomi's repro, feel free to take a look at the actual migration.
For more information, please take a look at [blog document](https://vercel.com/blog/common-mistakes-with-the-next-js-app-router-and-how-to-fix-them#using-server-and-client-components-together), It is well documented.

**Comment by devjiwonchoi** [comment]
@marcinincreo @blooser @Hrishi1999 @sehrish30 

Hey everyone! Are your problem(s) related to the pattern I introduced above?
If not, could you share a reproduction to your case? I'd happy to take a look!
