### ISSUE TITLE
Module not found: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by willin** [vercel/next.js#50444]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
❯ npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.1.0
      npm: 8.19.3
      Yarn: 3.3.0
      pnpm: 7.24.3
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

-

### To Reproduce

`/demo/page.tsx`:

```ts
import { authOptions } from '@/lib/next-auth';
import { getServerSession } from 'next-auth/next';

export default async function Page() {
  const session = await getServerSession(authOptions);

  return (
    <>
      <pre>{JSON.stringify(session)}</pre>
    </>
  );
}

export const dynamic = 'force-dynamic';
```

### Describe the Bug

works on 13.3.1

<img width="738" alt="image" src="https://github.com/vercel/next.js/assets/1890238/983594b1-7147-4bd7-ab79-c507c49727e8">

but when i tried 13.3.4-13.4.4 or canary

<img width="989" alt="image" src="https://github.com/vercel/next.js/assets/1890238/820b9957-207b-4f00-8208-e834be893e57">

13.3.2,13.3.3 when started, cannot open localhost:3000 always loading.

### Expected Behavior

-

### Which browser are you using? (if relevant)

Brave 113

### How are you deploying your application? (if relevant)

Vercel

**Comment by deepakrh185** [comment]
kindly share the repo link I will try to fix this.

**Comment by willin** [comment]
Clone this repo:  https://github.com/wshow/crypto-bug-mvp

set ENV:

```bash
GITHUB_ID=xxx
GITHUB_SECRET=xxx
```

github oauth app redirect set `http://localhost:3000/api/auth/callback/github`


```
npm run dev
```

then login.

**Comment by deepakrh185** [comment]
Hi @willin  I have fix the issue I will raise the pr to you kinldy check

**Comment by willin** [comment]
<img width="998" alt="image" src="https://github.com/vercel/next.js/assets/1890238/519ea8b6-f901-438a-a625-0a7785d15665">

```
- event compiled client and server successfully in 885 ms (1020 modules)
- error TypeError: Cannot read properties of undefined (reading 'substring')
    at __webpack_require__ (/Users/v0/Projects/Temp/crypto-bug-mvp/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/v0/Projects/Temp/crypto-bug-mvp/.next/server/edge-runtime-webpack.js:281:21)
    at __webpack_require__ (/Users/v0/Projects/Temp/crypto-bug-mvp/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/v0/Projects/Temp/crypto-bug-mvp/.next/server/edge-runtime-webpack.js:281:21)
- error TypeError: Cannot read properties of undefined (reading 'substring')
    at __webpack_require__ (/Users/v0/Projects/Temp/crypto-bug-mvp/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/v0/Projects/Temp/crypto-bug-mvp/.next/server/edge-runtime-webpack.js:281:21)
    at __webpack_require__ (/Users/v0/Projects/Temp/crypto-bug-mvp/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/v0/Projects/Temp/crypto-bug-mvp/.next/server/edge-runtime-webpack.js:281:21)
digest: "1179593499"
```

**Comment by deepakrh185** [comment]
@willin 
<img width="302" alt="image" src="https://github.com/vercel/next.js/assets/71048565/2c33b59c-485f-486e-8412-e3e02ff34b00">

**Comment by deepakrh185** [comment]
Hi @willin  have fixed  https://github.com/deepakrh185/crypto-bug-mvp/commit/8bd4a3115bc4e5b4898d948e5fdb19f71d872329

**Comment by mattiaz9** [comment]
@balazsorban44 I tested with version 13.4.5-canary.9 and i still have this issue. It's not even just in dev mode, also building isn't working.

**Comment by Emilvooo** [comment]
Having the same issue. Tried also different versions, canaries.. No luck.

**Comment by vincentboiardt** [comment]
Having the same issue

**Comment by swiecki** [comment]
Having the same issue

**Comment by mattiaz9** [comment]
I'm wondering if this is the intended behaviour. Since `crypto` is a node module and the edge runtime is based on WEB api we should access `crypto` directly without importing it, for instance:
```ts
export const runtime = "edge"

export function GET() {
  return new Response(JSON.stringify({ uuid: crypto.randomUUID() }), { status: 200 })
}
```

That code indeed works, but of course the problem we have is with third party packages.

Maybe some maintainer can clarify if this is a bug or an intended behaviour? @balazsorban44 @ijjk @shuding

**Comment by balazsorban44** [comment]
(please refrain from mass tagging maintainers in the future)

This is correct, `crypto` does not need to be imported.

The current version of `next-auth` is not edge compatible yet anyway, but the upcoming version will be.

So this error is currently expected.

**Comment by yinbug** [comment]
So what is the solution ？？

**Comment by fineshop** [comment]
I added the following in package.json and it was fixed:

```
{
  "browser": {
    "crypto": false,
    "stream": false
  }
}
```

**Comment by edwardshturman** [comment]
> I added the following in package.json and it was fixed:
> 
> ```
> {
>   "browser": {
>     "crypto": false,
>     "stream": false
>   }
> }
> ```

For me, this fixes the `crypto` issue but surfaces a new issue: `Module not found: Can't resolve 'http'`. Anyone else experiencing the same thing? Still seeing this with `latest` on both Next and NextAuth. Thanks! 🙏

**Comment by shixin-guo** [comment]
same issue ! 

"next": "^13.4.12",
"next-auth": "^4.22.3",

runtime = 'edge';

**Comment by edwardshturman** [comment]
Noting here that NextAuth supports the Edge Runtime in [the experimental v5](https://github.com/nextauthjs/next-auth/pull/7443). Have been playing around with it for a week or so, and works great for me thus far! Thanks Balázs and team :)
