### ISSUE TITLE
Starting at 13.4.13-canary.0 Internal Server Error due to connection refused

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#53171]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
13.4.13-canary.0
```

### Link to the code that reproduces this issue or a replay of the bug

no response

### To Reproduce

just update to this version and get up a production server

### Describe the Bug

- error Failed to handle request for /sw.js
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/.pnpm/next@13.4.13-canary.0_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.64.0/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:34:23)
    at async requestHandler (/app/node_modules/.pnpm/next@13.4.13-canary.0_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.64.0/node_modules/next/dist/server/lib/start-server.js:329:35)
    at async Server.<anonymous> (/app/node_modules/.pnpm/next@13.4.13-canary.0_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.64.0/node_modules/next/dist/server/lib/start-server.js:148:13) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:41367
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1592:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 41367
  }
}

### Expected Behavior

Server Working

<sub>[NEXT-1510](https://linear.app/vercel/issue/NEXT-1510/starting-at-13413-canary0-internal-server-error-due-to-connection)</sub>

**Comment by DuCanhGH** [comment]
Can you try adding `--hostname 127.0.0.1` or `HOSTNAME=127.0.0.1`? It is possible that `localhost` on your machine was resolved to `[::1]`. My PR #53131 tries to fix some issues with IPv6, but it hasn't got any attention yet...

**Comment by joacub** [comment]
im looking at the docs in how to pass that var to production server in standalone mode:

CMD node apps/web/server.js

do you know how?

**Comment by balazsorban44** [comment]
This is the second time I'm letting you know, please follow the bug report template when opening an issue. https://github.com/vercel/next.js/issues/52621#issuecomment-1633970023

Please add a minimal reproduction so we can investigate.

**Comment by joacub** [comment]
> This is the second time I'm letting you know, please follow the bug report template when opening an issue. [#52621 (comment)](https://github.com/vercel/next.js/issues/52621#issuecomment-1633970023)
> 
> Please add a minimal reproduction so we can investigate.

Please, allow me to explain the situation more clearly. I have encountered a recurring issue with the server not starting in production. The problem does not have any clear reproduction steps, and it happens consistently. It's important to note that the issue is not caused by anything on my end, as I've tested it on a completely empty Next.js project, and the problem persists.

This problem was first noticed by another person as well, and we have been trying to pinpoint the specific code that triggers this error. Despite our efforts, the root cause remains elusive. While I understand that you may want more information from me, I assure you that we have thoroughly investigated the situation.

I would appreciate any guidance or assistance you can provide to resolve this matter. As it is affecting the production environment, I'm eager to find a solution as soon as possible. Please let me know if you need any further details or if there's anything specific you would like me to do to help with the investigation and resolution of this issue. Thank you for your support

**Comment by DuCanhGH** [comment]
@joacub `HOSTNAME=127.0.0.1 node apps/web/server.js`.

**Comment by joacub** [comment]
> @joacub `HOSTNAME=127.0.0.1 node apps/web/server.js`.

Thank you so much I didn’t get going they were using that by another config, thank you so much

**Comment by joacub** [comment]
if i do that nothin works, maybe becosue is in docker i will when have time investigate how to solve it thanks

**Comment by joacub** [comment]
this will work properly again
HOSTNAME=0.0.0.0 node apps/web/server.js.
HOSTNAME=localhost node apps/web/server.js.

**Comment by joacub** [comment]
<img width="862" alt="image" src="https://github.com/vercel/next.js/assets/2091228/69ba38d6-1516-4462-a9b0-4d0878a2af58">

**Comment by joacub** [comment]
this is the cause of this ===> 
https://github.com/vercel/next.js/pull/53004

this is frustrating, every single day is a new issue , and then also there is persons like you @balazsorban44 
 that instead of help are only asking for things and arguing..., this is critical...

**Comment by balazsorban44** [comment]
Please read https://github.com/vercel/next.js/issues/53171#issuecomment-1650584517 and https://github.com/vercel/next.js/issues/53171#issuecomment-1650584966

**Comment by joacub** [comment]
> Please read [#53171 (comment)](https://github.com/vercel/next.js/issues/53171#issuecomment-1650584517) and [#53171 (comment)](https://github.com/vercel/next.js/issues/53171#issuecomment-1650584966)

What’s do you mean men, you are the only one don’t know what is happening… the other issue was resolve thanks to me, this one is hound to the same directions, this need investigation for nextjs side not for me, I’m not a worker of you, nextjs is busines that promises things to his customer this is not an open source like a any other that people do in his feee time. Please stop referencing to me like that and have respect , I was enough kind with you, but you are useless and annoying.

**Comment by joacub** [comment]
Error finally detected! As mentioned by @balazsorban44, it's an IPv6 handling error. If you force the use of 0.0.0.0 in Docker environments because you can't probably use 127.0.0.1, it will cause issues when you invoke the rewrite like this:

```js
return NextResponse.rewrite(
        new URL(
          url,
          request.url,
        ),
        getResponseInit(),
      );
```

The next call will invoke the middleware again with the new request, which is not intended. To avoid this, modify it to: 

```js
return NextResponse.rewrite(
         // this is to try to not called the middleware twice remove when next handle this better
        new URL(
          url,
          request.url
            .replace('https://localhost', 'https://0.0.0.0')
            .replace('http://localhost', 'http://0.0.0.0'),
        ),
        getResponseInit(),
      );
```

The middleware is not called twice because Next.js detects it as the same request and simply re-routes it.

**Comment by charnog** [comment]
Same problem here. It started with `13.4.13-canary.0`, and I can also see it in `13.4.13-canary.5`. I've been trying to figure it out on my local machine using Docker, but no luck. I can't really pinpoint what's causing it. We don't have rewrites in the middleware (as @joacub mentioned), for most of the requests, `NextResponse.next()` is executed, but we do have `rewrites` in the config. It could somehow be related.

I know a small example would help, but like I said, I can't narrow it down yet. Still trying to reproduce it locally.

Anyway, here are the logs from `13.4.13-canary.5` from our pods in the Kubernetes cluster. Maybe they'll help somehow.
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:226:29)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:419:24)
    at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:436:13) {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/next/dist/compiled/undici/index.js:1:63301)
      at Socket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '127.0.0.1',
      localPort: 52428,
      remoteAddress: undefined,
      remotePort: undefined,
      remoteFamily: undefined,
      timeout: undefined,
      bytesWritten: 770,
      bytesRead: 207
    }
  }
}
```
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:226:29)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:419:24)
    at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:436:13) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```

**Comment by zdarovka** [comment]
I had the same issues with `13.4.13-canary.5`.  Rollback to `13.4.12` solved it for me.

Here is the error from my container (sorry I no longer have it in plaintext)

![image](https://github.com/vercel/next.js/assets/5191607/129426b4-5f3a-406b-8aad-1787df221fa4)

**Comment by florianliebig** [comment]
We face the same issue beginning from 13.4.13-canary.0 - I tried to quickly reproduce with https://github.com/vercel/next.js/blob/canary/examples/with-docker/README.md and app dir. But it works every time.

We have quite a fancy setup (turborepo, multiple apps, multiple middlewares) but as stated here in the issue it seems to also happen without any of that.

Settings the hostname like in the example: https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile#L60 didn't work for me

**Comment by joacub** [comment]
> We face the same issue beginning from 13.4.13-canary.0 - I tried to quickly reproduce with https://github.com/vercel/next.js/blob/canary/examples/with-docker/README.md and app dir. But it works every time.
> 
> We have quite a fancy setup (turborepo, multiple apps, multiple middlewares) but as stated here in the issue it seems to also happen without any of that.
> 
> Settings the hostname like in the example: https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile#L60 didn't work for me
> 
> Only thing I can share from the error docker container is the line which throws the error:
> 
> ![2023-07-28 at 17 09](https://user-images.githubusercontent.com/10775702/256860403-37a9ad26-2696-41ca-86ef-e9a4aebd8513.png)
> 
> ![2023-07-28 at 17 10](https://user-images.githubusercontent.com/10775702/256860491-a9f50318-8fd0-46bf-81ee-2b44f63b13e1.png)
> 
> From https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/start-server.ts#L332

It will work in a normal setup, I also reproduce myself in a my side and works every time, to reproduce this error you need to have the setup in a docker container mapping the port from for example 3035:3000 and have Nginx proxy going to http://container-name:3035 and the error will happen every single time. There are many other errors when you have that setup like the env vars now are not going to the node, seems like nextjs is wiping all env vars since that versión and no env vars are going to the node server

**Comment by charnog** [comment]
@florianliebig, try setting it to `ENV HOSTNAME 0.0.0.0` instead of `ENV HOSTNAME localhost`, as @DuCanhGH mentioned before. It seems that this is a workaround for now. I'm testing on my side and it appears to resolve the issue.

**Comment by DuCanhGH** [comment]
@charnog yeah they really thought replacing `localhost` with `127.0.0.1` is the way to go 💀 I still haven't got any response by the way.

**Comment by joacub** [comment]
> @charnog yeah they really thought replacing `localhost` with `127.0.0.1` is the way to go 💀 I still haven't got any response by the way.

Yeah the way to fix this is setting hostname as 0.0.0.0 but then other things fails as next seems to be wiping All env vars now

**Comment by joacub** [comment]
> @charnog yeah they really thought replacing `localhost` with `127.0.0.1` is the way to go 💀 I still haven't got any response by the way.

Btw great work with next-pwa working really nice.

**Comment by joacub** [comment]
> @charnog yeah they really thought replacing `localhost` with `127.0.0.1` is the way to go 💀 I still haven't got any response by the way.

🤣

**Comment by joacub** [comment]
> Same problem here. It started with `13.4.13-canary.0`, and I can also see it in `13.4.13-canary.5`. I've been trying to figure it out on my local machine using Docker, but no luck. I can't really pinpoint what's causing it. We don't have rewrites in the middleware (as @joacub mentioned), for most of the requests, `NextResponse.next()` is executed, but we do have `rewrites` in the config. It could somehow be related.
> 
> I know a small example would help, but like I said, I can't narrow it down yet. Still trying to reproduce it locally.
> 
> Anyway, here are the logs from `13.4.13-canary.5` from our pods in the Kubernetes cluster. Maybe they'll help somehow.
> 
> ```
> TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11576:11)
>     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
>     at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:226:29)
>     at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:419:24)
>     at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:436:13) {
>   cause: SocketError: other side closed
>       at Socket.onSocketEnd (/app/node_modules/next/dist/compiled/undici/index.js:1:63301)
>       at Socket.emit (node:events:526:35)
>       at endReadableNT (node:internal/streams/readable:1359:12)
>       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>     code: 'UND_ERR_SOCKET',
>     socket: {
>       localAddress: '127.0.0.1',
>       localPort: 52428,
>       remoteAddress: undefined,
>       remotePort: undefined,
>       remoteFamily: undefined,
>       timeout: undefined,
>       bytesWritten: 770,
>       bytesRead: 207
>     }
>   }
> }
> ```
> 
> ```
> TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11576:11)
>     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
>     at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:226:29)
>     at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:419:24)
>     at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:436:13) {
>   cause: Error: read ECONNRESET
>       at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
>     errno: -104,
>     code: 'ECONNRESET',
>     syscall: 'read'
>   }
> }
> ```

Any rewrite made at any point will lead to the same behavior, triggering the re-execution of all processes and consequently altering the entire outcome of the subsequent code execution. This rewrite is perceived as a new request and should be handled differently to ensure the desired results.

**Comment by joacub** [comment]
> > Same problem here. It started with `13.4.13-canary.0`, and I can also see it in `13.4.13-canary.5`. I've been trying to figure it out on my local machine using Docker, but no luck. I can't really pinpoint what's causing it. We don't have rewrites in the middleware (as @joacub mentioned), for most of the requests, `NextResponse.next()` is executed, but we do have `rewrites` in the config. It could somehow be related.
> > I know a small example would help, but like I said, I can't narrow it down yet. Still trying to reproduce it locally.
> > Anyway, here are the logs from `13.4.13-canary.5` from our pods in the Kubernetes cluster. Maybe they'll help somehow.
> > ```
> > TypeError: fetch failed
> >     at Object.fetch (node:internal/deps/undici/undici:11576:11)
> >     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
> >     at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:226:29)
> >     at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:419:24)
> >     at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:436:13) {
> >   cause: SocketError: other side closed
> >       at Socket.onSocketEnd (/app/node_modules/next/dist/compiled/undici/index.js:1:63301)
> >       at Socket.emit (node:events:526:35)
> >       at endReadableNT (node:internal/streams/readable:1359:12)
> >       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
> >     code: 'UND_ERR_SOCKET',
> >     socket: {
> >       localAddress: '127.0.0.1',
> >       localPort: 52428,
> >       remoteAddress: undefined,
> >       remotePort: undefined,
> >       remoteFamily: undefined,
> >       timeout: undefined,
> >       bytesWritten: 770,
> >       bytesRead: 207
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > TypeError: fetch failed
> >     at Object.fetch (node:internal/deps/undici/undici:11576:11)
> >     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
> >     at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:226:29)
> >     at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:419:24)
> >     at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:436:13) {
> >   cause: Error: read ECONNRESET
> >       at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
> >     errno: -104,
> >     code: 'ECONNRESET',
> >     syscall: 'read'
> >   }
> > }
> > ```
> 
> Any rewrite made at any point will lead to the same behavior, triggering the re-execution of all processes and consequently altering the entire outcome of the subsequent code execution. This rewrite is perceived as a new request and should be handled differently to ensure the desired results.

btw that error you are facing there is not caused by the rewirte, the rewrite is another issue related to this versions becouse you have been force to indicated a HOSTNAME to properly make next working behind proxies and docker, so you need now to indicate in your setup a HOSTNAME 0.0.0.0 so then nextjs is hearing all incoming networks

**Comment by schimi-dev** [comment]
For self-hosted apps that use `output: standalone` Next.js `v13.4.13` introduced some weird and really hard to reproduce behaviours. This is an attempt to summarize my experience. Note that all of the things described below worked fine in `v13.4.12`.

Below is the `next.config.js` file:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
    output: 'standalone',
}

module.exports = nextConfig
```

For reproduction do the following: 
1) Build an app where `output: standalone` is configured.
2) For easier reproduction copy the `static` and `public` folder as described  here: https://nextjs.org/docs/app/api-reference/next-config-js/output#automatically-copying-traced-files
3) Start the app with `node server.js` on a server where `localhost` resolves to an ipv6 address.

In such an environment, the following 2 scenarios fail:
# 1. Internationalization middleware always redirects to `localhost`

Reproduction:
1) Use the example from the Next.js repository: https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing
2) Configure `output: standalone`.
3) Increase Next.js version to `13.4.13`.
4) Host the app on a differen server (not your local machine) where localhost resolves to an ipv6 address.
5) Visit the corresponding url in the browser, e.g.: http://my-test-server.mycompanydomain:3000

**Result:** The internationalization middleware redirects to: http://localhost:3000/en
**Expected:** The internationalization middleware should redirect to: http://my-test-server.mycompanydomain:3000/en

# 2. Redirects in Server Actions force a hard reload of the whole page in the browser
When running on a Server that only uses ipv4, Server Actions now work perfectly fine thanks to: 
https://github.com/vercel/next.js/pull/53373 and https://github.com/vercel/next.js/pull/53368 (great work by the way, I was really looking forward to that).

However, when hosted on a Server where `localhost` resolves to an ipv6 address and a Server Action uses `redirect("/some-other-path")` an error message is logged  and the redirect is enforced via a hard page reload in the browser:

Reproduction:
1) Use any simple service where Server Actions are enabled.
2) Call a Server Action that does a `redirect` to another page or the same page (it doesn't matter).

**Result:** The new page is visited via a hard reload in the web browser and the following error is logged to the console: 
<img width="508" alt="redirect_error" src="https://github.com/vercel/next.js/assets/93941373/89c636f4-af18-46e4-83e4-c02f9b53b90d">
**Expected:** Navigation should not reload the whole page and no error message should be logged.

# Additional Info
These were two simple scenarios I was able to reproduce. Moreover, there also seems to be a problem regarding environment variables for `output: standalone` in `13.4.13`: https://github.com/vercel/next.js/issues/53579 and https://github.com/vercel/next.js/issues/53367 

This makes it quite hard to test how aspects like manually setting HOSTANAME=0.0.0.0 or to 127.0.0.1 would work. In my case, none of the two reproduction scenarios described could be solved by this.

One more thing I noticed is that in `13.4.13` starting the server logs the following:
<img width="432" alt="bug_reproduction_13" src="https://github.com/vercel/next.js/assets/93941373/5be4b334-2f8a-43fd-a5b4-2991f375e0c6">
Note the first line: "ready started server on 0.0.0.0:3000, url: http://localhost:3000"
Is this intended to be that way?

I hope that this can help with troubleshooting. I really think that this is a hard one to reproduce, as problems become present in different aspects of the app, but only in a specific environment.

**Comment by schimi-dev** [comment]
Moreover, from what I tested it seems that @joacub is right and that this problem was already introduced in 13.4.13-canary.0, maybe via https://github.com/vercel/next.js/pull/53004. 

Nevertheless, for the reproduction scenarios I described, I would recommend the Stable Version `13.4.13`, because one of the reproduction Scenarios targets Server Actions where some significant changes/fixes where made in the meantime.

**Comment by opeologist** [comment]
this is also occurring in my environment. attempting to use `ENV HOSTNAME 0.0.0.0` in `Dockerfile` to see if that resolves the issue for now. reverting back to `13.4.12` didn't seem to resolve the issue. will update once the add in the Dockerfile is deployed as to whether that resolves the issue for now or not

**Comment by opeologist** [comment]
reverting back down to `13.4.12` resolved the issue, along with setting `ENV HOSTNAME localhost` in Dockerfile. hoping this and the related env var issue when in `output: standalone` gets resolved so i can unpin

**Comment by joacub** [comment]
> reverting back down to `13.4.12` resolved the issue, along with setting `ENV HOSTNAME localhost` in Dockerfile. hoping this and the related env var issue when in `output: standalone` gets resolved so i can unpin

You can today safely with workaround setting host to 127.0.0.1 and in the docker file writing the card to the env vars file

**Comment by darthmaim** [comment]
I have made a simple reproduction repository which reproduces the issue every time: 

0. Clone https://github.com/darthmaim-reproductions/vercel-next.js-53171
1. Run this command to build and start a docker container 
    ```sh
    docker build -t vercel-next.js-53171 . && docker run --rm -p3000:3000 vercel-next.js-53171
    ```
2. Access http://localhost:3000/
3. The server responds with `Internal Server Error`
4. The server logs output
    ```raw
        - ready started server on e68ae5711fa3:3000, url: http://e68ae5711fa3:3000
    Listening on port 3000 url: http://e68ae5711fa3:3000
    - error Failed to handle request for /
    TypeError: fetch failed
        at Object.fetch (node:internal/deps/undici/undici:11576:11)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
        at async requestHandler (/app/node_modules/next/dist/server/lib/start-server.js:336:33)
        at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:152:13) {
      cause: Error: connect ECONNREFUSED 127.0.0.1:41303
          at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
        errno: -111,
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 41303
      }
    }
    - error Failed to handle request for /favicon.ico
    TypeError: fetch failed
        at Object.fetch (node:internal/deps/undici/undici:11576:11)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
        at async requestHandler (/app/node_modules/next/dist/server/lib/start-server.js:336:33)
        at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:152:13) {
      cause: Error: connect ECONNREFUSED 127.0.0.1:41303
          at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
        errno: -111,
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 41303
      }
    }
    ```

**Comment by ddoan** [comment]
How did this slip canary into the release? This broke prod for us.

**Comment by ddoan** [comment]
This reproduces on `13.4.13` as well so suggesting using that without a fix is not a good suggestion.

**Comment by wroughtec** [comment]
Always nice when a patch introduces a breaking change 🙄. What's the workaround for runtime environmental variables? As I can get the app to run in docker by setting the hostname (as above) but the runtime envs are not found (kinda essential as they are for auth) this is on a standalone build. (checked on the next canary release and the same issue is there too).

**Comment by leepowellnbs** [comment]
Getting the same issue. Is there a workaround for now? Tried adding `ENV HOSTNAME 0.0.0.0` to our Dockerfile and that doesn't seem to have worked.

**Comment by joacub** [comment]
> Getting the same issue. Is there a workaround for now? Tried adding `ENV HOSTNAME 0.0.0.0` to our Dockerfile and that doesn't seem to have worked.

It does work, at least working for me, we also write in the docker file all env vars we want to passs to nextjs runtime

**Comment by zurgul** [comment]
**nextjs: ^13.4.13**
I looked into nextjs code and found a possible cause of the issue. The solution I found worked fine when nextjs app was started via Docker container.

If you look into **.next/standalone/server.js** you'll see the following lines of code
```js
const hostname = process.env.HOSTNAME || 'localhost'
...
startServer({
...
  hostname: hostname === 'localhost' ? '0.0.0.0' : hostname,
...
```
It seems that process.env.HOSTNAME was set by docker builder to some random string, therefore nextjs server was started with that random hostname instead of '0.0.0.0'. This means that connections was only accepted if that random hostname was used in any client request.

### Workaround solution
server inside of container should accept connections by any address (localhost, 127.0.0.1, ...) - so it must be 0.0.0.0. To achieve this I set HOSTNAME in Dockerfile to localhost, hence in the aforementioned **.next/standalone/server.js** it was resolved as hostname='0.0.0.0' prop for the startServer.
Hope this will help someone.

**Comment by leepowellnbs** [comment]
Update - I was setting the HOSTNAME in the wrong file, once moved to the entrypoint script it all works now. Thanks!

**Comment by alexboii** [comment]
not using docker & we're getting the same error on our repo. downgrading to 13.4.12 doesn't cause this issue but then our vercel build fails because of some weird "out of space" errors. upgrading to `13.4.14-canary.1` gives the same error as in OP & then just goes into an infinite spam of:

```
[dx:next] TRPCClientError: Unexpected token < in JSON at position 0
[dx:next]     at TRPCClientError.from (file:///Users/sasha/housing_cloud/web/node_modules/@trpc/client/dist/TRPCClientError-fef6cf44.mjs:26:16)
[dx:next]     at file:///Users/sasha/housing_cloud/web/node_modules/@trpc/client/dist/httpUtils-ad76b802.mjs:125:36
[dx:next]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[dx:next]   meta: {
[dx:next]     response: Response {
[dx:next]       [Symbol(realm)]: null,
[dx:next]       [Symbol(state)]: [Object],
[dx:next]       [Symbol(headers)]: [HeadersList]
[dx:next]     }
[dx:next]   },
[dx:next]   shape: undefined,
[dx:next]   data: undefined,
[dx:next]   [cause]: SyntaxError: Unexpected token < in JSON at position 0
[dx:next]       at JSON.parse (<anonymous>)
[dx:next]       at parseJSONFromBytes (node:internal/deps/undici/undici:6498:19)
[dx:next]       at successSteps (node:internal/deps/undici/undici:6472:27)
[dx:next]       at node:internal/deps/undici/undici:1145:60
[dx:next]       at node:internal/process/task_queues:140:7
[dx:next]       at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
[dx:next]       at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
[dx:next]       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[dx:next] }
```

**Comment by sljeff** [comment]
It should be noted that:
- by default, k8s injects the `HOSTNAME` environment variable into pods, and its value is the pod name.

So in k8s, the server will **never** listen on 0.0.0.0 after updating to 13.4.13.
Unless we update the deployments or start commands.

**Comment by zurgul** [comment]
> * by default, k8s injects the `HOSTNAME` environment variable into pods, and its value is the pod name.
> 
> So in k8s, the server will **never** listen on 0.0.0.0 after updating to 13.4.13. Unless we update the deployments or start commands.

we use k8s as well, however I was able to reproduce the problem with HOSTNAME locally using only Docker. When HOSTNAME was set in Dockerfile the issue was resolved locally and in k8s cluster

**Comment by leerob** [comment]
Thank you for providing the minimal reproduction – I've marked this one to be dug into further. In the meantime, please remain on `13.4.12` or lower while we dig into this 🙏

**Comment by leerob** [comment]
This has been fixed ✅

**Comment by XEngine** [comment]
no it's not fixed. At least not for me.  Kubernete pods are assigned default HOSTNAME 
![image](https://github.com/vercel/next.js/assets/6682465/faf2e576-9edc-46a5-8234-0ab9874ce546)

however when in 13.4.19 app somehow listens an ip address instead of the hostname and many restarts after, liveness probe detects it's somehow alive, next (node) begins to give ssl issues.

does anybody know any workaround for this?

**Comment by DuCanhGH** [comment]
@XEngine that doesn't look like an URL, nor an IP to me, which makes me wonder if that environment variable was even meant to be used like this. Can you check what did Next.js log back in older versions? I mean, https://github.com/vercel/next.js/commit/803bbe5c9388bb9b5af3b75ba6f1a76332e74112 fixed the standalone mode not getting `process.env` just a few đays ago.

**Comment by XEngine** [comment]
Ye. Before it was starting like this: 
```
Listening on port 3000 url: http://store-herrenausstatter-58cd58f98d-n92sf:3000
```
and it was working until 13.4.12. After that version whole thing begins to fail. Our environment still the same, the hostname you is the same hostname format. I have tried to run my dockerfile with 0.0.0.0, 127.0.0.1, [::1], localhost it started with 0.0.0.0 but received those ssl issues I don't know.

**Comment by DuCanhGH** [comment]
@XEngine if it broke in 13.4.12 then perhaps it's not really related to my fix and this issue. Maybe I'll investigate into it later if possible :) That IP being shown is definitely due to my PR though, but you shouldn't worry about that.

**Comment by XEngine** [comment]
> @XEngine if it broke in 13.4.12 then perhaps it's not really related to my fix and this issue. Maybe I'll investigate into it later if possible :) That IP being shown is definitely due to my PR though, but you shouldn't worry about that.

Sorry for my mistake on version definition. Correction : Working fine until **13.4.13**.

**Comment by DuCanhGH** [comment]
@XEngine yeah if it's 13.4.13 then it will be a lot more painful 💀

**Comment by izi-p** [comment]
Hello,

Same issue on our side. 
(Build standalone+docker+kubernetes).

App is running fine locally outside docker container.

Everything did work on kubernetes for 13.4.12.

When using 13.4.13, readiness probe or liveness probe cannot be reached on kubernetes pods with following error
`Liveness probe failed: Get "http://172.16.*.*:3000/healthz": dial tcp 172.16.*.*:3000: connect: connection refused`

Please note as well that our application use a env var named "HOSTNAME" and that it does conflict with the process.env.HOSTNAME used inside the generated next `server.js` file. I had to implement a postbuild script to rewrite server.js to not check this env var and always use localhost

**Comment by DuCanhGH** [comment]
@izi-p does adding `ENV HOSTNAME localhost` not work? Why would you need to override server.js?

**Comment by izi-p** [comment]
@DuCanhGH We need to override it because our application use a runtime variable named "HOSTNAME" and conflicts with the one server.js try to use. It seems to work by replacing hostname with 0.0.0.0 inside server.js

**Comment by vpmedia** [comment]
Hi!
I've spent about a whole working day debugging ECONNRESET/ECONNREFUSED/Server unexpectedly closed the connection errors while trying to run my next.js application inside a Docker container in localhost.
My solution is to downgrade the node.js image to node:16-bullseye (all the other later versions and/or different hostname changes did not help).
I've worked with two different next.js apps, 13.2.4 was exited with error codes, 13.4.19 was hanging while trying to establish connection without success.

**Comment by DuCanhGH** [comment]
@izi-p just asking, does `HOSTNAME=0.0.0.0 node .next/standalone/server.js` not work?

**Comment by DuCanhGH** [comment]
@XEngine hopefully #54926 should fix your use case :)

**Comment by ctsstc** [comment]
I've been losing my mind as well with too much time sunk into this...

I'm on Next version: `13.4.19`

I constantly get these errors in my logs; I imagine they're from K8's probes for liveness and readiness; even though the container launches just fine, but later fails with 500 errors it seems for those probes. I used to utilize a basic health check page, then I tried utilizing an API route that returned a simple 200 OK for the body.

## Errors

```
- ready started server on [::]:3000, url: http://localhost:3000
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:447:24)
    at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:464:13)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/next/dist/compiled/undici/index.js:1:63301)
      at Socket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1376:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '::1',
      localPort: 43952,
      remoteAddress: undefined,
      remotePort: undefined,
      remoteFamily: undefined,
      timeout: undefined,
      bytesWritten: 999,
      bytesRead: 542
    }
  }
}
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:254:29)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:447:24)
    at async requestHandler (/app/node_modules/next/dist/server/lib/router-server.js:464:13)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:117:13) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```

I also tried setting `HOSTNAME "0.0.0.0"` in my `Dockerfile` but that does not help. It's also odd the bootup message still says: `- ready started server on [::]:3000, url: http://localhost:3000`
