### ISSUE TITLE
Tests fails when lucide-react is used with Next 13.4.13

### ISSUE THREAD

**Issue by edenstrom** [vercel/next.js#53668]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/edenstrom/nextjs-bug-reproduction

### To Reproduce

Relevant code in example above:

- src/app/component.tsx
- src/app/component.test.tsx

1. Run `pnpm test` or `jest` to run tests.
2. Tests will fail with error below:

```
 FAIL  src/app/component.test.tsx
  ● Test suite failed to run

    Cannot find module 'modularize-import-loader?name=Check&from=default&as=default&join=./icons/check!lucide-react' from 'src/app/component.tsx'

    Require stack:
      src/app/component.tsx
      src/app/component.test.tsx



      at Resolver._throwModNotFoundError (node_modules/.pnpm/jest-resolve@29.6.2/node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (src/app/component.tsx:12:66)
      at Object.<anonymous> (src/app/component.test.tsx:7:20)

Test Suites: 1 failed, 1 total
```

3. Output works in browser with `next dev` and shows icon correctly
4. Change version of Next to 13.4.12. This makes the tests work again.

### Describe the Bug

Usage of `lucide-react` with Next.js `13.4.13` crashes the tests. 

<table>
<tr>
 <th>Version
 <th>Tests works
<tr>
<tr>
 <td>13.4.13
 <td>❌
<tr>
 <td>13.4.13-canary.18
 <td>❌
<tr>
 <td>13.4.12
 <td>✅
</table>

### Expected Behavior

Module should correctly resolve and the tests should succeed.

<sub>[NEXT-1494](https://linear.app/vercel/issue/NEXT-1494/tests-fails-when-lucide-react-is-used-with-next-13413)</sub>

**Comment by balazsorban44** [comment]
Looks like #53051 has not addressed some imports correctly, we will look into this!

**Comment by syntaxlexx** [comment]
Any workaround in the meantime?

**Comment by benrandja-akram** [comment]
> Any workaround in the meantime?

@syntaxlexx try    

```json
 "lucide-react": "0.263.1",
```

**Comment by gtonussi** [comment]
Hi, had the same issue updating my project to next@13.4.13 using lucide-react@0.265.0.

**Comment by JefteMedeiros** [comment]
Same problem here, rolled back to 13.4.12

**Comment by balazsorban44** [comment]
This was fixed in #53697, so closing. You can upgrade to `next@canary` to test it out, and it will be available shortly on `next@latest` too!

**Comment by kremalicious** [comment]
this is not solved for me when using Next.js v13.4.16 and lucide-react v0.268.0, still getting:

```
Cannot find module 'modularize-import-loader?name=ArrowDownCircle&from=default&as=default&join=../esm/icons/arrow-down-circle!lucide-react' from ...
```

**Comment by iarlen-reis** [comment]
> isso não foi resolvido para mim ao usar o Next.js v13.4.16 e o lucide-react v0.268.0. Enquanto resolvido durante as execuções de compilação, ainda estou conseguindo isso ao fazer qualquer teste com o Jest:
> 
> ```
> Cannot find module 'modularize-import-loader?name=ArrowDownCircle&from=default&as=default&join=../esm/icons/arrow-down-circle!lucide-react' from ...
> ```
> 
> Reprodutível com o caso de teste mencionado originalmente, mas com Next.js atualizado: https://github.com/edenstrom/nextjs-bug-reproduction

> go back to the previous version of nextjs: "next": "^13.4.12".
>
>```npm install next@13.4.12```

**Comment by max-programming** [comment]
Same here @msquinn

**Comment by steezplusplus** [comment]
Me as well

**Comment by joaopedrodcf** [comment]
This combination works to run jest tests:

`lucide-react: 0.269.1`

`next: 13.4.20-canary.28`

It seems the problem stopped appearing from this version onwards: 13.4.20-canary.9

**Comment by steezplusplus** [comment]
Works with 

`"next": "13.4.20-canary.28"`
`"lucide-react": "^0.277.0"`
