### ISSUE TITLE
Next JS compiling time is too long.

### ISSUE THREAD

**Issue by Apu-Emdad** [vercel/next.js#54618]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.16
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: standalone
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Apu-Emdad/QF

### To Reproduce

Run the following commands:

-  yarn
-  yarn dev

### Describe the Bug

After  `yarn dev`, I go to localhost:3000. From there the page can take up to 60 seconds to display. Then when the first page finally displays, each code change fast refresh or page transition SSR (compilation) takes between 15-20 seconds, sometimes more than 30 seconds, and sometimes it even doesn't work so I have to refresh the page.

**After installing  next@canary**
I got this error:

> TypeError: Cannot read properties of null (reading 'buffer')
>     at C:\Apu\personal_project\QF\QF\node_modules\next\dist\server\dev\hot-reloader.js:858:122
>     at SortableSet.forEach (<anonymous>)
>     at C:\Apu\personal_project\QF\QF\node_modules\next\dist\server\dev\hot-reloader.js:850:50
>     at Array.forEach (<anonymous>)
>     at C:\Apu\personal_project\QF\QF\node_modules\next\dist\server\dev\hot-reloader.js:844:42
>     at Map.forEach (<anonymous>)
>     at C:\Apu\personal_project\QF\QF\node_modules\next\dist\server\dev\hot-reloader.js:841:39
>     at Hook.eval [as callAsync] (eval at create (C:\Apu\personal_project\QF\QF\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:18:1)
>     at Compiler.emitAssets (C:\Apu\personal_project\QF\QF\node_modules\next\dist\compiled\webpack\bundle5.js:28:144868)
>     at C:\Apu\personal_project\QF\QF\node_modules\next\dist\compiled\webpack\bundle5.js:28:488923
>     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

### Expected Behavior

Page load + compilation should be faster.

### Which browser are you using? (if relevant)

Chrome 116.0.5845.97

**Comment by balazsorban44** [comment]
You seem to be on an older version of Next.js, after which we've released a lot of performance improvements, so you should be able to upgrade. The unrelated issue should be reported as a separate bug with a **minimal** reproduction, focusing on the issue. Please remove unrelated code/dependencies and open a new issue.

**Comment by Apu-Emdad** [comment]
@balazsorban44 
Hi, I updated next version to **13.4.19**
The problem still persists. I still have to wait for 15s-20s. 
You can check the latest commit `[next update -> 13.4.19]`
![image](https://github.com/vercel/next.js/assets/62764020/aa248907-7aa5-4791-bf90-979ab25279ee)

### Please let me know if there is any possible fix.

**Comment by wwwhatley** [comment]
This is not an outdated version... 13.4.19?
