### ISSUE TITLE
create-next-app puts all dependencies to `latest` instead of pinning version

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#56174]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js

### To Reproduce

`pnpm create next-app`

### Current vs. Expected behavior

Current: All packages are `latest`.
Expected: Package versions should be pinned.

The reason package versions should be pinned is because, in my opinion, the job of upgrading packages should be the developer's responsibility, as the developer needs to ensure the app still works normally before upgrading any dependencies – as who knows, there could be a release where a dependency may bring breaking changes to the codebase.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Not applicable.
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

### Additional context

I used a dummy link for the "Link to the code that reproduces this issue" section because here it doesn't require a reproduction repository to see the bug. Sorry about that.

Looks like the bug is from https://github.com/vercel/next.js/pull/55730.

<sub>[NEXT-1664](https://linear.app/vercel/issue/NEXT-1664/create-next-app-puts-all-dependencies-to-latest-instead-of-pinning)</sub>

**Comment by ShaikRehan123** [comment]
I can confirm, this is happening to me too

**Comment by balazsorban44** [comment]
> I used a dummy link for the "Link to the code that reproduces this issue" section because here it doesn't require a reproduction repository to see the bug. Sorry about that.

FWIW, you could have linked to a clean `create-next-app` install, but I understand.

Thanks for opening this issue! The change in #55730 was intentional, although I understand your argument. I put up a PR that should fix this

**Comment by joulev** [comment]
Thanks a lot!

**Comment by FNogueiraIntekMedical** [comment]
Hello, dear Contributors!

Would like to know when this change will take effect on running the command 'npx create-next-app'. I just tried it and still face the same issue, all the dependencies are marked with 'latest' instead of the pinned versions. 

(Sorry for the ignorance on how these changes work in a big project like this.)

Thanks!

**Comment by joulev** [comment]
@FNogueiraIntekMedical Right now it's not yet easily doable.

When Next.js releases v13.5.4-canary.7, you can use `npx create-next-app@canary` for this.

If you want to use the stable channel, wait until v13.5.4 is released, then you can use `npx create-next-app@latest`.

If you need it right now, `npx create-next-app@13.5.2` should do the job (it will be the previous behaviour of `create-next-app`, not the changes applied in the above PR).

Note that the behaviours of `create-next-app@13.5.2` is different from the changes above:

* 13.5.2 and previous: all versions are pinned (`"react": "18.2.0"`) but all dependencies are `dependencies` (not separated to deps and devDeps – but this doesn't matter). I personally like this one the most.
* 13.5.3: everything is `latest` (`"react": "latest"`).
* 13.5.4 and later: it will be "pinned to the major version" (idk how to explain it). Basically it will be `"react": "^18"`, not `"react": "18.2.0"`.

**Comment by FNogueiraIntekMedical** [comment]
Thanks for the clarification!!
