### ISSUE TITLE
maxDuration setting doesn't work

### ISSUE THREAD

**Issue by yakhinvadim** [vercel/next.js#56447]
### Link to the code that reproduces this issue

https://github.com/yakhinvadim/vercel-maxduration

### To Reproduce

1. Deploy repo to vercel with Pro account
2. Visit /api/long 

### Current vs. Expected behavior

Expected: the request finishes, since maxDuration is set to 90 seconds
Actual: the request fails with 504 Gateway Time-out error after 60 seconds

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.4
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by hnykda** [comment]
I tried configuring it via:

```
{
  "functions": {
    "app/**": {
      "memory": 3008,
      "maxDuration": 300
    }
  }
}
```
and also without a success. An endpoint:
```
```

**Comment by space1worm** [comment]
Experiencing same issue as well on PRO plan.

**Comment by swarnava** [comment]
Hi,

Swarnava from Vercel team here! We are investigating this issue.

**Comment by hnykda** [comment]
There is [this discussion](https://github.com/orgs/vercel/discussions/4248#discussion-5672536) btw. if that helps to provide more info

**Comment by space1worm** [comment]
Hi @swarnava I have also provided small MRE.

app: https://github.com/space1worm/serverless-timeout-test
github: https://github.com/vercel/next.js/issues/56413

**Please note**
This app is also on PRO plan.

<img width="364" alt="Screenshot 2023-10-07 at 14 09 09" src="https://github.com/vercel/next.js/assets/84189246/870e0b82-9f20-47e1-a3bd-772ae3d57478">

**Comment by swarnava** [comment]
Hi there,

This issue should be fixed now. Let us know if you are still having trouble.

**Comment by hnykda** [comment]
Fixed, works for me, thanks.

**Comment by faye1225** [comment]
<img width="963" alt="image" src="https://github.com/vercel/community/assets/56664035/c9f3ac08-cd83-42b3-b2ab-54f5c7518d6c">
Problems are still being encountered.
I have an API request that takes a long time to process. I set maxDuration, but it doesn't take effect. Below are my relevant configurations and code.

```
export const runtime = 'edge'
export const maxDuration = 300
export async function POST(req: Request) {
    const uploadJson = await fetch(...)
...
    return NextResponse.json(uploadJson)
}
```
"next": "13.5.5-canary.17" and I’m on a PRO plan

**Comment by 0xRomain** [comment]
I've got the same problem too from an api and also cron api.
I tried to add `export const maxDuration = 60;` but without success

**Comment by swarnava** [comment]
Please create a new issue with more details. Note `xport const maxDuration = 60;` only available on 13.5.4 and later

**Comment by faye1225** [comment]
fixed,https://github.com/orgs/vercel/discussions/4248#discussioncomment-7310341
