### ISSUE TITLE
Google Analytics missing from `@next/third-parties`

### ISSUE THREAD

**Issue by nickmccurdy** [vercel/next.js#57643]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:23 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_X86_64
Binaries:
  Node: 21.1.0
  npm: 10.2.1
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries

### What browser are you using? (if relevant)

Chrome 118.0.5993.117

### Describe the Bug

The `GoogleAnalytics` component originally proposed in #51194 is missing, and the `GoogleTagManager` component that replaced it cannot be used with Google Analytics because it depends on the Google tag library (not to be confused with the Google Tag Manager library).

After skimming #48256, it seems like the maintainers and contributors intended for the new `@next/third-parties` package to include an integration for each of the three Google services in [`third-party-capital`](https://github.com/GoogleChromeLabs/third-party-capital). However, its implementation of Google Analytics was never used, and instead an unrelated `GoogleTagManager` component was implemented from scratch.

### Expected Behavior

There is a `GoogleAnalytics` component using Google tag with either [`third-party-capital`](https://github.com/GoogleChromeLabs/third-party-capital) or [`next/script`](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts).

#### With missing `GoogleAnalytics` component

1. `import { GoogleAnalytics } from '@next/third-party'`
2. Attempt to use `<GoogleAnalytics />`.

#### With existing `GoogleTagManager` component

1. Create a [Google Analytics](https://analytics.withgoogle.com/) account.
2. Create a Google Analytics 4 or Google Analytics 360 (Google Analytics 4 or Universal Analytics) property.
3. Copy your Measurement (Google Analytics 4) or Tracking (Universal Analytics) ID.
4. `import { GoogleTagManager } from '@next/third-party'`
5. Attempt to use with your pasted Measurement or Tracking ID.
6. Run `next dev`.
7. Install [Google Chrome](https://www.google.com/chrome/) and [Tag Assistant Companion](https://chromewebstore.google.com/detail/tag-assistant-companion/jmekfmbnaedfebfnmakmokmlfpblbfdm).
8. Open [Tag Assistant](https://tagassistant.google.com/).
9. Add the domain of your local Next server (should be http://localhost:3000).
10. Observe that tags are missing in Tag Assistant and optionally that events are missing in Google Analytics debug view.

**Comment by m-farah** [comment]
It looks like the ### @next/third-party is not available with Next 14; only works with Next 13.

**Comment by housseindjirdeh** [comment]
@nickmccurdy You're totally right. We decided to first launch GTM and we're currently working on a separate `<GoogleAnalytics>` component. We'll link the PR with this issue once its up :)

**Comment by housseindjirdeh** [comment]
@m-farah @next/third-parties can be used in both Next 13 and 14! There's a peerDep issue that has been resolved since: #57515. For the meantime, you can either install the upgrade to the latest `next` canary or `npm install @next/third-parties --legacy-peer-deps`.

**Comment by bagedaddy** [comment]
With the existing GoogleTagManager component, are we currently able to track tags (e.g., from Tiktok / reddit ad campaigns)?

**Comment by nickmccurdy** [comment]
If you're using them through Google Tag Manager, yes.

**Comment by srhise** [comment]
This is in the canary release for `@next/third-parties`

**Comment by nickmccurdy** [comment]
- https://github.com/vercel/next.js/pull/58418
- https://github.com/vercel/next.js/pull/59671

**Comment by nickmccurdy** [comment]
@srhise I can confirm this is working as of `14.0.5-canary.7`, thanks.
```ts
import { GoogleAnalytics } from "@next/third-parties/google";

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>{children}</body>
			<GoogleAnalytics gaId="UA-*" />
		</html>
	);
}
```
I'll leave this open until it's in a stable release.

**Comment by housseindjirdeh** [comment]
Closing since this has landed in https://github.com/vercel/next.js/pull/58418 :)

**Comment by housseindjirdeh** [comment]
Oops just saw your comment @nickmccurdy about leaving this open until it's in stable. Sorry!

**Comment by taujeng** [comment]
Hi @housseindjirdeh @nickmccurdy , I'm still having trouble getting Google Analytics working for me even after switching to canary. Any help would be greatly appreciated, thanks!

My dependencies:
```
    "@next/third-parties": "^14.0.4",
    "@types/node": "20.5.6",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "dotenv": "^16.3.1",
    "eslint": "8.48.0",
    "eslint-config-next": "13.4.19",
    "hamburger-react": "^2.5.0",
    "next": "^14.0.5-canary.28",
```
In layout.tsx:

```
import { GoogleAnalytics } from "@next/third-parties/google";


config.autoAddCss = false;


export const metadata: Metadata = {
  title: 'palette',
  description: 'one minute journal app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <EntryProvider >
          {children}
        </EntryProvider>
        <Footer />
      </body>
      <GoogleAnalytics gaId={process.env.GOOGLE_ANALYTICS} />

    </html>
  )
}
```

**Comment by thehomelyedit** [comment]
I have tried on canary latest and still having issues implementing <GoogleAnalytics gaId='GA-123....'/> generating the following errors:

Error: Unsupported Server Component type: undefined
    at stringify (<anonymous>)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
 ⨯ Error: Unsupported Server Component type: undefined
    at stringify (<anonymous>)
 ⨯ Error: Unsupported Server Component type: undefined
    at stringify (<anonymous>)

**Comment by scottroot** [comment]
I have the same problem as those above.
I also am on latest canary and followed the advice on one of the other threads about adding the third-parties/google to tsconfig. Nothing working so far - still fails to build with error that GoogleAnalytics is not there.

**Comment by timomedia** [comment]
In next.js 14.0.1 have error 
Module '"@next/third-parties/google"' has no exported member 'GoogleAnalytics'.

**Comment by krashnakant** [comment]
using latest @nextjs and @next/third-parties still getting TS2305: Module "@next/third-parties/google" has no exported member GoogleAnalytics.

I looked into dist folder there is no component for GoogleAnalytics

**Comment by steps371** [comment]
same here

**Comment by housseindjirdeh** [comment]
Sorry for the trouble everyone, and the confusion on version supported. The feature should now work on latest canary (`14.0.5-canary.38`). We can keep this issue open until the feature hits stable.

For folks running into issues, can you try upgrading to latest canary? Please comment if you still any issues but that should resolve it.

**Comment by nmenic01** [comment]
I'm still getting Error: Unsupported Server Component type: undefined when using the GoogleAnalytics component on version `14.0.5-canary.38` @housseindjirdeh 

any ideas? :)

**Comment by drykberg** [comment]
> Sorry for the trouble everyone, and the confusion on version supported. The feature should now work on latest canary (`14.0.5-canary.38`). We can keep this issue open until the feature hits stable.
> 
> For folks running into issues, can you try upgrading to latest canary? Please comment if you still any issues but that should resolve it.

Are you guys thick or something, the ANALYTICS export was never added to any of the latest canaries. What's wrong with you?

**Comment by taujeng** [comment]
I'm on the latest version of canary: ``` "next": "^14.0.5-canary.39",  ``` and I'm still getting the error: ```Attempted import error: 'GoogleAnalytics' is not exported from '@next/third-parties/google' (imported as 'GoogleAnalytics').```

**Comment by drykberg** [comment]
> I'm still getting Error: Unsupported Server Component type: undefined when using the GoogleAnalytics component on version `14.0.5-canary.38` @housseindjirdeh
> 
> any ideas? :)

You probably have “@next/third-parties”: “^14.0.4” or lower installed. Check your package.json.

**Comment by housseindjirdeh** [comment]
@drykberg is right, please try updating `@next/third-parties` to latest canary (I should have clarified, my bad!). Older versions of the package itself are missing the Google Analytics export

**Comment by taujeng** [comment]
@housseindjirdeh @drykberg Ah yep that works for me. Thanks for the help!

**Comment by niels-bosman** [comment]
@nickmccurdy Think this is stable in 14.1.0 for both Next and next third parties.

**Comment by nickmccurdy** [comment]
Note that the package is technically still experimental, though `GoogleAnalytics` is now in `latest` and I don't see anything in its source that would cause issues in production.
