### ISSUE TITLE
Module not found: Can't resolve '#async_hooks'. Getting error with modules using sub-path imports

### ISSUE THREAD

**Issue by alaindeurveilher** [vercel/next.js#58052]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/sharp-spence-fyy83f

### To Reproduce

The codesandbox provided displays the error message when running the application.

> ./node_modules/p-limit/index.js (2:0)
Module not found: Can't resolve '#async_hooks'
Did you mean './#async_hooks'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules, /workspace).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
https://nextjs.org/docs/messages/module-not-found
Import trace for requested module:
./app/page.tsx

Explanation:

In one of my projects I am using p-limit. The last update of this dependency, version 5.0.0 takes advantage of [sub-path imports](https://nodejs.org/api/packages.html#subpath-imports), which apparently NextJS 14 does not handle very well, and reports the error above when compiling the page.

### Current vs. Expected behavior

Expected behaviour:

No error should be raised with the module p-limit used in a server component.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I did not actually try with canary on codesandbox because when canary, the appDir was said to be experimental. So the example given is with version 14.0.1 of NextJS.

**Comment by GabenGar** [comment]
What are the values of `"module"` and `"moduleResolution"` in your `tsconfig.json`?
Subpath imports is a nodejs/bundler thing, so what exactly is a context you expect `p-limit`, a nodejs package, to be called at? 
`p-limit` specifically depends on [`async_hooks`](https://nodejs.org/api/async_hooks.html) module of nodejs, so cannot be used outside of it, aka no browser.

**Comment by alaindeurveilher** [comment]
Hello,

In my `tsconfig.json` file I have the following default configuration:

```json
    "module": "esnext",
    "moduleResolution": "node",
```


I am using `p-limit` at the moment in the (server) action of a form to handle multiple promises in parallel. So it is performing on the server side.

**Comment by alaindeurveilher** [comment]
I tried, but changing `moduleResolution` to `bundler` did not fix the problem.

**Comment by GabenGar** [comment]
The crutch is [`p-limit`](https://github.com/sindresorhus/p-limit) uses subpath imports in its [`package.json`](https://github.com/sindresorhus/p-limit/blob/main/package.json#L18), to conditionally load [`async_hooks`](https://nodejs.org/api/async_hooks.html) with [a stub](https://github.com/sindresorhus/p-limit/blob/main/async-hooks-stub.js) outside of `node` environments. Possibly the nextjs bundler (turbopack and/or webpack) is being confused there, because, as far as package structure concerned, it should "work" as in not crash at module resolution time.

**Comment by Jeromearsene** [comment]
I have the same error with App Router structure.
I've `p-limit` in my `route.ts`:
<img width="209" alt="Capture d’écran 2024-03-18 à 09 49 28" src="https://github.com/vercel/next.js/assets/9333686/0d2d5b93-b1ac-4d3d-907e-669bda7d6aaf">

Any update ?

I've check closed issue on p-limit repo: https://github.com/sindresorhus/p-limit/issues/72

**Comment by RayRizzling** [comment]
had the same issue (next.js with app router) and solved it with the following at the next.config.mjs :
`/** @type {import('next').NextConfig} */
const nextConfig = {
    webpack: (config, { webpack }) => {
        // Adjust the resolve configuration
        config.resolve.fallback = {
            ...config.resolve.fallback,
            "async_hooks": false // Disable async_hooks fallback if causing issues
        };

        return config
    }
};

export default nextConfig
`

**Comment by RayRizzling** [comment]
had the same issue (next.js with app router) and solved it with the following at the next.config.mjs :
`/** @type {import('next').NextConfig} */
const nextConfig = {
webpack: (config, { webpack }) => {
// Adjust the resolve configuration
config.resolve.fallback = {
...config.resolve.fallback,
"async_hooks": false // Disable async_hooks fallback if causing issues
}

    return config
}
};

export default nextConfig`

**Comment by RayRizzling** [comment]
had the same issue (next.js with app router) and solved it with the following at the next.config.mjs :
`
/** @type {import('next').NextConfig} */
const nextConfig = {
webpack: (config, { webpack }) => {
// Adjust the resolve configuration
config.resolve.fallback = {
...config.resolve.fallback,
"async_hooks": false // Disable async_hooks fallback if causing issues
}

    return config
}
}

export default nextConfig
`

**Comment by RayRizzling** [comment]
had the same issue (next.js with app router) and solved it with the following at the next.config.mjs :

`
/** @type {import('next').NextConfig} */
const nextConfig = {
webpack: (config, { webpack }) => {
// Adjust the resolve configuration
config.resolve.fallback = {
...config.resolve.fallback,
"async_hooks": false // Disable async_hooks fallback if causing issues
}
    return config
}
}
export default nextConfig
`

**Comment by RayRizzling** [comment]
had the same issue (next.js with app router) and solved it with the following at the `next.config.mjs` 

`/** @type {import('next').NextConfig} */
const nextConfig = {
webpack: (config, { webpack }) => {
// Adjust the resolve configuration
config.resolve.fallback = {
...config.resolve.fallback,
"async_hooks": false // Disable async_hooks fallback if causing issues
}
    return config
}
}
export default nextConfig`

**Comment by mokkabonna** [comment]
For reference I solved this from failing in jest by having the following jest config: (this is inside my package.json)

```
 "jest": {
    "moduleNameMapper": {
         "^#async_hooks": "<rootDir>/node_modules/p-limit/async-hooks-stub.js"
    },
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/(?!yocto-queue|p-limit)"
    ]
  },
```

**Comment by ericmagnuson** [comment]
+1

**Comment by colinfindlay-nz** [comment]
The error generated is caused by specific (incorrect) behaviour in `webpack/enhanced-resolve`
This has been addressed in v5.17.1 - but afaik Next still relies on v5.16.0

https://github.com/webpack/enhanced-resolve/releases/tag/v5.17.1

**Comment by jellohouse** [comment]
I'm suddenly getting this issue as well (using cloudflare next-on-pages)... 

Is there a solution?

**Comment by cosier** [comment]
Suddenly also getting on cloudflare next-on-pages.
Rolled back a few commits, and still happening.

It just started..

**Comment by perryhong** [comment]
> 我也突然遇到了这个问题（使用 cloudflare next-on-pages）...
> 
> 有解决办法吗？

我也遇到了，今天刚刚发生，不知道cloudflare做了什么更新

**Comment by perryhong** [comment]
> I'm suddenly getting this issue as well (using cloudflare next-on-pages)...
> 
> Is there a solution?

have you fixed this problem? @jellohouse

**Comment by Gautham495** [comment]
I am getting the same in cloudflare pages

**Comment by quy-devbase** [comment]
@Gautham495 Try this solution: https://github.com/cloudflare/next-on-pages/issues/908#issuecomment-2502658653

**Comment by Gautham495** [comment]
It is working @quy-devbase - Thanks so much.
