### ISSUE TITLE
parallel routes: catch all nested under dynamic segment matches to the root

### ISSUE THREAD

**Issue by wlechowicz** [vercel/next.js#58272]
### Link to the code that reproduces this issue

https://github.com/wlechowicz/next14-catchall-repro

### To Reproduce

Caused by #58215, see https://github.com/vercel/next.js/pull/58215#issuecomment-1804319813

1. Start the application with `npm run dev`
2. Observe the error:
```
 ○ Compiling / ...
 ⨯ app\page.tsx
You cannot have two parallel pages that resolve to the same path. Please check /page and /[lang]/@modal/[...catchAll]/page. Refer to the route group docs for more information: https://nextjs.org/docs/app/building-your-application/routing/route-groups
```
3. If the `@modal`, `foo` and `bar` are moved up to the app root (outside of `[lang]`), no such error appears and the `catchAll` closes the "modal" as expected when any `/bar/*` non-intercepted Link is clicked.

### Current vs. Expected behavior

Previous behavior (prior to #58215) was that that `[...catchAll]` was not matching non-intercepted routes at all. See #50284
Current behavior with this change is that error quoted above is thrown at compile time.
Expected behavior is that catch-all matches to the correct parallel route, not root.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
  Platform: win32        
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.2-canary.27
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

<sub>[NEXT-1808](https://linear.app/vercel/issue/NEXT-1808/parallel-routes-catch-all-nested-under-dynamic-segment-matches-to-the)</sub>

**Comment by mrjasonroy** [comment]
Can confirm, 14.0.2 broke my parallel modals:

```
src/app/product/[id]/page.tsx
You cannot have two parallel pages that resolve to the same path. Please check /product/[id]/page and /(home)/@modal/[...catchAll]/page. Refer to the route group docs for more information: https://nextjs.org/docs/app/building-your-application/routing/route-groups
```

Downgrading to 14.0.1 fixed the issue for me

**Comment by tangye1234** [comment]
I also get this error: `You cannot have two parallel pages that resolve to the same path. Please check /(article)/contact/page and /(main)/@sider/[...catchAll]/page`

I think there is no need to check two parallel pages with different layout. because, the parallel routes can only be existed when it's layout dose not change to others.

**Comment by mrjasonroy** [comment]
Does anyone know if there is a workaround for 14.0.2 that can achieve the example modal? Or are we stuck on 14.0.1. The fix here would fix another issue I am have with default.tsx not being called in the base route of a parallel route in 14.0.1

**Comment by wlechowicz** [comment]
@mrjasonroy pre- #58215 there were other issues, where the catchAll on a parallel route was not matching at all (at least combined with an intercepting route). For me it's the same as you, there isn't a version where the example modal works, because before it doesn't dismiss with a catchAll, after that PR it throws those errors.

**Comment by tangye1234** [comment]
> Does anyone know if there is a workaround for 14.0.2 that can achieve the example modal? Or are we stuck on 14.0.1. The fix here would fix another issue I am have with default.tsx not being called in the base route of a parallel route in 14.0.1

workaround: using not-found instead of default. The only issue is not-found has no dynamic params.

**Comment by wlechowicz** [comment]
@tangye1234 @mrjasonroy  It looks like this is fixed in 14.0.3-canary.6 by #58368 I assume. 

cc @feedthejim

**Comment by mrjasonroy** [comment]
Still an error with me in 14.0.3. Maybe it has to do with how I am using parallel routes for slots and for things like modals, along with route groups for layouts.

I noticed that nested route groups don't work properly when using router.push() as well - I will investigate more and open an issue if I can figure out the core issue.

```
src/app/@header/chat/[id]/page.tsx
You cannot have two parallel pages that resolve to the same path. Please check /chat/[id]/page and //(home)/@modal/[...catchAll]/page
```

**Comment by feedthejim** [comment]
I don't see an error on the latest canary @wlechowicz can you confirm? I think there's another bug though.

**Comment by enchorb** [comment]
Getting this on 14.0.2+, fine on 14.0.1
