### ISSUE TITLE
`x-forwarded-host` header does not match `origin`

### ISSUE THREAD

**Issue by lewisnewson** [vercel/next.js#58295]
### Link to the code that reproduces this issue

https://github.com/lewisnewson/nextjs-14.0.2-bug-report

### To Reproduce

1. Clone the attached git repo
2. Deploy the `main` branch onto a basic Heroku dyno
3. Open the application in a new browser window
4. Observe the error printed in the Heroku server logs

### Current vs. Expected behavior

Currently:

1. Server action called
2. Fails on the server with the error "`x-forwarded-host` header with value `localhost:23380` does not match `origin` header with value `nextjs-14-0-2-bug-report-4ea064a57303.herokuapp.com` from a forwarded Server Actions request. Aborting the action. -- Error: Invalid Server Actions request."

What should happen:

1. Server action called
2. Executed correctly server-side (prints example todos)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #54~20.04.1-Ubuntu SMP Fri Oct 6 22:04:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Since upgrading from 14.0.1 to 14.0.2, deployments into a Heroku environment have now seen issues arise with the use of server actions. This can be shown in the example provided, when deployed to Heroku, loading the application prints the error message into the console of the dyno.

This issue does not happen when running `next dev` on a local machine, instead it only seems to appear when the application is deployed into production.

**Comment by JavierMartinz** [comment]
@lewisnewson https://github.com/vercel/next.js/issues/58019#issuecomment-1803925492

**Comment by lewisnewson** [comment]
> @lewisnewson [#58019 (comment)](https://github.com/vercel/next.js/issues/58019#issuecomment-1803925492)

Fantastic, adding their recommendation of the following sorted the issue for me;

**next.config.js**
`experimental.serverActions.allowedOrigins: ["https://nextjs-14-0-2-bug-report-4ea064a57303.herokuapp.com"]`

So for those needing a hand with this, the above should work as fix.

Thanks for digging that out @JavierMartinz

**Comment by nanmon** [comment]
can't get it working from VSCode desktop connected to a CodeSpace, tried with the following next.config.js
```js
{
	experimental: {
		serverActions: {
			allowedForwardedHosts: ['localhost'],
			allowedOrigins: ['http://localhost']
		},
	}
}
```

**Comment by mrxbox98** [comment]
Tried to add it to the next config but didn't work. Not sure where there is a breaking change in a minor version update anyways.

**Comment by devraj** [comment]
I found this thread following the same issue, and have tried `canary` and the current stable with the same results.

@lewisnewson I noticed your commend mentions that you had this working in `14.0.1`, I am seeing different results having downgraded back to `14.0.1`, there are no error messages but the server action doesn't seem to make `fetch` call to my REST service (validated by monitoring the logs of the REST API server).

**Comment by eyenalxai** [comment]
Issue also happens for me when running `next dev` on a local machine if you access app not via localhost but through another address in local network, like `192.168.1.2:3000`. Works without errors on 14.0.1.

**Comment by mertafor** [comment]
I've had the same issue with nginx. I tried using serverActions.allowedOrigins and also experimental.serverActions.allowedOrigins / allowedHosts but didn't help. Downgrading to 14.0.1 fixed the problem. Hope the next update fix this.

**Comment by lucgagan** [comment]
Downgrading to v14.0.0 makes it work.

Next.js team keeps adding breaking changes like it is a competition.

**Comment by lucgagan** [comment]
Downgrading to v14.0.0 makes it work.

**Comment by michaelangeloio** [comment]
This also doesn't work for me. Using Nx as well.

**Comment by GVALFER** [comment]
The same here after update to 14.0.2

```
x-forwarded-host` header with value `localhost:3000` does not match `origin` header with value `1xx.2xx.1xx.71:3000` from a forwarded Server Actions request. Aborting the action.
 ⨯ Error: Invalid Server Actions request.
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
```

**Comment by eyn** [comment]
This will be fixed by #58500

**Comment by TotomInc** [comment]
This is fixed in 14.0.3, upgrade to next 14.0.3 and the error will be gone.

**Comment by lewisnewson** [comment]
Confirmed this is now solved in version 14.0.3.

Thanks all!

**Comment by thibautvdu** [comment]
@TotomInc 

I came across this issue ; upgrading to 14.0.3 did not solve it for me, but downgrading to 14.0.0 did.
The POST request goes through when I replay it with all the X-Forwarded-**** headers removed. You can find the problematic headers below to reproduce the error : 

```
X-Forwarded-For: 10.47.104.50
X-Forwarded-For: 34.159.59.249
X-Forwarded-Host: waba-stack-01.360dialog.io
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
```

**Comment by fwcontact** [comment]
> @TotomInc
> 
> I came across this issue ; upgrading to 14.0.3 did not solve it for me, but downgrading to 14.0.0 did. The POST request goes through when I replay it with all the X-Forwarded-**** headers removed. You can find the problematic headers below to reproduce the error :
> 
> ```
> X-Forwarded-For: 10.47.104.50
> X-Forwarded-For: 34.159.59.249
> X-Forwarded-Host: waba-stack-01.360dialog.io
> X-Forwarded-Port: 443
> X-Forwarded-Proto: https
> X-Forwarded-Proto: https
> X-Forwarded-Scheme: https
> ```

same here. not fixed in 14.0.3.

**Comment by kemaltf** [comment]
confirmed, it fixed in 14.0.3

**Comment by Colossus** [comment]
This doesn't work if using a custom port. I'm still getting the following in 14.0.3:

`x-forwarded-host` header with value `213.xxx.xxx.xxx` does not match `origin` header with value `213.xxx.xxx.xxx:3003` from a forwarded Server Actions request. Aborting the action.

**Comment by Lodimup** [comment]
Not fixed for us too.

We deploy on k8s and nextjs is behind nginx, and we get this.
```
`x-forwarded-host` header with value `SERVICE_NAME` does not match `origin` header with value `subdomain.domain.com` from a forwarded Server Actions request. Aborting the action.
```

**Comment by Colossus** [comment]
I fixed this on my end by just returning from nginx whatever next.js expected instead of the standard `$proxy_add_x_forwarded_for`

**Comment by Lodimup** [comment]
> I fixed this on my end by just returning from nginx whatever next.js expected instead of the standard `$proxy_add_x_forwarded_for`

like this?
```
...
http {
    upstream frontend-main {
        server frontend-main;
    }

    server {
        listen 80;
        server_name subdomain.domain.com;

        location / {
            proxy_set_header x-forwarded-host "subdomain.domain.com";
            proxy_pass http://frontend-main;
        }
    }
}

```

**Comment by Colossus** [comment]
Yes, on my end it looks like this: `proxy_set_header X-Forwarded-Host $host:3003`

**Comment by Lodimup** [comment]
> Yes, on my end it looks like this: `proxy_set_header X-Forwarded-Host $host:3003`

confirmed working but I think it's hacky

**Comment by SmileSydney** [comment]
I'm working on 14.0.3 in Codespaces and still getting error:
```
`x-forwarded-host` header with value `psychic-umbrella-xr45956gpg9crrw-3000.app.github.dev` does not match `origin` header with value `localhost:3000` from a forwarded Server Actions request. Aborting the action.
 ⨯ Error: Invalid Server Actions request.
```

**nextjs.config.ts**
```
const nextConfig = {
    experimental: {
		serverActions: {
			allowedOrigins: ["https://psychic-umbrella-xr45956gpg9crrw-3000.app.github.dev"]
			},
	}
  }  
module.exports = nextConfig
```

**Comment by Myks92** [comment]
14.0.3 Not fixed for us too.

**Comment by MarvinVrdoljak** [comment]
Same for me - not fixed.

**Comment by colin-kudos** [comment]
`  proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;`

This fixed it for me

**Comment by Lodimup** [comment]
> ```
>     proxy_pass http://127.0.0.1:3000;
>     proxy_http_version 1.1;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-Host $host;
>     proxy_set_header X-Forwarded-Proto $scheme;
> ```
> 
> This fixed it for me

this also resolves https://github.com/vercel/next.js/issues/58914

**Comment by Jonas-PFX** [comment]
> @TotomInc
> 
> I came across this issue ; upgrading to 14.0.3 did not solve it for me, but downgrading to 14.0.0 did. The POST request goes through when I replay it with all the X-Forwarded-**** headers removed. You can find the problematic headers below to reproduce the error :
> 
> ```
> X-Forwarded-For: 10.47.104.50
> X-Forwarded-For: 34.159.59.249
> X-Forwarded-Host: waba-stack-01.360dialog.io
> X-Forwarded-Port: 443
> X-Forwarded-Proto: https
> X-Forwarded-Proto: https
> X-Forwarded-Scheme: https
> ```

Based on the fact that you have multiple `x-forwarded-proto` headers, sounds like you might be running in to [this issue](https://github.com/vercel/next.js/pull/58824).

For those that run nginx with `proxy_set_header X-Forwarded-Proto ...`, nginx will strip out the multiple headers, so thats a possible workaround.

**Comment by eduardobertozi** [comment]
> > @lewisnewson [#58019 (comment)](https://github.com/vercel/next.js/issues/58019#issuecomment-1803925492)
> 
> Fantastic, adding their recommendation of the following sorted the issue for me;
> 
> **next.config.js** `experimental.serverActions.allowedOrigins: ["https://nextjs-14-0-2-bug-report-4ea064a57303.herokuapp.com"]`
> 
> So for those needing a hand with this, the above should work as fix.
> 
> Thanks for digging that out @JavierMartinz

Thanks!! It solve my problem.

**Comment by landsman** [comment]
I had the same problem on AWS ECS Fargate where I using nginx in side container as reverse proxy for Next.js.

Here is my template for nginx.config that is working great:

```conf
events {
    worker_connections 1024;
}

http {
  resolver 127.0.0.11 valid=30s ipv6=off;

  # Nginx will allocate up to 16 buffers, each of size 32 KB, for each client connection.
  # These buffers are used to temporarily store parts of the response from the upstream server before forwarding them to the client.
  # Adjusting the number and size of buffers can impact the memory usage and performance of Nginx when serving large responses.
  proxy_buffers 16 32k;

  # Nginx configures a buffer of 64 KB to read the response from the upstream server.
  # This buffer is used to temporarily store chunks of the response as it is being received.
  # The size of this buffer can affect the efficiency of data transfer between Nginx and the upstream server.
  # A larger buffer may reduce the number of read operations at the expense of increased memory usage.
  proxy_buffer_size 64k;

  # This passes the host header from the client to the SSL handshake with the proxied server
  # Useful when the proxied server relies on Server Name Indication (SNI)
  # This way, the proxied server can present the correct SSL certificate matching the client's host header
  proxy_ssl_server_name on;

  server {
      listen 80;
      listen [::]:80;
      server_name ${DOMAIN_NAME};

      # Home page
      location = / {
          proxy_pass ${WEB_FLOW_URL};
          proxy_set_header Host ${WEB_FLOW_HOST};
      }

      # Other Webflow pages
      location = /contact {
          proxy_pass ${WEB_FLOW_URL}/contact;
          proxy_set_header Host ${WEB_FLOW_HOST};
      }

      location = /pricing {
          proxy_pass ${WEB_FLOW_URL}/pricing;
          proxy_set_header Host ${WEB_FLOW_HOST};
      }

      location = /privacy {
          proxy_pass ${WEB_FLOW_URL}/privacy;
          proxy_set_header Host ${WEB_FLOW_HOST};
      }

      location = /cookies {
          proxy_pass ${WEB_FLOW_URL}/cookies;
          proxy_set_header Host ${WEB_FLOW_HOST};
      }

      location = /terms {
          proxy_pass ${WEB_FLOW_URL}/terms;
          proxy_set_header Host ${WEB_FLOW_HOST};
      }

      location = /jobs {
          proxy_pass ${WEB_FLOW_URL}/jobs;
          proxy_set_header Host ${WEB_FLOW_HOST};
      }

      # next.js folder with static assets
      location /static/ {
          expires 1d;
          add_header Cache-Control "public, max-age=31536000, immutable";
      }

      # Everything else goes to next.js web app
       location / {
          proxy_pass ${NEXT_JS_URL};
          proxy_http_version 1.1;
          proxy_read_timeout 900;

          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';

          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_cache_bypass $http_upgrade;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      client_header_timeout 60;
      client_body_timeout 60;
      keepalive_timeout 60;

      gzip on;
      gzip_comp_level 4;
      gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
  }
}
```

and script to replace these variables in template:

```sh
#!/bin/sh

# this script is used to replace the environment variables in the nginx.conf file
# env variables are set by infrastructure, ECS Task Definition

# shellcheck disable=SC2016
envsubst '$DOMAIN_NAME $NEXT_JS_URL $WEB_FLOW_HOST $WEB_FLOW_URL' < /etc/nginx/template.nginx.conf > /etc/nginx/nginx.conf

exec nginx -g 'daemon off;'
```

dockerfile
```dockerfile
FROM nginx:alpine

# needed to use envsubst in start-nginx.sh
RUN apk add busybox-extras

# Copy the Nginx config
COPY template.nginx.conf /etc/nginx/template.nginx.conf
COPY start-nginx.sh /start-nginx.sh

RUN chmod +x /start-nginx.sh

# Forward request logs to Docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80

CMD ["/start-nginx.sh"]
```

**Comment by jovanhartono** [comment]
i'm on v14.0.3
