### ISSUE TITLE
Attempted import error: 'webgl-sdf-generator' does not contain a default export (imported as 'createSDFGenerator')

### ISSUE THREAD

**Issue by dincerpece** [vercel/next.js#58557]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.1
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

there is no

### What browser are you using? (if relevant)

Chrome 119.0.6045.160

### How are you deploying your application? (if relevant)

localhost

### Describe the Bug

There was no problem with my @react-three/fiber package. While the Next 14.0.1 version worked very smoothly, I started to receive warnings in the next 14.0.2, 14.0.3 and canary versions. I updated all relevant packages but the problem persists. The packages and versions that may be relevant are as follows:

@react-three/fiber: 8.15.11
@react-three/drei: 9.88.16
three: 0.158.0

The warning is as follows: Attempted import error: 'webgl-sdf-generator' does not contain a default export (imported as 'createSDFGenerator').

![Screenshot_6](https://github.com/vercel/next.js/assets/57527680/37b1498a-ed5e-4f91-81a1-3f46b00be193)

### Expected Behavior

I expect it to work without warning, just like it did in Next 14.0.1.

### To Reproduce

I updated the relevant packages and their next versions, but the result is the same. I get the same warning in both development and production mode.

**Comment by rgbjoy** [comment]
Yes I'm getting it too ` ⚠ ./node_modules/troika-three-text/dist/troika-three-text.esm.js
Attempted import error: 'webgl-sdf-generator' does not contain a default export (imported as 'createSDFGenerator').

Import trace for requested module:
./node_modules/troika-three-text/dist/troika-three-text.esm.js
./node_modules/@react-three/drei/core/Text.js
./node_modules/@react-three/drei/index.js
./components/background.tsx
./components/siteLayout.tsx`

**Comment by hmellahi** [comment]
hey @dincerpece, I've encountered the same issue. Have you found a solution? If so, could you please share it?

**Comment by emnul** [comment]
I'm also encountering this issue

**Comment by DevaPandiyan** [comment]
i also facing same issue.....

**Comment by mkermani144** [comment]
Seems an issue in newer next versions. `14.0.0` works but `14.0.3` crashes.

**Comment by Redowan-Ahmed** [comment]
I'm also facing the same issue in NextJst 14.0.3

**Comment by CodyJasonBennett** [comment]
I merged https://github.com/pmndrs/drei/pull/1726 in Drei 9.88.17 which contains a work-around so you can consume Drei, but let me know if this does/doesn't work when using `Text` and whether you're using the app directory.

WRT to Next and possibly a compiler regression, the specific syntax used in `webgl-sdf-generator` is `export { SDFGenerator as default };`, but it's unclear whether it's resolving as ESM to begin with via non-standard `module` or its default UMD target from `main`.

**Comment by 4lejandrito** [comment]
> I merged [pmndrs/drei#1726](https://github.com/pmndrs/drei/pull/1726) in Drei 9.88.17 which contains a work-around so you can consume Drei, but let me know if this does/doesn't work when using `Text` and whether you're using the app directory.
> 
> WRT to Next and possibly a compiler regression, the specific syntax used in `webgl-sdf-generator` is `export { SDFGenerator as default };`, but it's unclear whether it's resolving as ESM to begin with via non-standard `module` or its default UMD target from `main`.

The Issue still occurs with `"@react-three/drei": "9.88.17"`.

**Comment by emnul** [comment]
> I merged https://github.com/pmndrs/drei/pull/1726 in Drei 9.88.17 which contains a work-around so you can consume Drei, but let me know if this does/doesn't work when using Text and whether you're using the app directory.

This warning still persists for me. I'm only importing the OrbitControls component in my case. I tested using the Text component and nothing seems to break, but the warning is still there. Lmk if there's anything I can do to help. Relatively new to Next and Three, but I can probably figure something out if pointed in the right direction.

**Comment by gonghaibo** [comment]
As long as cavas is used it will exist.

**Comment by CodyJasonBennett** [comment]
If someone could share an example or repository, that would help us track this down.

**Comment by dincerpece** [comment]
Hi, @CodyJasonBennett 

> If someone could share an example or repository, that would help us track this down.

I simply prepared a repository, hope it helps: https://codesandbox.io/p/sandbox/nextjs-three-fb-1-csr869

**Comment by CodyJasonBennett** [comment]
Unfortunately, that affirms that there is no way for us to work around this in Drei and that it's an issue with the app directory. We've received a host of issues from its compiler all over the three.js ecosystem since the adoption of SWC. You'll have to pin to Next 14.0.1 or earlier until a fix becomes available.

**Comment by dincerpece** [comment]
> Unfortunately, that affirms that there is no way for us to work around this in Drei and that it's an issue with the app directory. We've received a host of issues from its compiler all over the three.js ecosystem since the adoption of SWC. You'll have to pin to Next 14.0.1 or earlier until a fix becomes available.
> 
> ```json
> {
>   "dependencies": {
>     "next": "14.0.1"
>   }
> }
> ```

As I mentioned in my description, while there is no problem in 14.0.1, this warning occurs in later versions and canaries.

**Comment by jakst** [comment]
Same issue for the `@pathfinder-ide/react` package. I created a separate issue here https://github.com/vercel/next.js/issues/58831 with a minimal reproduction attached.

**Comment by CodyJasonBennett** [comment]
See my comment in https://github.com/vercel/next.js/issues/58557#issuecomment-1818922996 and I've since confirmed that Next is reading the `module` package field all the way down.

As per my previous comment, and now evidenced by #58831, I would expect `export { foo as bar }` to be causing the issue here.
