### ISSUE TITLE
Google Tag Manager event "History change" is no longer fired in Next.js 14.0.3

### ISSUE THREAD

**Issue by manuelseisl** [vercel/next.js#58924]
### Link to the code that reproduces this issue

https://github.com/manuelseisl/next-js-demo

### To Reproduce

1. Change GTM ID in layout.jsx
2. Start application
3. Go to GTM preview mode
4. Navigate between pages

### Current vs. Expected behavior

The Google Tag Manager event "History change" is no longer fired in Next.js 14.0.3.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.8.0
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

I tested my reproduction against different versions and canary releases, and the first one that introduced the bug was “14.0.3”, when switching back to “14.0.2” it works.

**Comment by vKongv** [comment]
I thought this was the default behavior when I first using Nextjs with 14.0.3. I added a template.tsx to trigger GTM track event manually :/

**Comment by cduff** [comment]
I just checked and this was breaking Google Tag Manager / Analytics for me. Rolling back to 14.0.2 fixes for now.

**Comment by cduff** [comment]
> @cduff @vKongv @manuelseisl Are you having trouble keeping track of all the pages? I use import { GoogleTagManager } from "@next/third-parties/google"; and for the page to appear in Google Analytics panel, I have to refresh page manually to see that someone has visited some page

@Bart3kL Do you have it set up to trigger on History Change? This is required due to hydration.

**Comment by Bart3kL** [comment]
@cduff Do you have it done somewhere and can you show it?

**Comment by vKongv** [comment]
> > @cduff @vKongv @manuelseisl Are you having trouble keeping track of all the pages? I use import { GoogleTagManager } from "@next/third-parties/google"; and for the page to appear in Google Analytics panel, I have to refresh page manually to see that someone has visited some page
> 
> @Bart3kL Do you have it set up to trigger on History Change? This is required due to hydration.

I did it in app/template.tsx like the [doc said](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#templates), thought it was a default behavior to do this until I see this issue

```tsx
'use client';
import { useEffect } from 'react';
import { sendGTMEvent } from '@next/third-parties/google';

export default function Template({ children }: { children: React.ReactNode }) {
  const isProd = process.env.NODE_ENV === 'production';

  useEffect(() => {
    isProd && process.env.NEXT_PUBLIC_GTM_ID && sendGTMEvent({ event: 'page_view' });
  }, [isProd]);

  return <div>{children}</div>;
}
```

**Comment by philwolstenholme** [comment]
The GTM [history change event](https://support.google.com/tagmanager/answer/7679322) should 'just work', but recently Next patched `history` `pushState` and `replaceState`, presumably causing this bug.

**Comment by cduff** [comment]
> @cduff Do you have it done somewhere and can you show it?

@Bart3kL I just have GTM set up in the root layout like: https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-tag-manager

And the tag is configured like this:

![image](https://github.com/vercel/next.js/assets/7855146/534cf5bb-c210-4d16-b960-837ea0aaa91c)

**Comment by philwolstenholme** [comment]
This issue should be resolved by https://github.com/vercel/next.js/commit/8ff1368fdbba5f8425ce9913a2f13dc6ce1dd994, I think

**Comment by cduff** [comment]
Fixed in 14.0.4 for me.

**Comment by oalexdoda** [comment]
Fixed on 14.0.4 but that version (and 14.0.5-canary) has a bug where all imports break.

And because of the complexity of the setup there's no way to add a minimal repro, so can't open an issue:
- https://github.com/vercel/next.js/issues/59535
- https://github.com/vercel/next.js/issues/59386

Gonna be stuck on 14.0.3 for a while...

**Comment by benyaminl** [comment]
@vKongv Hello, I tried yours and use different variable for the useEffect, but seems it won't re-render between pages using <Link> Component, is there other thing that I need to set in order to re-render the Template.tsx on /app/template.tsx? 

Thank you

**Comment by dominicfallows** [comment]
I'm on `14.1.4` and noticed this still isn't working - that is I get no [History Change trigger](https://support.google.com/tagmanager/answer/7679322) in GTM

**Comment by catlan** [comment]
> I'm on 14.1.4 and noticed this still isn't working - that is I get no [History Change trigger](https://support.google.com/tagmanager/answer/7679322) in GTM

Haven't retested with the latest version, but had to move the _GoogleTagManager_ into _head_ at some point for History Change trigger to work.

```
      <head>
        <GoogleTagManager gtmId="GTM-XXXXXXXX" />
      </head>
```

**Comment by HarveyPeachey** [comment]
`14.2.3` doesn't seem to be working automatically for page views, even when following the [docs](https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#tracking-pageviews).

**Comment by Borgo99** [comment]
`14.2.4` it's still not working

**Comment by dalytekab** [comment]
`15.1.4` and it's still not working

**Comment by marcoshernanz** [comment]
Thanks for reporting this. The 14.0.3 regression was caused by App Router bypassing wrapped History API methods. #58861 fixed this and shipped in 14.0.4. Wrapped `pushState` calls now work on 14.0.4, 14.2.4, 16.3.1, and current canary. Closing as fixed. If this still reproduces on a current release, please open a new issue with a current minimal reproduction.
