### ISSUE TITLE
Not-found broken with multiple root layouts

### ISSUE THREAD

**Issue by stychu** [vercel/next.js#59180]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/blissful-fog-nflrh6

### To Reproduce

1. Open sandbox and click `not found page`
2. It will redirect to the generic nextjs 404 page

### Current vs. Expected behavior

Generic 404 Nextjs error page is shown when I navigate to any unknow urls.

 I expect to be redirected to my custom 404 UI handler

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.9.0
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

> Good to know: In addition to catching expected notFound() errors, the root app/not-found.js file also handles any unmatched URLs for your whole application. This means users that visit a URL that is not handled by your app will be shown the UI exported by the app/not-found.js file.

 https://nextjs.org/docs/app/api-reference/file-conventions/not-found
 --- 

According to the docs in order to be able to handle any unmatched URLs in the application we are bound to the fixed path for the not-found UI that must be placed at the root of the app -> `app/not-found.js` 

This breaks not-found custom UI handling as per provided example.

I've 2 root layout groups https://nextjs.org/docs/app/building-your-application/routing/route-groups#creating-multiple-root-layouts

1. Auth group (which is publicly accessible)
2. Main group (which is accessible if user is authenticated and basically contains the whole app routing)

With this setup and not having app root not-found file it's not possible to be able to handle 404 with custom UI as any 404 url handling is bound to the root `app/not-found.tsx`.
I believe this should not be bound to the fixed path but rather the `top most` existing `not-found` file and if no file exist then generic 404 should intercept. This also applies for the error.tsx I believe.

**Comment by stychu** [comment]
Seems this is same/similar issue. How come multiple root layouts can't have it's own 404/error handlers..

https://github.com/vercel/next.js/issues/54980

**Comment by stychu** [comment]
Can I get any feedback on this? It this is a bug or I do something wrong?
@huozhi you seem to have some knowledge around this topic as I saw some changes recently made for handling files in this PR  https://github.com/vercel/next.js/pull/54931.

**Comment by devjiwonchoi** [comment]
Please see https://github.com/vercel/next.js/issues/55191#issuecomment-1985794575

**Comment by iamlinkus** [comment]
Looks like the fix commit has been reverted 15 hours ago (https://github.com/vercel/next.js/pull/64516). Is there an update when we'll get this working?

**Comment by devjiwonchoi** [comment]
No didn't get reverted, it was cuz of the CI. It's fixed now :) hope you could check it out and close this issue as well.

**Comment by iamlinkus** [comment]
Ok, checked 14.2.1 (which has that fix), and the problem outlined in the OP message still exists. It's a huge problem for people that are working with Payload CMS 3.0 (https://github.com/payloadcms/payload-3.0-demo/issues/84#issuecomment-2057874607), which uses two adjacent group routes and the structure is the following:

![CleanShot 2024-04-16 at 13 46 46@2x](https://github.com/vercel/next.js/assets/16874184/61410b2e-2a05-4816-b230-6ac214da97fd)

We need both route groups completely separated, both having their own root layouts and their own not-found components. With how things are currently, there is no way of doing that apart from dirty workarounds. I think most people experiencing this issue expected the behavior to be able to simply add `not-found.js` to each group route and render in each their own error component without artificially adding root layouts or root not-founds.

**Comment by devjiwonchoi** [comment]
@iamlinkus Don't think it appended to the stable version, have you checked on canary?

**Comment by iamlinkus** [comment]
> @iamlinkus Don't think it appended to the stable version, have you checked on canary?

Checked the `14.3.0-canary.0`, which includes that fix. I can confirm that it now lets you have a `not-found` in the root  (`/app`), without a root layout (`RootLayout`) in the root (`/app`), which is great. However, for my use case (and any people using Payload 3.0), who want their websites to have a custom not-found - it still doesn't solve the problem.

What we need: the ability for each group route (including a group route, regardless if it's a root (homepage), or a sub-page (/admin)) to have a custom not-found. Currently, even with your fix, if I want to have a custom not-found component for my homepage (the (app) group route from the screenshot in my previous comment), the only way I can do that is adding a `not-found` component to the root `/app` folder. This has two problems:

1. I'm not able to use the root layout that's within my `(app)` group route.
2. All group routes inherit that component, so that means my `(payload)` group route will have the global not-found, even though Payload has their own `not-found` component (which I do not want to override).

Also, even with that fix, next.js doesn't seem to care about the `not-found` component in my `(app)` group route. Maybe because it's for the root of the website, but inside a route group folder?

**Comment by iamlinkus** [comment]
I've created a devbox to recreate the issue.

With this file structure:
![CleanShot 2024-04-17 at 12 02 35@2x](https://github.com/vercel/next.js/assets/16874184/b96c9cad-8549-4f82-9658-b679b843257f)

None of the not-found components are rendered. Only the generic next.js one is.

[Here's the devbox.](https://codesandbox.io/p/devbox/not-found-in-route-groups-fvnyt7)

**Comment by csumudu** [comment]
Facing the same issue, any workaround?

**Comment by kunalkeshan** [comment]
Has anyone found a fix for this yet? Sure we can have a workaround of [catch-all segments](https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes#catch-all-segments) but in this case, the page would return a status code of 200, while actual not found pages would preferably have a 404 status code returning along with it for SEO purposes too.

**Comment by jademh** [comment]
+1 following this issue

**Comment by pmillspaugh** [comment]
+1 for allowing `not-found.tsx` to work with multiple root layouts. But in the meantime, for anyone wondering what the [catch-all segment](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#catch-all-segments) workaround might look like:

```
app/
├── (marketing)/
│   ├── layout.tsx
│   └── page.tsx
├── (auth)/
│   ├── dashboard/
│   ├── settings/
│   └── layout.tsx
└── [...404]/
    ├── layout.tsx
    └── page.tsx
```

This does not solve the HTTP status code issue. This enables a custom 404 page with multiple root layouts, but that 404 page will return 200. It looks like there was some discussion of allowing [setting HTTP status on server components](https://github.com/vercel/next.js/discussions/53225), but unfortunately it stalled.

FWIW, I also tried using a catch-all segment plus a route handler, but I ran into compiler errors trying to render a server component from a route handler. _This code does not compile_, but I'll share in case anyone can take it across the finish line:

```ts
import { renderToString } from "react-dom/server";
import { NextResponse } from "next/server";
import NotFound from "~/components/404";

export function GET() {
  const html = renderToString(<NotFound />);

  return new NextResponse(html, {
    status: 404,
    headers: { "Content-Type": "text/html" },
  });
}
```

Or another potential workaround would be to return static HTML for your custom 404 page, like:

```ts
import { NextResponse } from "next/server";

export function GET() {
  return new NextResponse(`<html>Add your custom 404 page here</html>`, {
    status: 404,
    headers: { "Content-Type": "text/html" },
  });
}
```

**Comment by Chukwu3meka** [comment]
What worked for me if I don't want my root not-found page applying to missing pages in sub layouts, what I did was to create a fallback in each layouts this way

`\app\unique-layout\[...fallback]\page.tsx`

Make sure to include the square brackets for fallback, else it won't work


> ...happy hacking 🧑🏽‍💻
