### ISSUE TITLE
New Dev-Server (14.0.4->14.1.0 or 14.1.1) broken config combination: missing required error components, refreshing...

### ISSUE THREAD

**Issue by fix-me** [vercel/next.js#61134]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Enterprise
Binaries:
  Node: 18.19.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.10 // Latest available version is detected (14.1.1-canary.10).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: export
```

### Which example does this report relate to?

npx create-next-app@latest

### Describe the Bug

After updating from Next.js version 14.0.4 to 14.1.0, or when installing the latest version, the newly introduced dev-server exhibits a bug. When the Next.js configuration is set to output: "export" and distDir: "out", rendering fails, and the dev-server resolves _error with the output: "missing required error components, refreshing...".

### Expected Behavior

The dev-server should handle the specified configuration (output: "export" and distDir: "out") without causing issues with rendering and error components. The application should render as expected without encountering missing error components.

### To Reproduce

1. Set up a Next.js project with the provided configuration:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
  distDir: "out",
};

export default nextConfig;
```

2. Run the project using Next.js version 14.1.0 or the latest version. `npm run dev`
3. Observe the dev-server behavior and the error output mentioned above.

**Comment by fix-me** [comment]
Additionally, I have run the server in debug mode and stepped through the request. It appears to be searching for the server files in the 'out' directory and encounters a failure when accessing the font manifest. While 'out' is essential for the pipeline during the build process, the dev-server should have no trouble locating its resources in the '.next' directory.

**Comment by fix-me** [comment]
Sorry, I used the 'example' issue button, thinking I should report it with an example. However, the core is affected here!

**Comment by DarkGuy10** [comment]
Same as #61041 and #61105

**Comment by AlbinoGeek** [comment]
This should have huge attention as it's **a regresssion in a minor version**.

**Comment by Alex-Costea** [comment]
I encountered the same problem.

**Comment by AlbinoGeek** [comment]
This should have been fixed as per #61105

**Comment by fix-me** [comment]
Thx for the info, I'll close it with the next stable release that fixes it.

**Comment by atstoyanov** [comment]
It worked for me in 14.1.1-canary.58 but still broken in newly released 14.1.1

**Comment by fix-me** [comment]
It seems, in 14.1.1 this error is not fixed

![image](https://github.com/vercel/next.js/assets/43244072/2c9a2405-1b43-4783-964f-1073448f01f2)

**Comment by atstoyanov** [comment]
If you check the release notes for 14.1.1 and 14.1.2 you'll see that #62064 is not included in either of them. So stick to the canary build until it is released.

**Comment by samcx** [comment]
This was included in https://github.com/vercel/next.js/releases/tag/v14.1.3!
