### ISSUE TITLE
"Rendered more hooks than during previous render" when using App Router

### ISSUE THREAD

**Issue by mynameisankit** [vercel/next.js#63121]
### Link to the code that reproduces this issue

[Link](https://codesandbox.io/p/devbox/redirect-repro-f2tsjq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltmlqf3g00073b6jezir0a4o%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltmlqf3f00023b6jpc0dfmz3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltmlqf3g00043b6jpro52tyg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltmlqf3g00063b6jkxiv9b6x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltmlqf3f00023b6jpc0dfmz3%2522%253A%257B%2522id%2522%253A%2522cltmlqf3f00023b6jpc0dfmz3%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltmlqf3g00063b6jkxiv9b6x%2522%253A%257B%2522id%2522%253A%2522cltmlqf3g00063b6jkxiv9b6x%2522%252C%2522activeTabId%2522%253A%2522cltmlv4on00tm3b6je8zsvnx6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltmlv4on00tm3b6je8zsvnx6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fversions%252Fv1%2522%257D%255D%257D%252C%2522cltmlqf3g00043b6jpro52tyg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltmlqf3g00033b6j3opcl07x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cltmlqf3g00043b6jpro52tyg%2522%252C%2522activeTabId%2522%253A%2522cltmlqf3g00033b6j3opcl07x%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

For more reproductions, see:
- https://github.com/vercel/next.js/issues/63388
- https://github.com/vercel/next.js/issues/78396
- https://github.com/vercel/next.js/issues/80483

### To Reproduce

1. Start the application on port 3000
2. Goto `<base-url>/versions/v1`
3. Wait for a few seconds till the error screen is displayed
4. Click on `Goto Version v2`

### Current vs. Expected behavior

I expected to be redirected to `<base-url>/versions/v2` but instead a client-side react error is triggered with the following stack trace

```
Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom.development.js:11337:1)
    at updateMemo (react-dom.development.js:12470:1)
    at Object.useMemo (react-dom.development.js:13417:1)
    at useMemo (react.development.js:1777:1)
    at Router (app-router.js:215:58)
    at renderWithHooks (react-dom.development.js:11021:1)
    at updateFunctionComponent (react-dom.development.js:16184:1)
    at beginWork$1 (react-dom.development.js:18396:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20498:1)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20547:1)
    at invokeGuardedCallback (react-dom.development.js:20622:1)
    at beginWork (react-dom.development.js:26813:1)
    at performUnitOfWork (react-dom.development.js:25637:1)
    at workLoopSync (react-dom.development.js:25353:1)
    at renderRootSync (react-dom.development.js:25308:1)
    at recoverFromConcurrentError (react-dom.development.js:24525:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:24470:1)
    at workLoop (scheduler.development.js:256:1)
    at flushWork (scheduler.development.js:225:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:534:1)
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.15.1
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

I tested my reproduction on the following versions:-
1. `13.4.19`
2. `14.1.0`

**Comment by sirajtahra** [comment]
+ 1

**Comment by lifeisegg123** [comment]
I have dig into this issue and found that call of `useThenable` inside of `use` hook doesn't seem to work properly.
So, I tried change the implementation of [useUnwrapState](https://github.com/vercel/next.js/blob/48396e80ae38caed139b7fd9fc66f7291a33c3af/packages/next/src/client/components/use-reducer-with-devtools.ts#L79) like this in my local machine, it worked.

```ts
function useUnwrapState(_state: ReducerState): AppRouterState {
  const [state, setState] = useState(_state);
  useEffect(()=>{
     if (isThenable(_state)) {
       _state.then(setState);
    } else {
      setState(_state)
    }
  }, [_state])

  return state
}
```

Maybe is it related to `use` hook and `startTransition` [issue](https://github.com/facebook/react/pull/29670)?

**Comment by jetaggart** [comment]
We're seeing this with a component that renders nothing and only redirects. Only happens in production:

```
export default async function OnboardingPage() {
  const status = await gateway.onboarding.status.get()

  match(status.onboarding.currentStep)
    .with(OnboardingStatusNotStarted, () => {
      redirect("/onboarding/start")
    })
    // ...
    .otherwise(() => {
      throw new Error(
        `Invalid onboarding status ${status.onboarding.currentStep}`
      )
    })

  return <></>
}
```

**Comment by hunghuy201280** [comment]
+1

**Comment by himself65** [comment]
My error stack here

```log
(anonymous) @ react-dom-client.production.js:11023
x @ scheduler.production.js:151
error-boundary-callbacks.ts:56 Error: Minified React error #310; visit https://react.dev/errors/310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lQ (react-dom-client.production.js:3494:1)
    at Object.aw [as useMemo] (react-dom-client.production.js:4161:1)
    at react.production.js:515:1
    at M (app-router.tsx:252:38)
    at lM (react-dom-client.production.js:3373:1)
    at oh (react-dom-client.production.js:6016:1)
    at o_ (react-dom-client.production.js:7012:1)
    at ic (react-dom-client.production.js:10829:1)
    at react-dom-client.production.js:10710:35
    at is (react-dom-client.production.js:10711:1)
    at u9 (react-dom-client.production.js:10289:1)
    at ij (react-dom-client.production.js:11606:1)
    at MessagePort.x (scheduler.production.js:151:1)
overrideMethod @ hook.js:608
(anonymous) @ console.js:36
s @ error-boundary-callbacks.ts:56
ot @ react-dom-client.production.js:5580
e.callback @ react-dom-client.production.js:5613
rC @ react-dom-client.production.js:2818
rz @ react-dom-client.production.js:2828
oO @ react-dom-client.production.js:7472
oK @ react-dom-client.production.js:7834
o6 @ react-dom-client.production.js:8678
oK @ react-dom-client.production.js:7802
o6 @ react-dom-client.production.js:8678
oK @ react-dom-client.production.js:7802
o6 @ react-dom-client.production.js:8678
oK @ react-dom-client.production.js:7802
o6 @ react-dom-client.production.js:8678
oK @ react-dom-client.production.js:7802
o6 @ react-dom-client.production.js:8678
oK @ react-dom-client.production.js:7868
o6 @ react-dom-client.production.js:8678
oK @ react-dom-client.production.js:7868
o6 @ react-dom-client.production.js:8678
oK @ react-dom-client.production.js:7838
iv @ react-dom-client.production.js:11190
ig @ react-dom-client.production.js:11050
u7 @ react-dom-client.production.js:10462
u9 @ react-dom-client.production.js:10387
ij @ react-dom-client.production.js:11606
x @ scheduler.production.js:151

```

**Comment by himself65** [comment]
```tsx
/**
 * The global router that wraps the application components.
 */
function Router({
  actionQueue,
  assetPrefix,
}: {
  actionQueue: AppRouterActionQueue
  assetPrefix: string
}) {
  const [state, dispatch] = useReducer(actionQueue)
  const { canonicalUrl } = useUnwrapState(state)
  // Add memoized pathname/query for useSearchParams and usePathname.
  const { searchParams, pathname } = useMemo(() => { // <-- this line
    const url = new URL(
      canonicalUrl,
      typeof window === 'undefined' ? 'http://n' : window.location.href
    )

    return {
      // This is turned into a readonly class in `useSearchParams`
      searchParams: url.searchParams,
      pathname: hasBasePath(url.pathname)
        ? removeBasePath(url.pathname)
        : url.pathname,
    }
  }, [canonicalUrl])

```

**Comment by sam-masscreations** [comment]
@himself65 did you solve this?

**Comment by maiconcarraro** [comment]
This issue happens to me when calling `redirect` in a page.tsx (RSC), it was fixed once I add the `loading.tsx` 🤷‍♂

**Comment by EndyZhou** [comment]
```tsx
import type React from "react";
import { auth } from "@/server/auth";
import type { PropsWithChildren } from "react";
import { redirect } from "next/navigation";

export default async function AuthLayout({ children }: PropsWithChildren) {
  const session = await auth();
  if (session) { // ok
    redirect("/dashboard");
  }

  return <div className="min-h-screen">{children}</div>;
}

```
 When redirect to the dashboard, an error occurs. I don't quite understand why. 🤔
> stitched-error.ts:23 Uncaught Error: Rendered more hooks than during the previous render.

**Comment by EndyZhou** [comment]
> import type React from "react";
> import { auth } from "@/server/auth";
> import type { PropsWithChildren } from "react";
> import { redirect } from "next/navigation";
> 
> export default async function AuthLayout({ children }: PropsWithChildren) {
>   const session = await auth();
>   if (session) { // ok
>     redirect("/dashboard");
>   }
> 
>   return <div className="min-h-screen">{children}</div>;
> }
> When redirect to the dashboard, an error occurs. I don't quite understand why. 🤔
> 
> > stitched-error.ts:23 Uncaught Error: Rendered more hooks than during the previous render.

```tsx
"use client";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

export function ClientRedirect({ url }: { url: string }) {
  const router = useRouter();
  useEffect(() => {
    router.replace(url);
  }, [url, router]);

  return null;
}

```
```tsx
	...
  if (session) {
    return <ClientRedirect url='/dashboard' />
  }
  ...
}
```

No errors remain. Is redirection currently achievable only on the client-side?

**Comment by ZGFuZHk100** [comment]
I think here the issue is that the people are trying to do a redirect in different places, with different tools, and considering everything is just a function.

Solution for each goal:

1. **Redirect from a server component**

```ts
import { redirect } from 'next/navigation'

export default async function ProjectPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params

  if () {
  redirect(`${id}/overview`)
  }

  return null // or JSX
}
```

It's important to notice that this is a React component not a plain function. It MUST return null or JSX. Otherwise when it reaches the frontend (yes, even server components eventually land on the front), it will cause the error mentioned above.
Sorry, hydration hurts a lot.

2. **Redirect from a server action**

```ts
'use server'

import { redirect } from 'next/navigation'

export async function redirectToOverview(id: string) {
  // Your server action logic here
  redirect(`${id}/overview`) // No return needed
}
```

Here we can return or not whatever we want as it's essentially a plain function.

3. **Redirect from a client component**

I also saw people doing something like this 

```ts
  useEffect(() => {
    const performRedirect = async () => {
      const { id } = await params
      router.push(`${id}/overview`)
    }

    performRedirect()
  }, [params, router])
```

Here I don't even know how to start, because it gives me chills. Hopefully, nobody is doing this for real, but just in case please know that you can do this instead:

```ts
'use client'
 
import { redirect, usePathname } from 'next/navigation'
 
export function ClientRedirect() {
  const pathname = usePathname()
 
  if (pathname.startsWith('/admin') && !pathname.includes('/login')) {
    redirect('/admin/login')
  }
 
  return <div>Login Page</div>
}
``` 

Yes, redirect works on the client. And for those who are not using the latest versions of Next, here is the link to their doc, just browse to your version and you'll find a better way than a use effect to do a redirect:
https://nextjs.org/docs/app/api-reference/functions/redirect#client-component


Hope this is helpful for someone. If I'm missing something let me know

P.S. I don't even want to explain why adding a suspense around a wrong-written redirect component works. I think "if it works, then it must be fine" is not cool anymore

**Comment by cpotey** [comment]
Has anyone got any further solutions for this error beyond removing suspense boundaries/loading.tsx entirely? I'm surprised this hasn't been more widely reported to be honest.

I'm trying to improve UX by utilising suspense, but am blocked by this error repeatedly. I have tried using `loading.tsx`, opting for an inlined `<Suspense>`, removing `not-found.tsx` and `<Link>` inside them, and various other "solutions" mentioned in other threads etc, but have got no other fix beyond just straight up removing all instances of `loading.tsx`/`<Suspense>` entirely.

It's a bit frustrating as the dev mode UX (and the built version, when it's not throwing this error!) is fantastic, and Suspense seems amazing, but I am completely blocked in being able to use it anywhere on production at all. 

I'm currently seeming to run into the error when a page renders a `notFound()`/`not-found.tsx` (either Next.js's fallback or a custom one in my codebase) from an API endpoint for a request/page that doesn't exist, but haven't worked a way around it in the front-end to have both suspense AND not found working.

**Comment by arunanshub** [comment]
This issue still exists in nextjs 16 (app router).

**Comment by heecheon92** [comment]
I am also facing this issue but this is a react issue and being tracked at https://github.com/facebook/react/issues/33580 correct?

**Comment by arunanshub** [comment]
facebook/react#36174

raised a PR in React to fix the issue.

**Comment by arunanshub** [comment]
For those who can't wait, apply this patch to Nextjs:

```diff
diff --git a/dist/client/components/app-router.js b/dist/client/components/app-router.js
index 560525f322ce81bc6a9f0a677aed59464dff2887..81b7fa7179bcd94eb025d831e0a603ac843ac8d6 100644
--- a/dist/client/components/app-router.js
+++ b/dist/client/components/app-router.js
@@ -111,6 +111,14 @@ function Head({ headCacheNode }) {
  * The global router that wraps the application components.
  */ function Router({ actionQueue, globalError, webSocket, staticIndicatorState }) {
     const state = (0, _useactionqueue.useActionQueue)(actionQueue);
+    return /*#__PURE__*/ (0, _jsxruntime.jsx)(RouterContent, {
+        state: state,
+        globalError: globalError,
+        webSocket: webSocket,
+        staticIndicatorState: staticIndicatorState
+    });
+}
+function RouterContent({ state, globalError, webSocket, staticIndicatorState }) {
     const { canonicalUrl } = state;
     // Add memoized pathname/query for useSearchParams and usePathname.
     const { searchParams, pathname } = (0, _react.useMemo)(()=>{
```

`package.json`:

```json
    "patchedDependencies": {
      "next@16.2.2": "patches/next@16.2.2.patch"
    }
```

**Comment by KShad10** [comment]
Confirming this still reproduces on **next@16.1.6** with the bundled React canary (`19.3.0-canary-f93b9fd4-20251217`). Our crash signal: `/groups/[id]` route, ~85% **Mobile Safari 26.3 / iOS 18.7**, triggered by server-action dispatches and BFCache `pageshow` restores (App Router fires `ACTION_RESTORE` on those — `app-router.js:147`). Sentry stack bottoms out at the `useMemo` call inside `Router` exactly as described upthread.

The patch [@arunanshub posted on 2026-04-03](https://github.com/vercel/next.js/issues/63121#issuecomment-4184781636) — extracting everything after `useActionQueue` into a child `RouterContent` component — applies cleanly to 16.1.6 (we adapted it for the slightly different compiled output and patched both the CJS and ESM copies under `node_modules/next/dist/{client,esm/client}/components/app-router.js`). Verified via `patch-package`: production build, typecheck, lint, and full test suite pass; the affected user flows (bracket submission/removal, group settings, member/entry removal, navigation back into the page via BFCache) no longer reproduce the crash locally.

Posting in case it helps maintainers gauge the long tail of the bug. +1 on landing facebook/react#36174 or shipping the `RouterContent` extraction in next directly so downstream consumers don't need a patch-package hack.

**Comment by sorsama** [comment]
### Versions
- `next@16.2.5`
- `react@19.2.6` / `react-dom@19.2.6`
- App Router, JWT-strategy auth via `next-auth@5.0.0-beta.31`

```
Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom-client.development.js:8111)
    at updateMemo (react-dom-client.development.js:9055)
    at Object.useMemo (react-dom-client.development.js:28821)
    at Router (app-router.tsx:168:45)   ← the `useMemo({ searchParams, pathname }, [canonicalUrl])`
    at renderWithHooks
    at updateFunctionComponent
    at beginWork
```

The offending hook is the `useMemo` for `{ searchParams, pathname }` near the top of `Router` nothing user-code is doing, but the hook slot is shifting because something earlier in the same render changed. Reproduces with `reactStrictMode: false` as well.

**Comment by gaearon** [comment]
Hi folks, sorry for the super long wait on this. It's fixed upstream in React in https://github.com/react/react/pull/36911. The fix will propagate to Next after the corresponding React canary lands in the Next repo. We can close this then.
