### ISSUE TITLE
App router routing to dynamic route instead of predefined route in Next.js

### ISSUE THREAD

**Issue by MiaoMint** [vercel/next.js#65725]
### Link to the code that reproduces this issue

https://github.com/MiaoMint/nextgram

### To Reproduce

1. Start the application in development (next dev)
2. Click New

### Current vs. Expected behavior

Following the steps in the previous section, I expected to jump to a predefined route, but instead I observed a dynamic route.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Mon Feb 19 19:43:41 PST 2024; root:xnu-8796.141.3.704.6~1/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 18.20.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: 9.1.0
Relevant Packages:
  next: 14.3.0-canary.61 // Latest available version is detected (14.3.0-canary.61).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

**Comment by MiaoMint** [comment]
https://github.com/MiaoMint/nextgram

**Comment by icyJoseph** [comment]
This works fine in latest canary, I see you have 14.0.5, but the latest release is 14.2.3, please try with a latest version.

- https://stackblitz.com/github/MiaoMint/nextgram?file=app%2Fphotos%2Fnew%2Fpage.tsx

**Comment by mefengl** [comment]
@icyJoseph Where is the example that works fine, the link you provided still has issues...

**Comment by icyJoseph** [comment]
🤔 that was working... I should've taken a screenshot. Unfortunately, now I can confirm it is broken

**Comment by fgnass** [comment]
I can confirm that the issue still exists in 14.2.4 – Is there any fix or workaround, or maybe some pointer where to start looking for the root cause?

@leerob If you look at the https://nextgram.vercel.app/ example and open a photo, the `?_rsc=...` responses are always served with `X-Vercel-Cache: MISS`, although they don't do anything dynamic. Also during build, all intercepting routes are reported as `ƒ (Dynamic)`, even when export `const dynamic = "force-static";` is used.

**Comment by leerob** [comment]
That would be because I have a dynamic path `/photos/[id]` but I'm not using `generateStaticParams`.

Fixed here: https://github.com/vercel/nextgram/commit/06a115d2cad2991b9f8163044e58f34309fea29c#diff-afff095bf4a465cc392a34bda04fa200fa11388a2ba95ca8beb7145df2c8c11dR1-R7

Apologies for the confusion!

**Comment by fgnass** [comment]
@leerob thanks a lot for your quick reply! I still get `X-Vercel-Cache: MISS` for all the intercepted routes and their `?_rsc=...` requests, though:

<img width="1299" alt="Screenshot 2024-07-10 at 09 49 40" src="https://github.com/vercel/next.js/assets/89450/e76621f4-08d9-4c96-95ef-a01b3bc29302">

I also deployed your updated version to my own Vercel account, just in case https://nextgram.vercel.app was not yet up-to-date. Am I missing something important here?
