### ISSUE TITLE
Memory spike issue with Next.js 15.1.4 on Azure

### ISSUE THREAD

**Issue by skerdi-zogaj** [vercel/next.js#74855]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.2.0: Fri Dec  6 18:51:28 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.13.1
  npm: 10.8.1
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 15.1.4 // Latest available version is detected (15.1.4).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: standalone
```

### Which example does this report relate to?

This issue is not related to any specific example in the examples folder. The problem occurs in a general Next.js application deployed on Azure.

### Describe the Bug

We are experiencing a significant memory spike and auto-scaling issues when using Next.js 15.1 in our Azure deployments. Memory usage increases unpredictably under typical traffic conditions, leading to higher resource utilization and triggering unnecessary auto-scaling.

When downgrading to Next.js 14.2, these issues are resolved, and memory usage returns to stable levels. This suggests a regression introduced in version 15.1.

Graphs comparing memory usage for versions 15.1 and 14.2 are attached below for reference.

![Image](https://github.com/user-attachments/assets/9b4fa01f-c9e5-44ab-9aee-ecb7e332cba8)

![Image](https://github.com/user-attachments/assets/7e14e615-4366-4dbe-8d55-e4cbf43bb15b)

### Expected Behavior

Memory usage should remain stable and consistent under typical traffic conditions when using Next.js 15.1, similar to the behavior observed in Next.js 14.2.

### To Reproduce

Deploy a Next.js 15.1 application on Azure with typical production traffic patterns.
Monitor the memory usage and auto-scaling behavior using Azure's monitoring tools.
Observe that memory usage increases significantly and unpredictably, causing auto-scaling to trigger even under normal load.
Downgrade the application to Next.js 14.2.
Re-monitor the application, noticing that memory usage stabilizes and auto-scaling behaves as expected.

![Image](https://github.com/user-attachments/assets/ffeb6497-bd6e-4a31-8525-87d66f6a3546)

![Image](https://github.com/user-attachments/assets/c7063e2d-f1c4-4dd9-8d06-67a2570f55ea)

**Comment by frankbo** [comment]
We are facing a similar issue in our kubernetes pods. With Nextjs 15.1.3 the memory consumption was/is fine and the pods run as expected, but with the update to 15.1.4 the pods want to consume more and more memory and die at some point. Normally our pods use 110mb memory and are fine with that. With the update to Nextjs 15.1.4 they start with 115 and the memory get up to 300mb, then they die and it starts over again. From the graphs it looks like a memory leak or at least something that consumes more memory then necessary over time.
Let me know if you need further information.

**Comment by vitalyiegorov** [comment]
We are facing the same issue with the Node 22.13 on NextJS 15.1.4

**Comment by cjcheshire** [comment]
I don't want to do the me too… `node:20-alpine` + `NextJS 15.1.4`. We have dropped back to `NextJS 15.1.3` to see if it settles.

Hard to create an example repo for this. We have 40+ page templates (1400 pages) that use unstable_cache to revalidate every 10 minutes. We also have a couple of apis.

You can see when we deployed 15.1.4:

<img width="1886" alt="Image" src="https://github.com/user-attachments/assets/eddf504a-d9a7-4c41-8261-a65c32b19f7e" />

**Comment by skerdi03** [comment]
> We are facing a similar issue in our kubernetes pods. With Nextjs 15.1.3 the memory consumption was/is fine and the pods run as expected, but with the update to 15.1.4 the pods want to consume more and more memory and die at some point. Normally our pods use 110mb memory and are fine with that. With the update to Nextjs 15.1.4 they start with 115 and the memory get up to 300mb, then they die and it starts over again. From the graphs it looks like a memory leak or at least something that consumes more memory then necessary over time. Let me know if you need further information.
> 
> [@skerdi03](https://github.com/skerdi03) did you try version 15.1.3 as well. And do you face the same issues there?

Yes, we had the same issue with 15.1.3 as well

**Comment by justinadkins** [comment]
We've experienced memory issues since 15.1.x, 15.0.x is stable for us. Deployed on AWS via FlightControl. We're running Node 18 right now.

**Comment by lubieowoce** [comment]
We've identified one leak that became much more noticeable in `15.1.4` -- specifically, since that release, it'd cause each revalidation to leak a promise that'd then stick around forever (in `next start`). That fix is here: https://github.com/vercel/next.js/pull/75041). We'll update this thread when it's out.

**Comment by huozhi** [comment]
The fix mentioned above is landed in v15.1.6, please upgrade and let us know if that fixes your issue 🙏 Thanks

**Comment by sbehrends** [comment]
For us looks like the latest version fixed the issue.

Here is memory usage before and after the update.
![Image](https://github.com/user-attachments/assets/5adc6c26-6cbb-434a-af91-96b4835790d7)

**Comment by DonikaV** [comment]
As i can see on the graphs of memory usage the problem has been fixed in 15.1.6

**Comment by farzadsoltani** [comment]
I have noticed that it's been climbing much slower than previously, but I can definitely still see more RAM usage compared to 15.0.x and a much higher jump compared to 14.x.

On 14.x, we would average around 300-400mb per pod. On 15.0.x the average would be around 400-500mb. But I've been seeing 600mb+ each time I check my pods. Something's not quite right.

**Comment by maxigs7** [comment]
> I have noticed that it's been climbing much slower than previously, but I can definitely still see more RAM usage compared to 15.0.x and a much higher jump compared to 14.x.
> 
> On 14.x, we would average around 300-400mb per pod. On 15.0.x the average would be around 400-500mb. But I've been seeing 600mb+ each time I check my pods. Something's not quite right.

We tried the same 15.1.6, but it is still happening, even though we created a container to measure it and the memory usage is going up. We finally downgraded it to version 15.0.3, and everything stabilized. We are not using any server-side feature, only the pages router, and with no getServerSide props.

**Comment by justinadkins** [comment]
We are still seeing a pretty significant memory leak on `15.1.6`. I was hopeful this was the fix. `15.0.x` is stable for us. We deployed the version bump yesterday.

<img width="1785" alt="Image" src="https://github.com/user-attachments/assets/1a662eb9-98e5-4da0-ab10-b76ed44fb821" />

**Comment by DonikaV** [comment]
@justinadkins 
In our case the issue has been fixed after 15.1.6, maybe you have other problems? 
Have you tried something from, here? 
 https://nextjs.org/docs/app/building-your-application/optimizing/memory-usage

<img width="1556" alt="Image" src="https://github.com/user-attachments/assets/672a3e6a-99a8-46e5-872a-3774866fbf0e" />

**Comment by justinadkins** [comment]
@DonikaV I have taken a look at that documentation and done some troubleshooting. I don't have a memory leak in `15.0.4` but I have one in `15.1.6`. There is either something about my codebase that becomes leaky in `15.1.x` or something included in the Next bump that is now leaking in certain scenarios.

**Comment by TJC** [comment]
We're also seeing quite a bad memory leak on 15.1.6. It's not as severe as 15.1.4, but it's still quite problematic, such that we had to revert the upgrade.

Let me know if it's helpful for us to measure the requests vs memory usage, to give you an idea of scale?

**Comment by frankbo** [comment]
For us the memory consumption is again at 110mb. We had one weird peak up to 300mb, but I think that had nothing to do with nextjs. Since the update to 15.1.6 the Pods run fine again. If you need further information how we are using nextjs let me know.

**Comment by aakashbapna** [comment]
We had recently upgraded from next 14.2.x to 15.1.x. We encountered similar memory leak issues with next 15.1.x. Upgrading to next 15.1.6 didn't help reduce memory usage. Our pod memory usage kept growing and they would eventually get killed with OOM. 

Things stabilized when we downgraded to next 15.0.4, we saw dramatically less memory usage hovering around 120mb per pod like earlier (next 14.2.x).

We extensively use middleware and are fully on app router.

Next 15.1.6 vs Next 15.0.4

<img width="686" alt="Image" src="https://github.com/user-attachments/assets/48f7303f-08ba-457d-843b-b9369007ee53" />

**Comment by dennieriechelman** [comment]
We are experiencing exactly the same on two of our ecommerce sites with medium/low traffic (around 2M request per day). Please see screenshot for the next.js versions that we deployed.

Some more info:
- Running in latest k8s on a node:20.15.0-alpine container.
- We do some work in the middleware (Mostly deleting cookies for some request, updating token if expired)

I have tried to do some heap dump analysis but did not get far.

If there is any more info that could help you please let me know. I would really like to be able to update our app.

![Image](https://github.com/user-attachments/assets/75e7be23-20cf-4f40-829d-dbe7199a126d)

**Comment by justinadkins** [comment]
As stated above, we are still affected by memory leaks on 15.1.6. Our project is using:
- Middleware primarily for auth, we use Clerk (using `clerkMiddleware` function)
- App router
- Sentry for exception observability

**Comment by wslp12** [comment]
Memory leakage occurs at 15.1.6 due to the same issue.
What is peculiar is that the cpu usage rate is also very high (issue version)

Logically, it is the smae phenomnon when trying only the return null in rootLayout

additional information
node: 20.15.1
setnry/core: 8.42.0
sentry/nextjs: 8.42.0
sentry/utils: 8.42.0

**Comment by Jax-p** [comment]
> Memory leakage occurs at 15.1.6 due to the same issue.
> What is peculiar is that the cpu usage rate is also very high (issue version)
> 
> Logically, it is the smae phenomnon when trying only the return null in rootLayout
> 
> additional information
> node: 20.15.1
> setnry/core: 8.42.0
> sentry/nextjs: 8.42.0
> sentry/utils: 8.42.0

Have you tried to turn off Sentry? In our case 15.0.4 is runnable with Sentry/Next 8.5X.X but every other version leaks memory. But without Sentry, even 15.1.6 looks much better.

**Comment by masterkain** [comment]
a standalone app I deployed on my cluster usually uses around 100MB, it's balooning to 2GB, never used sentry

**Comment by mhanbl** [comment]
We suffered a memory leak on AWS/ECS ever since 15.1.x - we just downgraded to 15.0.4 and that seems to have solved it

<img width="1152" alt="Image" src="https://github.com/user-attachments/assets/b8d3bc71-984e-4cdb-bd1f-c0d4818ddee6" />

**Comment by Maclay74** [comment]
Hey, we have the same problem on 15.1.6. I noticed that it happens once I add middleware to the application. 
It's very easy to reproduce by creating a new application via create-next-app. Test it with and without middleware.

**Comment by peec** [comment]
We are experiencing the same issues, running in standalone nextjs using middleware on our kubernetes cluster.

When we downgraded to 15.0.4 the memory leak was gone.

**Comment by dennieriechelman** [comment]
> Hey, we have the same problem on 15.1.6. I noticed that it happens once I add middleware to the application. It's very easy to reproduce by creating a new application via create-next-app. Test it with and without middleware.

Thanks @Maclay74 . I also came to the same conclusion. What exactly did you add to the middleware?

**Comment by Maclay74** [comment]
> > Hey, we have the same problem on 15.1.6. I noticed that it happens once I add middleware to the application. It's very easy to reproduce by creating a new application via create-next-app. Test it with and without middleware.
> 
> Thanks [@Maclay74](https://github.com/Maclay74) . I also came to the same conclusion. What exactly did you add to the middleware?

Literally nothing, just an empty function. The fact that the middleware presents in the app causes leaks, apparently.

**Comment by u11d-aleksy-bohdziul** [comment]
In our case, upgrading the NodeJS version from 20.15.1 to 23.6.1 seems to have fixed the issue.

We're running our nextjs server on ECS Fargate and we noticed a memory issue during a stress tests, where we suddenly had a much higher memory usage, which didn't drop down after the tests finished.
In our case this was caused by NodeJS not cleaning up old `Timeout` objects.

I was able to reproduce this issue in both Next.js 15.1.6 and 15.0.4, but in 15.0.4 the issue only appears after setting the flag`experimental.after` to true. That's because the flag `experimental.after` was removed in Next.js 15.1 and the feature tied to it is now always enabled. 
The part of this feature causing our issue is this `setTimeout` call: https://github.com/vercel/next.js/blob/58e1bd29a1563032244ee6d3ca689eb255756e0d/packages/next/src/server/web/adapter.ts#L299-L301

For some reason, the Timeout objects created by this setTimeout call were never cleaned up by NodeJS, and they also prevented quite a few other objects from being garbage collected.

Here’s a screenshot of the heap snapshot from our Next.js server, taken about 2 hours after the stress tests ended:

<img width="654" alt="Image" src="https://github.com/user-attachments/assets/4ee69371-4241-41c0-b420-b40298096f62" />

Each of those nearly 20 000 Timeouts is created by the setTimeout invocation mentioned above. All of them are marked as destroyed, and are only retained by `knownTimersById`, which from my understanding shows that this is a purely NodeJS issue.

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/e9c69fd6-6a6f-4a3e-9cbd-371cd997ca0b" />

**Comment by lubieowoce** [comment]
@u11d-aleksy-bohdziul Thank you so much for tracking this down! I believe this might be caused by this nodejs bug: https://github.com/nodejs/node/issues/53335.
In middleware (and other edge functions) we're wrapping `setTimeout` so that it returns a `number` instead of a `NodeJS.Timeout`, so we'd run into the same leak.

AFAICT [the fix for that](https://github.com/nodejs/node/pull/53337) was released in:
- [node v20.16.0](https://github.com/nodejs/node/pull/53945)
- [node v22.4.0](https://github.com/nodejs/node/pull/53583)
- node v23.0.0

**For anyone still experiencing leaks on `15.1.6`, please try updating your node to one of the above versions and see if that solves it.**

**Comment by wslp12** [comment]
> AFAICT [the fix for that](https://github.com/nodejs/node/pull/53337) was released in:
> - [node v20.16.0](https://github.com/nodejs/node/pull/53945)
> - [node v22.4.0](https://github.com/nodejs/node/pull/53583)
> - node v23.0.0
> 
> **For anyone still experiencing leaks on Next.js 15.1.6, please try updating your node to one of the above versions and see if that solves it.**

Solve thanks

**Comment by Maclay74** [comment]
Hey @lubieowoce (me too), I tested 15.1.6 on 20.16.0 and 22 versions of Node, and 20.16.0 still leaks some memory in our application, whereas 22 is totally stable.

**Comment by justinadkins** [comment]
The `setTimeout` Node issue ended up being the culprit for us! We were using a version of nixpacks which under the hood was using Node `22.3.0`. After updating to the latest version which uses `22.10.0` our issue resolved. Thank you @u11d-aleksy-bohdziul for surfacing 🙏

**Comment by dymoo** [comment]
> We suffered a memory leak on AWS/ECS ever since 15.1.x - we just downgraded to 15.0.4 and that seems to have solved it
> 
> <img alt="Image" width="1152" src="https://private-user-images.githubusercontent.com/87980193/409869673-b8d3bc71-984e-4cdb-bd1f-c0d4818ddee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkwOTQwNjMsIm5iZiI6MTczOTA5Mzc2MywicGF0aCI6Ii84Nzk4MDE5My80MDk4Njk2NzMtYjhkM2JjNzEtOTg0ZS00Y2RiLWJkMWYtYzBkNDgxOGRkZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA5VDA5MzYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZTVkM2JmMTA3ZDY3NWRlMjk3YjVjZDQwY2MzNzFmZjllMDQxMDdjYWUyNzFmY2U2NjU0MzViMWYzZGQ3ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iC-1rRj4qPd_s3LjXiuYAu5IrlD0ENEI3xv81FUxc8s">

leak on 23.7-bookworm on ECS ARM fargate next v15.1.6 -- I'm re-running with '--heapsnapshot-signal=SIGUSR2' to see whats up...

<img width="570" alt="Image" src="https://github.com/user-attachments/assets/b9896479-4140-4992-ab86-39b8a1f020ec" />

**Comment by dennieriechelman** [comment]
@u11d-aleksy-bohdziul and @lubieowoce thank you for finding this out and providing a solution.

This morning we updated to node:23.7.0-alpine with Next 15.1.6 and we are not seeing memory leaks anymore! 🚀

**Comment by maxigs7** [comment]
@u11d-aleksy-bohdziul @lubieowoce awesome finding.

We updated it to node 22.12 and everything looks fine at the moment.

Thank you!

**Comment by farzadsoltani** [comment]
Upgraded to Node v22.13.1 and Next.js v15.1.6 and not noticing any more memory leaks.

**Comment by lubieowoce** [comment]
We've just shipped [15.1.7](https://github.com/vercel/next.js/releases/tag/v15.1.7) with a fix that should mitigate this on older node versions. So if you can't upgrade node to a version where this problem is fixed, please try that

**Comment by dymoo** [comment]
Fixed our leak.

Thank you nextjs team!
