### ISSUE TITLE
[next-devtools] TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by PlagueFPS** [vercel/next.js#81467]
### Link to the code that reproduces this issue

https://github.com/PlagueFPS/next-dev-tools-issue-repro

## Steps to Reproduce

1. **Clone the repository**
   ```
   git clone <repository-url>
   cd <repository-directory>
   ```

2. **Install dependencies**
   ```
   pnpm install
   ```

3. **Start the development server**
   ```
   pnpm run dev
   ```

4. **Observe the error**
   - The error should appear in the terminal and in the dev tools in the bottom right corner.

### Current vs. Expected behavior

**Current behavior**:
On page load, the TypeError issue is shown both in the terminal and next-devtools. This drastically slows down the HMR process since it needs to process the error, and hard re-load the page.

**Expected behavior**:
No TypeError on page load, resulting in a smooth HMR experience.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 32586
  Available CPU cores: 16
Binaries:
  Node: 21.0.0
  npm: 10.2.0
  Yarn: N/A
  pnpm: 9.13.2
Relevant Packages:
  next: 15.4.0-canary.120
  eslint-config-next: N/A
  react: 19.1.0
  react-dom: 19.1.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack, Module Resolution, Runtime, TypeScript

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested my reproduction against different canary releases, and the first one that introduced the bug was "15.4.0-canary.110", since reverting to `15.4.0-canary.109` it works.

**Comment by huozhi** [comment]
I cannot repro it, the app seems fairly simple. Do you have any stack traces or screenshot that can share where the error is from?

**Comment by PlagueFPS** [comment]
<img width="950" height="1068" alt="Image" src="https://github.com/user-attachments/assets/d9229859-bc5a-4271-b70d-1cf1c538f3c4" />

**Comment by PlagueFPS** [comment]
> I cannot repro it, the app seems fairly simple. Do you have any stack traces or screenshot that can share where the error is from?

I can provide the full stack trace if needed; it is quite long.

**Comment by icyJoseph** [comment]
Sorry to chime in but I see that this commit between https://github.com/vercel/next.js/compare/v15.4.0-canary.109...v15.4.0-canary.110

- https://github.com/vercel/next.js/commit/af0dd9eef47676f0539f963ed9e28006bf5a9a78 

added base-ui, and in your screenshot I see, detectBrowser:

- https://github.com/mui/base-ui/blob/06c1fb2f7cac6e1b2ea81fa1fa38c545bceba7e4/packages/react/src/utils/detectBrowser.ts#L28

Which does a toLowerCase call

## Edit

(I accidentally submitted before finishing the post)

This issue, https://github.com/mui/base-ui/issues/2259, reports a similar problem, and was patched here, https://github.com/mui/base-ui/pull/2273

I guess, we just need to bump the package in the devtools. @huozhi @PlagueFPS

**Comment by PlagueFPS** [comment]
Yeah, I am not on a Mac which may have been what cause the issue for me.

**Comment by icyJoseph** [comment]
What browser are you using @PlagueFPS or how is your dev setup?

**Comment by PlagueFPS** [comment]
I am using MS Edge, my dev setup is just my IDE and browser.

Edit: on windows 11

**Comment by icyJoseph** [comment]
Didn't mean to be blunt, just trying to figure out if this is the root issue. Many arrows are pointing that way, but I'd like to confirm for sure. 

So if you run this in your browser's console:

```tsx
const hasNavigator = typeof navigator !== 'undefined';

function getPlatform() {
    if (!hasNavigator) {
        return '';
    }
    const uaData = navigator.userAgentData;
    if (uaData === null || uaData === void 0 ? void 0 : uaData.platform) {
        return uaData.platform;
    }
    return navigator.platform;
}
```

we should see undefined?

**Comment by PlagueFPS** [comment]
No worries, appreciate you being thorough in your process. Yes, I get undefined in my browser's console.

**Comment by huozhi** [comment]
Thanks for the report, I've patched a fix, please let us know if it's fixed in next canary version. Appreciate the testing against the latest canary releases ❤️

**Comment by PlagueFPS** [comment]
Glad I could help! Thanks for the fix, I'll be sure to comment here again if it works.

**Comment by PlagueFPS** [comment]
@huozhi latest release unfortunately did not resolve the issue. The stack trace did change slightly though: 

<img width="956" height="1072" alt="Image" src="https://github.com/user-attachments/assets/6954a516-9758-49da-9e80-2936a87fce8f" />

**Comment by icyJoseph** [comment]
Hi, I think we didn't do the modification in all places necessary, I can try to make a PR

## Edit

We noticed some style imports were not excluded, a new PR should be coming up soon.

**Comment by PlagueFPS** [comment]
@huozhi @icyJoseph Issue has been resolved with the `15.4.0-canary.123`. Appreciate you guys working through this and getting a fix in the same day! ❤️
