### ISSUE TITLE
nodeMiddleware Option inconsistent unusable in canary and 15.4.4

### ISSUE THREAD

**Issue by larsilus** [vercel/next.js#82122]
### Link to the code that reproduces this issue

https://github.com/larslaegnerfrequi/buggy-nodemiddleware

### To Reproduce

pnpm next build

 ⚠ Invalid next.config.ts options detected: 
 ⚠     Unrecognized key(s) in object: 'nodeMiddleware' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
   ▲ Next.js 15.4.2-canary.18
   - Experiments (use with caution):
     ✓ nodeMiddleware

   Creating an optimized production build ...
 ✓ Compiled successfully in 1000ms
   Linting and checking validity of types  .Failed to compile.

./next.config.ts:7:5
Type error: Object literal may only specify known properties, and 'nodeMiddleware' does not exist in type 'ExperimentalConfig'.       

   5 |   reactStrictMode: true,
   6 |   experimental: {
>  7 |     nodeMiddleware: true
     |     ^
   8 |   },
   9 | };
  10 |
Next.js build worker exited with code: 1 and signal: null
 .

so i cannot activate it when using canary,

but when using 15.4.4 i get the error:

pnpm run dev

> @ dev C:\DEV\SRC\test\nextjs\buggy-nodemiddleware
> next dev

node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[CanaryOnlyError: The experimental feature "experimental.nodeMiddleware" can only be enabled when using the latest canary version of Next.js.]

=> so no way anymore to activate nodeMiddleware

### Current vs. Expected behavior

i want to activate nodeMiddleware for next dev and next build with standalone output.
Not possible.

### Provide environment information

```bash
npm warn Unknown env config "verify-deps-before-run". This will stop working in the next major version of npm.
npm warn Unknown env config "verify-deps-before-run". This will stop working in the next major version of npm.
'yarn' is not recognized as an internal or external command,
operable program or batch file.

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Enterprise
  Available memory (MB): 32767
  Available CPU cores: 12
Binaries:
  Node: 24.4.1
  npm: 11.4.2
  Yarn: N/A
  pnpm: 10.13.1
Relevant Packages:
  next: 15.4.2-canary.18 // Latest available version is detected (15.4.2-canary.18).
  eslint-config-next: N/A
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.8.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Middleware

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by icyJoseph** [comment]
Hi,

Move the `app/middleware.ts` to the root, `middleware.ts`, and then AFAIK, you still need to use `NextRequest`/`Request` and create `NextResponse`/`Response` within the middleware:

```ts
// nodeMiddleware.ts
import { randomBytes } from 'crypto'
import { NextRequest, NextResponse } from 'next/server'

export default function nodeMiddleware(
  req: NextRequest
) {
  console.log('🔥 Node middleware is running')
  console.log('Random byte:', randomBytes(1))

  const res = NextResponse.next()
  res.headers.set('x-node-middleware', 'active')

  return res
}

export const config = {
  runtime: 'nodejs'
}

```

Don't forget to include the config. 

<img width="1503" height="473" alt="Image" src="https://github.com/user-attachments/assets/f04d3353-5a4c-4669-86db-b66272f1ea6a" />

And yes, you should just remove the config:

**Comment by kavish-p** [comment]
For those willing to downgrade the package while this is fixed, the latest canary version where nodeMiddleware works fine is `15.4.2-canary.12`

**Comment by larsilus** [comment]
@icyJoseph  thanks, I got it working on 15.4.2-canary.19 with your fixes and when removing the experimental config (see my git repo). 

but there seems to be another error so still cannot build, 
it does work on my windows machine in terminal in vscode (non-admin) with:
1) rm -rf node_modules && pnpm install -node-linker=hoisted && pnpm run build
but not with
2) rm -rf node_modules && pnpm install && pnpm run build  # only works when i am in a admin window, not as a non-admin

=> so there are symlinks issues for non admin terminals on windows, the same with bun instead of pnpm. i will open another ticket for it.

**Comment by icyJoseph** [comment]
Hi, awesome that you got it working. 

For your next issue, please include as many logs as possible, and package manager configuration if possible too.

Make sure to discard this is not a VSCode terminal issue too. 

Also please use code block highlighting https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks as that makes reading through your code examples easier

If this issue is resolved for now, let's close the issue report.
