### ISSUE TITLE
Next.js 16 with cacheComponents: "Next.js cannot guarantee that Cache Components will run as expected due to the current runtime's implementation of setTimeout()." when using Bun

### ISSUE THREAD

**Issue by Thanaen** [vercel/next.js#87630]
### Link to the code that reproduces this issue

https://github.com/Thanaen/next-bun-cache-components

### To Reproduce

1. Create a new Next.js project with default values.
2. Update `next.config.ts` to 
```ts
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
  cacheComponents: true,
};

export default nextConfig;

```

3. Update the scripts to use bun
```json
{
    "dev": "bun --bun next dev",
    "build": "bun --bun next build",
    "start": "bun --bun next start",
    "lint": "eslint"
  }
```

4. Run bun dev
Output
```
$ bun --bun next dev
▲ Next.js 16.1.0 (Turbopack, Cache Components)
- Local:         http://localhost:3000
- Network:       http://10.255.255.254:3000

✓ Starting...
✓ Ready in 603ms
```

5. Go to http://localhost:3000
Output
```
Next.js cannot guarantee that Cache Components will run as expected due to the current runtime's implementation of `setTimeout()`.
Please report a github issue here: https://github.com/vercel/next.js/issues/new/
 GET / 200 in 1838ms (compile: 1550ms, render: 288ms)

```

### Current vs. Expected behavior

I expected output:
```
$ bun --bun next dev
▲ Next.js 16.1.0 (Turbopack, Cache Components)
- Local:         http://localhost:3000
- Network:       http://10.255.255.254:3000

✓ Starting...
✓ Ready in 603ms
 GET / 200 in 1838ms (compile: 1550ms, render: 288ms)
```

Current output:
```
$ bun --bun next dev
▲ Next.js 16.1.0 (Turbopack, Cache Components)
- Local:         http://localhost:3000
- Network:       http://10.255.255.254:3000

✓ Starting...
✓ Ready in 603ms
**Next.js cannot guarantee that Cache Components will run as expected due to the current runtime's implementation of `setTimeout()`.
Please report a github issue here: https://github.com/vercel/next.js/issues/new/**
 GET / 200 in 1838ms (compile: 1550ms, render: 288ms)
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025
  Available memory (MB): 15836
  Available CPU cores: 20
Binaries:
  Node: 25.2.1
  npm: 11.6.2
  Yarn: 1.22.22
  pnpm: 10.23.0
Relevant Packages:
  next: 16.1.0 // Latest available version is detected (16.1.0).
  eslint-config-next: N/A
  react: 19.2.3
  react-dom: 19.2.3
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

cacheComponents

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Related: [Bun issue](https://github.com/oven-sh/bun/issues/25639)

**Comment by paperclover** [comment]
@lubieowoce what was the purpose of https://github.com/vercel/next.js/pull/86018, the patch adding this warning? the pr description lacks a problem statement or links to any issues. the code within is extremely difficult to understand, and makes me wonder if there are alternatives to whatever the goal was, avoiding the need to depend on more undocumented and [legacy](https://nodejs.org/api/documentation.html#stability-index) node.js APIs.

**Comment by lubieowoce** [comment]
TLDR: This is currently expected behavior. We rely on certain event loop behaviors in node and haven't had time to vet them in Bun yet. When we confirm that it all works fine, the warning will be removed.

---

@paperclover The warning actually originated in #86093, that's the one you should be looking at:
https://github.com/vercel/next.js/pull/86093/changes#diff-e695f070e222cfe1d22d8e089f6087b24f910898f1372b65d846b1080eb9f7cfR91

The motivation for that one is that, as part of Cache Components rendering, we need
```js
setTimeout(one, 0)
setTimeout(two, 0)
```
to run in the same iteration of the event loop, with no other tasks sneaking in between. This lets us separate things into separate "stages" (1 task = 1 stage) while not letting any uncached IO finish, which is fundamental to Cache Components.

You might think that this'd just work, but it's not guaranteed, and caused a decent amount of CI flakiness, because a `setImmediate` scheduled by React was _sometimes_ running too early (between the two timers). When something like this happens, we either we end up with too little content in the static shell (for internal React reasons), or too much content (if IO manages to resolve). This subverts the Cache Components programming model so we can't let that happen.

Which brings us to the patch. In node, we can make sequential `setTimeout` act consistently using the ugly hacks in `createAtomicTimerGroup` (see [this comment](https://github.com/vercel/next.js/blob/31b62520366aefef9d6800cd519157a16f958052/packages/next/src/server/app-render/app-render-scheduling.ts#L4) for more on that).

I have not had time to investigate the exact behavior of this in Bun, and most of our users are on Node. So for things that aren't node, we essentially say "you're on a runtime we haven't tested, weird stuff might happen, beware" and then figure out if/how we can support alternative runtimes in the future.
I'm unlikely to have time for this anytime soon, so if someone's interested in researching how this works in Bun, I'll happily accept help :)

---

> avoiding the need to depend on more undocumented and [legacy](https://nodejs.org/api/documentation.html#stability-index) node.js APIs.

I'm guessing you're referring to `process.nextTick` which is marked as legacy. We rely on it in a couple places, almost exclusively as `queueMicrotask(() => process.nextTick(callback))` which is a trick to run`callback` after the microtask queue is exhausted. It's used [in other places too](https://github.com/graphql/dataloader/blob/d4f559500848d9894b785b0e35e0aaff89d5c350/src/index.js#L246-L248). There's currently no standard replacement for it, and it's pretty load-bearing, so we're likely stuck with it for the forseeable future.

**Comment by lubieowoce** [comment]
I figured I'd go check. Bun has the same inconsistent behavior as node, so the warning is accurate.

Here's a simpler test than the one in [this comment](https://github.com/vercel/next.js/blob/31b62520366aefef9d6800cd519157a16f958052/packages/next/src/server/app-render/app-render-scheduling.ts#L4) for more on that):

```js
"use strict";

const iterations = process.env.ITERATIONS
  ? Number.parseInt(process.env.ITERATIONS)
  : 100;

async function run() {
  for (let i = 0; i < iterations; i++) {
    const ok = await checkTimeouts();
    if (!ok) {
      console.log(`immediate ran before the second timeout (iteration: ${i})!`);
      process.exit(1);
    }
  }
  console.log(`ran ${iterations} iterations without interleaving`);
  process.exit(0);
}

function checkTimeouts() {
  return new Promise((resolve) => {
    let immediateRan = false;
    setTimeout(() => {
      setImmediate(() => {
        immediateRan = true;
      });
    });
    setTimeout(() => {
      const ok = !immediateRan // the timeout should run first.
      resolve(ok);
    });
  });
}

run();
```

Legend for the outputs:
- "ran N iterations without interleaving" = good
- "immediate ran before the second timeout"  = bad

And the results on my mac:

```terminal
$ node --version
v20.19.3
$ ITERATIONS=10000 node test.js
immediate ran before the second timeout (iteration: 276)!
$ ITERATIONS=10000 node test.js
immediate ran before the second timeout (iteration: 147)!
$ ITERATIONS=10000 node test.js
immediate ran before the second timeout (iteration: 0)!
$ ITERATIONS=10000 node test.js
immediate ran before the second timeout (iteration: 258)!
$ ITERATIONS=10000 node test.js
immediate ran before the second timeout (iteration: 216)!
```
```terminal
$ bun --version
1.3.5
$ ITERATIONS=10000 bun test.js 
immediate ran before the second timeout (iteration: 91)!
$ ITERATIONS=10000 bun test.js 
ran 10000 iterations without interleaving
$ ITERATIONS=10000 bun test.js 
ran 10000 iterations without interleaving
$ ITERATIONS=10000 bun test.js 
immediate ran before the second timeout (iteration: 5300)!
$ ITERATIONS=10000 bun test.js 
immediate ran before the second timeout (iteration: 6939)!
```

So, Bun does exhibit the same issue that the patch tries to solve. I don't know if or how we can make this work there. Like I said, help welcome.

(And before anyone suggests it -- we can't just switch to sequential `setImmediate` instead. It affects a bunch of things, e.g. for how we integrate with IO tracking in React Devtools. It's a complicated topic)

**Comment by magnusriga** [comment]
In summary, is it correct that we cannot use the `bun` runtime with Next.js 16, assuming `cacheComponents: true`?

**Comment by lubieowoce** [comment]
I would say "use Bun at your own risk". The main risk is that things like an uncached `fetch` that should be omitted from the static shell will accidentally become part of it, which would be a form of cache poisoning. But you may also never hit this. For example, if all uncached IO happens after `await connection()`), you should be fine *in practice*.

**Comment by Thanaen** [comment]
https://github.com/oven-sh/bun/issues/25639#event-22005214287

Bun seems to consider that this issue is now fixed

**Comment by 190n** [comment]
> Bun seems to consider that this issue is now fixed

From the fix they shipped (oven-sh/bun#26021), it seems like they have made the warning go away (by adding an `_idleStart` property) but they still don't let user code control timer execution order like Node.js does (they don't examine `_idleStart`; writes to it do nothing). So I wouldn't consider the issue fixed. I opened oven-sh/bun#26508 tracking this. I haven't thoroughly tested how this may affect Next.js, though; I only tested the example script in a comment which demonstrates the execution order issue.

**Comment by magnusriga** [comment]
Is it safe to block all access to server acion "x" on a proxy server or on Cloudflare? Meaning all Next-Action headers with value "x". Or all that are shorter than 20 char.

 Would "x" ever be a real server action? I believe they are longer hashes normally.

**Comment by luizvergennes** [comment]
Looks like Bun fixed this issue, is anyone able to validate/confirm:
https://github.com/oven-sh/bun/pull/36859

**Comment by netfishx** [comment]
Re: the validation request for Bun 1.4 (oven-sh/bun#36859) — partial confirmation from testing Next 16.3.1 standalone under Bun 1.4.0:

- The `setTimeout` warning path looks fixed (no more cacheComponents setTimeout warning).
- However, with `cacheComponents: true` + `partialPrefetching: true`, every plain GET leaks 2× `unhandledRejection: Error: Route / needs to bail out of prerendering at this point because it used Date.now()` (digest `NEXT_PRERENDER_INTERRUPTED`) under `bun server.js`. The identical standalone build under Node 26 leaks 0.

Minimal 3-file repro + flag bisection (the leak requires `partialPrefetching`; `cacheComponents` alone is clean) filed at oven-sh/bun#39847. Also reproduced on Bun canary.

**Comment by marcoshernanz** [comment]
Thanks for the report. This was fixed upstream in Bun 1.4.0 by oven-sh/bun#36859. I verified the original Next.js 16.1.0 repro warns on Bun 1.3.5, while Bun 1.4.0 serves it without the warning and passes the timer-ordering check. The `partialPrefetching` rejection leak is separate and remains tracked in oven-sh/bun#39847. Closing as resolved upstream.
